<?php
// French translation of eraseCache, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:27
$GLOBALS['__l10n']['use eraseCache']='utiliser eraseCache';

# index.php:34
$GLOBALS['__l10n']['No dirs deleted.']='Aucun dossier supprimé';

# index.php:44
$GLOBALS['__l10n']['Deleted dirs :']='Dossiers supprimé :';

# index.php:55
$GLOBALS['__l10n']['Unable to change the type']='Impossible de changer le type';

# index.php:69
$GLOBALS['__l10n']['To select the files with removed :']='Sélectionner les dossiers à supprimer :';

# index.php:79
$GLOBALS['__l10n']['Click on the button to erase the temporary files']='Cliquez sur le bouton pour effacer les fichiers temporaires';

# index.php:80
$GLOBALS['__l10n']['Remove the temporary files']='Supprimer les fichiers temporaires';

# index.php:103
$GLOBALS['__l10n']['Are you sure you want to remove the temporary files?']='Souhaitez-vous vraiment supprimer les fichiers temporaires ?';

# index.php:105
$GLOBALS['__l10n']['Are you sure you want to change permissions ?']='Souhaitez-vous vraiment changer les permissions ?';

# index.php:122
# index.php:142
$GLOBALS['__l10n']['Form']='Formulaire';

# index.php:128
$GLOBALS['__l10n']['Allows to erase the temporary files of your blog']='Permet d\'effacer les fichiers temporaires de votre blog';

# index.php:131
$GLOBALS['__l10n']['Restriction']='Restriction';

# index.php:132
$GLOBALS['__l10n']['Change the permissions in the menu "users"']='Changer les permissions dans le menu "utilisateurs"';

# index.php:136
$GLOBALS['__l10n']['Beware of files you delete, choose not support any of the system files.']='Attention aux dossiers que vous supprimez, ne choisissez en aucun cas les fichiers système.';

# index.php:138
$GLOBALS['__l10n']['The default file cache are:']='Les fichiers par défaut du cache sont :';

# index.php:144
$GLOBALS['__l10n']['The dirs is empty']='Le dossier est vide';

# index.php:149
$GLOBALS['__l10n']['About']='À propos';

# index.php:150
$GLOBALS['__l10n']['Made by:']='Crée par :';

# index.php:154
$GLOBALS['__l10n']['Thanks']='Remerciements';

# index.php:159
$GLOBALS['__l10n']['More information on the plugin:']='Plus d\'information sur le plugin';

# index.php:170
$GLOBALS['__l10n']['Support and Update']='Support et Mise à jour';

# index.php:171
$GLOBALS['__l10n']['Please go to:']='Veuillez vous rendre sur :';

# index.php:179
$GLOBALS['__l10n']['I receive an error message when I am in the administration']='J\'ai un message d\'erreur lorsque je suis dans l\'administration';

# index.php:186
$GLOBALS['__l10n']['The permissions of writing are not correct (700 minimum)']='Les permissions d\'écriture ne sont pas corrects (700 minimum)';

# index.php:188
$GLOBALS['__l10n']['I did not file cbtpl and cbfeed in the list']='Je n\'ai pas de dossier cbtpl et cbfeed dans la liste';

# index.php:190
$GLOBALS['__l10n']['check your file "config.php"']='vérifiez votre fichier "config.php"';

# index.php:191
$GLOBALS['__l10n']['The cache is empty']='Le cache est vide';

$GLOBALS['__l10n']['The file is empty']='Le dossier est vide';

$GLOBALS['__l10n']['The rights of writing are not correct (700 required)']='Les droits d\'écriture ne sont pas corrects (700 requis)';

$GLOBALS['__l10n']['Error']='Erreur';

$GLOBALS['__l10n']['erasecache']='effacecache';

$GLOBALS['__l10n']['Contribute']='Contributions';

$GLOBALS['__l10n']['erase cache successfully.']='cache vidé avec succès';

$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

$GLOBALS['__l10n']['To select the file with removed :']='Sélectionner le dossier à supprimé :';

$GLOBALS['__l10n']['erase Cache successfully.']='Cache vidé avec succès';

$GLOBALS['__l10n']['Click on the button to erase the files temporary of dotclear']='Cliquez sur le bouton pour effacer les fichiers temporaires de dotclear';

?>