<?php
// Français translation of ComListe, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:18
# _widgets.php:22
# index.php:92
# index.php:104
$GLOBALS['__l10n']['ComListe']='ComListe';

# _widgets.php:21
# _widgets.php:23
# inc/class.dc.comListe.php:277
# index.php:40
$GLOBALS['__l10n']['List of comments']='Liste des commentaires';

# _widgets.php:23
$GLOBALS['__l10n']['Link title:']='Titre du lien:';

# inc/class.dc.comListe.php:258
$GLOBALS['__l10n']['open post']='ouvrir le billet';

# index.php:60
$GLOBALS['__l10n']['No page title.']='Pas de titre de page.';

# index.php:100
$GLOBALS['__l10n']['Save configuration successful']='Sauvegarde de la configuration réussie';

# index.php:116
$GLOBALS['__l10n']['Plugin activation']='Activation de l\'extension';

# index.php:119
$GLOBALS['__l10n']['Enable comListe']='Activer comListe';

# index.php:121
$GLOBALS['__l10n']['General options']='Options générales';

# index.php:122
$GLOBALS['__l10n']['Title page']='Titre de la page';

# index.php:125
$GLOBALS['__l10n']['Number of comments per page']='Nombre de commentaires par page';

# index.php:128
$GLOBALS['__l10n']['Comments order']='Sens de tri pour les commentaires';

$GLOBALS['__l10n']['Message:']='Message:';

$GLOBALS['__l10n']['Setting have been successfully updated.']='Configuration mise à jour avec succès.';

$GLOBALS['__l10n']['Current page']='Page courante';

?>