<?php
// Français translation of ComListe, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:29
# _widgets.php:33
# index.php:103
# index.php:115
$GLOBALS['__l10n']['ComListe']='ComListe';

# _widgets.php:32
# _widgets.php:34
# class.dc.comListe.php:271
# index.php:51
$GLOBALS['__l10n']['List of comments']='Liste des commentaires';

# _widgets.php:34
$GLOBALS['__l10n']['Link title:']='Titre du lien:';

# index.php:71
$GLOBALS['__l10n']['No page title.']='Pas de titre de page.';

# index.php:111
$GLOBALS['__l10n']['Save configuration successful']='Sauvegarde de la configuration réussie';

# index.php:127
$GLOBALS['__l10n']['Plugin activation']='Activation de l\'extension';

# index.php:130
$GLOBALS['__l10n']['Enable comListe']='Activer comListe';

# index.php:132
$GLOBALS['__l10n']['General options']='Options générales';

# index.php:133
$GLOBALS['__l10n']['Title page']='Titre de la page';

# index.php:136
$GLOBALS['__l10n']['Number of comments per page']='Nombre de commentaires par page';

# index.php:139
$GLOBALS['__l10n']['Comments order']='Sens de tri pour les commentaires';

$GLOBALS['__l10n']['Message:']='Message:';

$GLOBALS['__l10n']['Setting have been successfully updated.']='Configuration mise à jour avec succès.';

$GLOBALS['__l10n']['Current page']='Page courante';

?>