<?php
// French translation of Popularity Contest, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# class.popularityContest.php:30
$GLOBALS['__l10n']['weekly']='chaque semaine';

# class.popularityContest.php:31
$GLOBALS['__l10n']['every 3 days']='tous les 3 jours';

# class.popularityContest.php:32
$GLOBALS['__l10n']['daily']='quotidiennement';

# class.popularityContest.php:67
$GLOBALS['__l10n']['wait %s before sending a report']='attendez %s avant d\'envoyer un rapport';

# class.popularityContest.php:101
$GLOBALS['__l10n']['wait before sending a report']='attendez avant d\'envoyer un rapport';

# class.popularityContest.php:118
$GLOBALS['__l10n']['report succesfully sent']='rapport envoyé avec succés';

# class.popularityContest.php:122
# class.popularityContest.php:128
$GLOBALS['__l10n']['unknown error:']='erreur inconnue:';

# class.popularityContest.php:140
$GLOBALS['__l10n']['Installed plugins:']='Extensions installées:';

# class.popularityContest.php:145
$GLOBALS['__l10n']['Hide']='Cacher';

# class.popularityContest.php:147
$GLOBALS['__l10n']['Icon']='Icône';

# class.popularityContest.php:182
$GLOBALS['__l10n']['year']='année';

# class.popularityContest.php:182
$GLOBALS['__l10n']['years']='années';

# class.popularityContest.php:183
$GLOBALS['__l10n']['month']='mois';

# class.popularityContest.php:183
$GLOBALS['__l10n']['months']='mois';

# class.popularityContest.php:184
$GLOBALS['__l10n']['day']='jour';

# class.popularityContest.php:184
$GLOBALS['__l10n']['days']='jours';

# class.popularityContest.php:185
$GLOBALS['__l10n']['hour']='heure';

# class.popularityContest.php:185
$GLOBALS['__l10n']['hours']='heures';

# class.popularityContest.php:186
$GLOBALS['__l10n']['minute']='minute';

# class.popularityContest.php:186
$GLOBALS['__l10n']['minutes']='minutes';

# class.popularityContest.php:187
$GLOBALS['__l10n']['second']='seconde';

# class.popularityContest.php:187
$GLOBALS['__l10n']['seconds']='secondes';

# class.popularityContest.php:205
$GLOBALS['__l10n']['and']='et';

# index.php:59
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:101
$GLOBALS['__l10n']['Last successful report: %s ago']='Dernier rapport réussi: il y a %s';

# index.php:105
$GLOBALS['__l10n']['Last try: %s ago']='Dernier essai: il y a %s';

# index.php:111
$GLOBALS['__l10n']['This plugin only send the following informations to Dotclear Popularity Contest:']='Cette extension envoie seulement les informations suivantes à Dotclear Popularity Contest:';

# index.php:115
$GLOBALS['__l10n']['the names of installed plugins']='les noms des extensions installées';

# index.php:116
$GLOBALS['__l10n']['the value of md5(DC_ADMIN_URL) (%s) identify the Dotclear installation with an unique and anonym hash']='la valeur de md5(DC_ADMIN_URL) (%s) identifie l\'installation de Dotclear avec un hash unique et anonyme';

# index.php:117
$GLOBALS['__l10n']['the Dotclear version (%s)']='la version de Dotclear (%s)';

# index.php:126
$GLOBALS['__l10n']['In the settings, you can hide some plugins and they will be ignored by Dotclear Popularity Contest.']='Dans les paramètres, vous pouvez cacher des extensions et elles seront ignorées par Dotclear Popularity Contest.';

# index.php:127
$GLOBALS['__l10n']['Click here to see results.']='Cliquez ici pour voir les résultats.';

# index.php:129
$GLOBALS['__l10n']['Send a report to Dotclear Popularity Contest']='Envoyer un rapport à Dotclear Popularity Contest';

# index.php:132
$GLOBALS['__l10n']['Plugins:']='Extensions:';

# index.php:136
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:141
$GLOBALS['__l10n']['Send a report:']='Envoyer un rapport:';

# index.php:146
$GLOBALS['__l10n']['Hide plugins:']='Cacher les extensions:';

# index.php:149
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

?>