<?php
// French translation of Souvenir, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:10
$GLOBALS['__l10n']['Souvenir']='Souvenir';

# _admin.php:12
$GLOBALS['__l10n']['Title:']='Titre:';

# _admin.php:12
# _admin.php:33
$GLOBALS['__l10n']['optional']='facultatif';

# _admin.php:12
$GLOBALS['__l10n']['One year ago']='Un an plus tôt';

# _admin.php:15
$GLOBALS['__l10n']['1 month ago']='1 mois plut tôt';

# _admin.php:18
$GLOBALS['__l10n']['months ago']='mois plut tôt';

# _admin.php:20
$GLOBALS['__l10n']['1 year ago']='1 an plus tôt';

# _admin.php:22
$GLOBALS['__l10n']['Show a link to a post published:']='Afficher un lien vers un billet publié:';

# _admin.php:29
$GLOBALS['__l10n']['Maximum number of days before of after the date in the past:']='Nombre maximum de jours avant ou après la date dans le passé:';

# _admin.php:31
$GLOBALS['__l10n']['Number of characters of the post title to display (empty means no limit):']='Nombre de caractères du titre du billet à afficher (laisser vide pour aucune limite):';

# _admin.php:33
$GLOBALS['__l10n']['Display date after post title (see PHP strftime function):']='Afficher la date après le titre du billet (voir la fonction PHP strftime):';

?>