<?php
// French translation of Clock, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:2
# _admin.php:16
# index.php:9
# index.php:12
$GLOBALS['__l10n']['Clock']='Horloge';

# _admin.php:18
$GLOBALS['__l10n']['Local time in']='Heure de';

# _admin.php:20
$GLOBALS['__l10n']['Timezone:']='Fuseau horaire:';

# _admin.php:22
$GLOBALS['__l10n']['Format (see PHP strftime function) (HMS display dynamically %H:%M:%S):']='Format (voir la fonction strftime de PHP) (HMS affiche dynamiquement %H:%M:%S):';

# index.php:14
$GLOBALS['__l10n']['Select a timezone']='Sélectionner un fuseau horaire';

# index.php:15
$GLOBALS['__l10n']['Copy and paste this timezone in a Clock widget']='Copier et coller ce fuseau horaire dans un widget Horloge';

?>