<?php
// Français translation of Adsense Management, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:24
$GLOBALS['__l10n']['See the Widget Adsense']='Voir le Widget Adsense';

# _admin.php:26
# _admin.php:34
# index.php:100
# index.php:169
$GLOBALS['__l10n']['Google Adsense']='Google Adsense';

# _admin.php:37
# index.php:234
$GLOBALS['__l10n']['Google ad client:(16 digits)']='Google ad client:(16 chiffres)';

# _admin.php:38
$GLOBALS['__l10n']['Round:']='Arrondis';

# _admin.php:39
$GLOBALS['__l10n']['Colors:']='Couleurs';

# _admin.php:40
$GLOBALS['__l10n']['Default']='Defaut';

# _admin.php:41
# index.php:265
$GLOBALS['__l10n']['Styles of the angles:']='Styles des angles';

# _admin.php:42
# index.php:267
$GLOBALS['__l10n']['Right angles']='Angles droit';

# _admin.php:42
# index.php:267
$GLOBALS['__l10n']['Angles slightly rounded']='Angles légèrement arrondis';

# _admin.php:42
# index.php:267
$GLOBALS['__l10n']['Angles very rounded']='Angles très arrondis';

# _admin.php:43
$GLOBALS['__l10n']['Position:']='Position';

# _admin.php:45
$GLOBALS['__l10n']['Format:']='Format :';

# class.adsense.php:31
$GLOBALS['__l10n']['Cache file does not exist or with already be removing']='Le fichier de cache n\'existe pas ou à déjà été supprimer';

# index.php:25
$GLOBALS['__l10n']['google_ad_client is empty']='google_ad_client est vide';

# index.php:35
# index.php:59
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:88
$GLOBALS['__l10n']['Cache has been successfully deleted.']='Cache supprimé avec succès';

# index.php:172
# index.php:233
$GLOBALS['__l10n']['Adsense']='Adsense';

# index.php:173
$GLOBALS['__l10n']['Display Widget Adsense']='Afficher widget adsense';

# index.php:174
$GLOBALS['__l10n']['To display Adsense on the page, you have to active the <em>Adsense</em> widget by dragging it into the navigation sidebar from the']='Pour afficher Adsense sur la page, vous devez activer le widget <em>Adsense </em> en le glissant dans le bandeau de navigation à partir de';

# index.php:174
$GLOBALS['__l10n']['the widget page']='la page des widgets';

# index.php:174
$GLOBALS['__l10n']['and click on the &quot;update sidebars&quot; button.']='et cliquer sur le bouton "mettre à jour les bandeaux".';

# index.php:174
$GLOBALS['__l10n']['To set and personalize the displaying, use the widget.']='Toute la configuration et la personnalisation de l\'affichage se fait au niveau du widget.';

# index.php:175
$GLOBALS['__l10n']['Display Adsense']='Afficher Adsense';

# index.php:176
$GLOBALS['__l10n']['Copy/Paste the following code in _post.html']='Copier/coller le code suivant dans _post.html';

# index.php:176
$GLOBALS['__l10n']['or another file']='ou dans un autre fichier';

# index.php:176
$GLOBALS['__l10n']['with the theme editor']='avec l\'éditeur de thème';

# index.php:177
$GLOBALS['__l10n']['Example']='Exemple';

# index.php:182
$GLOBALS['__l10n']['Line 65, right before:']='Ligne 65,  juste avant:';

# index.php:186
$GLOBALS['__l10n']['Documentation of Google AdSense']='Documentation de Google Adsense';

# index.php:187
$GLOBALS['__l10n']['To find your unique AdSense publisher ID number, log into your AdSense account at <a class="popupwindow" href="http://www.google.com/adsense">http://www.google.com/adsense</a>.']='Pour trouver votre identifiant d\'éditeur AdSense personnel, connectez-vous à votre compte à l\'adresse <a class="popupwindow" href="http://www.google.com/adsense">http://www.google.com/adsense</a>.';

# index.php:187
$GLOBALS['__l10n']['On the My Account tab, scroll down to the Property info section.']='Dans l\'onglet Mon compte, faites défiler l\'écran jusqu\'à la section Informations relatives au site.';

# index.php:187
$GLOBALS['__l10n']['Your publisher ID for each AdSense product and feature will be located in this section.']='Vous y trouverez votre identifiant d\'éditeur pour tous les produits et fonctions AdSense.';

# index.php:189
$GLOBALS['__l10n']['Summary:']='Résumé:';

# index.php:190
$GLOBALS['__l10n']['This code will easily find it to you on your account google adsense while following the indications above.']='Ce code vous le trouverez facilement sur votre compte google adsense en suivant les indications ci-dessus.';

# index.php:190
$GLOBALS['__l10n']['You should copy only the 16 figures without the "pub".']='Vous ne devez copier que les 16 chiffres sans le "pub-".';

# index.php:195
$GLOBALS['__l10n']['Template']='thème';

# index.php:200
$GLOBALS['__l10n']['Edit a file']='Editer le fichier';

# index.php:201
$GLOBALS['__l10n']['HTML file:']='fichier HTML';

# index.php:202
$GLOBALS['__l10n']['your template uses the files by default']='Vous utilisez le thème par défaut';

# index.php:220
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:222
# index.php:225
$GLOBALS['__l10n']['Delete the cache']='Effacer le cache';

# index.php:228
$GLOBALS['__l10n']['Tips']='Conseils';

# index.php:229
$GLOBALS['__l10n']['Using the plugin']='Utiliser le plugin';

# index.php:242
$GLOBALS['__l10n']['Width:']='Taille';

# index.php:243
$GLOBALS['__l10n']['Height:']='Hauteur';

# index.php:260
$GLOBALS['__l10n']['Border color:']='Couleur bordure:';

# index.php:262
$GLOBALS['__l10n']['Color link:']='Couleur des liens:';

# index.php:263
$GLOBALS['__l10n']['Color text:']='Couleur du texte:';

# index.php:264
$GLOBALS['__l10n']['Color url:']='Couleur de l\'url:';

# index.php:272
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:324
# index.php:325
$GLOBALS['__l10n']['About']='À propos';

# index.php:327
$GLOBALS['__l10n']['Adsense Management']='Adsense Management';

# index.php:332
$GLOBALS['__l10n']['More information on Adsense Management:']='Plus d\'information sur Adsense MAnagement';

# index.php:339
$GLOBALS['__l10n']['Support and Update']='Support et Mise à jour';

# index.php:340
$GLOBALS['__l10n']['Please go to:']='Veuillez vous rendre sur :';

$GLOBALS['__l10n']['erase Cache successfully.']='Cache vidé avec succès';

$GLOBALS['__l10n']['Copy/Paste the following code or wish it to you in your topic']='Copier/coller le code suivant ou vous le désirez dans votre thème';

$GLOBALS['__l10n']['Example in _post.html']='Exemple dans _post.html';

$GLOBALS['__l10n']['Blue']='Bleu';

$GLOBALS['__l10n']['Black']='Noir';

$GLOBALS['__l10n']['Grey']='Gris';

$GLOBALS['__l10n']['Red']='Rouge';

$GLOBALS['__l10n']['Yellow']='Jaune';

$GLOBALS['__l10n']['To find your unique AdSense publisher ID number, log into your AdSense account at http://www.google.com/adsense.']='Pour trouver votre identifiant d\'éditeur AdSense personnel, connectez-vous à votre compte à l\'adresse http://www.google.com/adsense.';

?>