<?php
// French translation of Annuaire, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:33
# index.php:7
# index.php:105
$GLOBALS['__l10n']['Directory']='Annuaire';

# _admin.php:50
$GLOBALS['__l10n']['none']='aucune';

# _admin.php:61
$GLOBALS['__l10n']['Blog category']='Catégorie du blog';

# _admin.php:63
$GLOBALS['__l10n']['Category of this blog:']='Catégorie de ce blog';

# _admin.php:87
# _admin.php:89
$GLOBALS['__l10n']['Directory (categories list)']='Annuaire (liste des catégories)';

# class.annuaire.admin.php:95
# class.annuaire.widgets.php:38
$GLOBALS['__l10n']['No categories']='Pas de catégories';

# class.annuaire.admin.php:148
# class.annuaire.admin.php:183
$GLOBALS['__l10n']['Back to categories list']='Retour à la liste des catégories';

# index.php:27
$GLOBALS['__l10n']['No category deleted']='Pas de catégorie supprimée';

# index.php:29
$GLOBALS['__l10n']['Category(s) successfully deleted']='Catégorie(s) supprimée(s) avec succès';

# index.php:68
$GLOBALS['__l10n']['Category updated']='Catégorie mise à jour';

# index.php:70
$GLOBALS['__l10n']['Category not updated']='Catégorie non mise à jour';

# index.php:86
$GLOBALS['__l10n']['Category created']='Catégorie crée';

# index.php:88
$GLOBALS['__l10n']['Category not created']='Catégorie non crée';

# index.php:121
$GLOBALS['__l10n']['Add category']='Ajouter une catégorie';

$GLOBALS['__l10n']['Blogs categories']='Catégories des blogs';

?>