<?php
// French translation of Informations, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:24
# index.php:35
# index.php:43
$GLOBALS['__l10n']['Informations']='Informations';

# class.info.php:94
$GLOBALS['__l10n']['Name']='Nom';

# class.info.php:95
$GLOBALS['__l10n']['Records']='Enregistrements';

# class.info.php:96
$GLOBALS['__l10n']['Size']='Taille';

# class.info.php:127
$GLOBALS['__l10n']['Total :']='Total :';

# class.info.php:151
$GLOBALS['__l10n']['Directory']='Répertoire';

# class.info.php:152
$GLOBALS['__l10n']['Is a directory']='Est un répertoire';

# class.info.php:153
$GLOBALS['__l10n']['Is executable']='Est exécutable';

# class.info.php:154
$GLOBALS['__l10n']['Is writable']='Peut être écrit';

# class.info.php:155
$GLOBALS['__l10n']['Is readable']='Peut être lu';

# class.info.php:156
$GLOBALS['__l10n']['Path']='Chemin';

# class.info.php:157
$GLOBALS['__l10n']['Owner']='Propriétaire';

# class.info.php:158
$GLOBALS['__l10n']['Permissions']='Permissions';

# class.info.php:168
# class.info.php:175
$GLOBALS['__l10n']['plugins']='extensions';

# class.info.php:180
$GLOBALS['__l10n']['cache']='cache';

# class.info.php:181
$GLOBALS['__l10n']['public']='public';

# class.info.php:182
$GLOBALS['__l10n']['themes']='thèmes';

# class.info.php:183
$GLOBALS['__l10n']['theme']='thème';

# index.php:44
$GLOBALS['__l10n']['General informations']='Informations générales';

# index.php:45
$GLOBALS['__l10n']['You are using Dotclear %s']='Vous utilisez Dotclear %s';

# index.php:53
$GLOBALS['__l10n']['URL scan method is %1$s and the last character of URL is %2$s']='La méthode de lecture de l\'URL est %1$s et le dernier caractère de l\'URL est %2$s';

# index.php:62
# index.php:69
$GLOBALS['__l10n']['URL scan method is %1$s and the last character of URL isn&#39;t %2$s']='La méthode de lecture de l\'URL est %1$s et le dernier caractère de l\'URL n\'est pas %2$s';

# index.php:76
$GLOBALS['__l10n']['URL scan method is not %1$s or %2$s']='La méthode de lecture de l\'URL n\'est pas  %1$s ou %2$s';

# index.php:79
$GLOBALS['__l10n']['The blog ID is %s']='L\'identifiant du blog est %s';

# index.php:81
$GLOBALS['__l10n']['Database']='Base de données';

# index.php:82
$GLOBALS['__l10n']['Dotclear tables in your database are']='Les tables de Dotclear dans votre base de données sont';

# index.php:85
$GLOBALS['__l10n']['Directory informations']='Informations sur les répertoires';

# index.php:87
$GLOBALS['__l10n']['Legend :']='Légende :';

# index.php:88
$GLOBALS['__l10n']['yes']='oui';

# index.php:88
$GLOBALS['__l10n']['no']='non';

# index.php:89
$GLOBALS['__l10n']['Public directory is optional.']='Le répertoire public est facultatif.';

# index.php:91
$GLOBALS['__l10n']['Server informations']='Informations sur le serveur';

# index.php:92
$GLOBALS['__l10n']['Dotclear is installed in the directory %s']='Dotclear est installé dans le répertoire %s';

# index.php:93
$GLOBALS['__l10n']['The PHP version is %s']='La version de PHP est %s';

# index.php:94
$GLOBALS['__l10n']['The database driver is %1$s and its version %2$s']='Le pilote de la base de données est %1$s et sa version est %2$s';

# index.php:98
$GLOBALS['__l10n']['The web server is %2$s']='Le serveur Web est %s';

# index.php:107
$GLOBALS['__l10n']['The user is %s']='L\'utilisateur est %s';

# index.php:115
$GLOBALS['__l10n']['The error_reporting level is %2$s']='Le niveau de error_reporting est %s';

# index.php:116
$GLOBALS['__l10n']['The displayed errors are %s']='Les erreurs affichées sont %s';

?>