<?php
// Français translation of Newsletter, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _install.php:40
# index.php:46
$GLOBALS['__l10n']['Unable to install Newsletter.']='Impossible d\'installer Newsletter';

# _public.php:75
$GLOBALS['__l10n']['Test display template.']='Test d\'affichage du template.';

# _public.php:79
$GLOBALS['__l10n']['About Newsletter ...']='A propos de Newsletter ...';

# _public.php:80
$GLOBALS['__l10n']['About']='A propos';

# _public.php:82
$GLOBALS['__l10n']['Authors']='Auteurs';

# _public.php:88
# _public.php:104
# _public.php:120
# _public.php:136
# _public.php:152
$GLOBALS['__l10n']['Missing informations. ']='Informations manquantes.';

# _public.php:92
$GLOBALS['__l10n']['Your subscription code is invalid.']='Votre code d\'inscription est invalide.';

# _public.php:94
$GLOBALS['__l10n']['Account already confirmed.']='Abonnement déja confirmé.';

# _public.php:97
$GLOBALS['__l10n']['Your subscription is confirmed.']='Votre inscription est confirmée.';

# _public.php:97
# _public.php:113
# _public.php:129
# _public.php:145
# _public.php:159
$GLOBALS['__l10n']['You will soon receive an email.']='Vous allez bientôt recevoir un email.';

# _public.php:108
# _public.php:124
# _public.php:140
# _public.php:156
$GLOBALS['__l10n']['Unable to find you account informations.']='Impossible de trouver les informations de votre compte.';

# _public.php:110
$GLOBALS['__l10n']['Account already enabled.']='Abonnement déja activé.';

# _public.php:113
# inc/class.newsletter.core.php:1274
$GLOBALS['__l10n']['Your account is enabled.']='Votre abonnement est activé.';

# _public.php:126
$GLOBALS['__l10n']['Account already disabled.']='Abonnement déja désactivé.';

# _public.php:129
# inc/class.newsletter.core.php:1265
$GLOBALS['__l10n']['Your account is disabled.']='Votre abonnement est désactivé.';

# _public.php:142
$GLOBALS['__l10n']['Account already suspended.']='Abonnement déja suspendu.';

# _public.php:145
# inc/class.newsletter.core.php:1256
$GLOBALS['__l10n']['Your account is suspended.']='Votre abonnement est suspendu.';

# _public.php:159
$GLOBALS['__l10n']['Your sending format is']='Votre format d\'envoi est';

# _public.php:182
$GLOBALS['__l10n']['Bad captcha code.']='Mauvais code de vérification.';

# _public.php:205
$GLOBALS['__l10n']['Error in formular.']='Erreur dans le formulaire.';

# _public.php:223
# _public.php:440
# _widgets.php:25
# _widgets.php:27
# inc/class.newsletter.admin.php:999
# inc/class.newsletter.plugin.php:776
# index.php:24
$GLOBALS['__l10n']['Newsletter']='Lettre d\'informations';

# _public.php:276
# _public.php:498
# _public.php:499
# inc/class.newsletter.admin.php:573
$GLOBALS['__l10n']['Captcha']='Code visuel';

# _public.php:302
# _public.php:387
# _public.php:472
# _public.php:477
# inc/class.newsletter.admin.php:992
$GLOBALS['__l10n']['Suspend']='Suspendre';

# _public.php:306
# _public.php:390
# _public.php:478
$GLOBALS['__l10n']['Resume']='Résumé';

# _public.php:325
# _public.php:368
# _public.php:461
# inc/class.newsletter.admin.php:341
# inc/class.newsletter.admin.php:1011
# inc/class.newsletter.admin.php:1063
$GLOBALS['__l10n']['text']='texte';

# _public.php:332
# _public.php:383
# _public.php:468
$GLOBALS['__l10n']['Change format']='Changer le format';

# _public.php:365
# _public.php:458
$GLOBALS['__l10n']['Format']='Format';

# _public.php:367
# _public.php:460
# inc/class.newsletter.admin.php:342
# inc/class.newsletter.admin.php:1010
# inc/class.newsletter.admin.php:1064
$GLOBALS['__l10n']['html']='html';

# _public.php:392
# _public.php:480
# _public.php:485
$GLOBALS['__l10n']['Unsubscribe']='Se désabonner';

# _public.php:443
# _widgets.php:32
$GLOBALS['__l10n']['Subscription link']='S\'abonner';

# _public.php:455
$GLOBALS['__l10n']['Email']='Courriel';

# _public.php:463
# _public.php:483
$GLOBALS['__l10n']['Actions']='Actions';

# _widgets.php:28
$GLOBALS['__l10n']['Show title']='Afficher le titre';

# _widgets.php:30
$GLOBALS['__l10n']['In widget']='Dans un widget';

# _widgets.php:31
$GLOBALS['__l10n']['In sublink']='Dans un lien';

# _widgets.php:32
$GLOBALS['__l10n']['Title subscription link:']='Titre du lien de souscription:';

# inc/class.newsletter.admin.php:205
$GLOBALS['__l10n']['No template to adapt.']='Pas de template à adapter.';

# inc/class.newsletter.admin.php:227
$GLOBALS['__l10n']['is not in your theme folder.']='n\'est pas dans votre répertoire de thème.';

# inc/class.newsletter.admin.php:231
$GLOBALS['__l10n']['is not in the plugin folder.']='n\'est pas dans le répertoire de plugin.';

# inc/class.newsletter.admin.php:235
$GLOBALS['__l10n']['is not readable.']='n\'est pas lisible';

# inc/class.newsletter.admin.php:302
# inc/class.newsletter.admin.php:308
$GLOBALS['__l10n']['Template created.']='Template créé.';

# inc/class.newsletter.admin.php:304
$GLOBALS['__l10n']['Unable to write file.']='Impossible d\'écrire le fichier.';

# inc/class.newsletter.admin.php:406
# index.php:956
$GLOBALS['__l10n']['Settings']='Paramètres';

# inc/class.newsletter.admin.php:418
$GLOBALS['__l10n']['Editor name']='Nom de l\'éditeur';

# inc/class.newsletter.admin.php:422
$GLOBALS['__l10n']['Editor email']='Email de l\'éditeur';

# inc/class.newsletter.admin.php:428
$GLOBALS['__l10n']['Message presentation']='Message de présentation';

# inc/class.newsletter.admin.php:432
$GLOBALS['__l10n']['Presentation message for posts']='Message de présentation pour les billets';

# inc/class.newsletter.admin.php:436
$GLOBALS['__l10n']['Subject of the Newsletter']='Sujet de la Newsletter';

# inc/class.newsletter.admin.php:442
$GLOBALS['__l10n']['Subject of the mail Confirm']='Sujet du mail de confirmation';

# inc/class.newsletter.admin.php:446
$GLOBALS['__l10n']['Introductory confirm message']='Introduction au lien de confirmation';

# inc/class.newsletter.admin.php:450
$GLOBALS['__l10n']['Confirm message']='Message de confirmation';

# inc/class.newsletter.admin.php:454
$GLOBALS['__l10n']['Title confirmation link']='Titre du lien de confirmation';

# inc/class.newsletter.admin.php:458
$GLOBALS['__l10n']['Concluding confirm message']='Conclusion du message de confirmation';

# inc/class.newsletter.admin.php:465
$GLOBALS['__l10n']['Subject of the mail Disable']='Sujet du mail de désactivation';

# inc/class.newsletter.admin.php:469
$GLOBALS['__l10n']['Introductory disable message']='Introduction au lien de désactivation';

# inc/class.newsletter.admin.php:473
$GLOBALS['__l10n']['Disable message']='Message de désactivation';

# inc/class.newsletter.admin.php:477
$GLOBALS['__l10n']['Txt disabled msg']='Texte du message de désactivation';

# inc/class.newsletter.admin.php:481
$GLOBALS['__l10n']['Title disable link']='Titre du lien de désactivation';

# inc/class.newsletter.admin.php:485
$GLOBALS['__l10n']['Concluding disable msg']='Conclusion du message de désactivation';

# inc/class.newsletter.admin.php:491
$GLOBALS['__l10n']['Subject of the mail Enable']='Sujet du mail d\'activation';

# inc/class.newsletter.admin.php:495
$GLOBALS['__l10n']['Introductory enable message']='Introduction au lien d\'activation';

# inc/class.newsletter.admin.php:499
$GLOBALS['__l10n']['Enable message']='Message d\'activation';

# inc/class.newsletter.admin.php:503
$GLOBALS['__l10n']['Texte enabled message']='Texte du message d\'activation';

# inc/class.newsletter.admin.php:507
$GLOBALS['__l10n']['Title enable link']='Titre du lien d\'activation';

# inc/class.newsletter.admin.php:511
$GLOBALS['__l10n']['Concluging enable message']='Conclusion du message d\'activation';

# inc/class.newsletter.admin.php:517
$GLOBALS['__l10n']['Subject of the mail Suspend']='Sujet du mail de suspension';

# inc/class.newsletter.admin.php:521
$GLOBALS['__l10n']['Introductory suspend message']='Introduction au lien de suspension';

# inc/class.newsletter.admin.php:525
$GLOBALS['__l10n']['Suspend message']='Message de suspension';

# inc/class.newsletter.admin.php:529
$GLOBALS['__l10n']['Txt suspended msg']='Texte du message de suspension';

# inc/class.newsletter.admin.php:533
$GLOBALS['__l10n']['Title suspend link']='Titre du lien de suspension';

# inc/class.newsletter.admin.php:537
$GLOBALS['__l10n']['Concluding suspend message']='Conclusion du message de suspension';

# inc/class.newsletter.admin.php:543
$GLOBALS['__l10n']['Subject of the mail Resume']='Sujet du mail de résumé';

# inc/class.newsletter.admin.php:547
$GLOBALS['__l10n']['Subject of the mail Changing mode']='Sujet du mail de changement de mode';

# inc/class.newsletter.admin.php:551
$GLOBALS['__l10n']['Title page of the subscribe form']='Titre de la page du formulaire d\'abonnement';

# inc/class.newsletter.admin.php:558
$GLOBALS['__l10n']['Introductory message']='Message d\'introduction';

# inc/class.newsletter.admin.php:561
$GLOBALS['__l10n']['Concluding message']='Message de conclusion';

# inc/class.newsletter.admin.php:564
$GLOBALS['__l10n']['Message presentation form']='Message de présentation du formulaire';

# inc/class.newsletter.admin.php:570
$GLOBALS['__l10n']['Advanced Settings']='Paramètres avancés';

# inc/class.newsletter.admin.php:574
$GLOBALS['__l10n']['Default format for sending']='Format par défaut pour l\'envoi';

# inc/class.newsletter.admin.php:579
$GLOBALS['__l10n']['Use default format for sending']='Utiliser le format par défaut pour l\'envoi';

# inc/class.newsletter.admin.php:583
$GLOBALS['__l10n']['Automatic send']='Envoi automatique';

# inc/class.newsletter.admin.php:587
$GLOBALS['__l10n']['Notification sending']='Accusé de réception';

# inc/class.newsletter.admin.php:589
$GLOBALS['__l10n']['Minimum posts']='Nombre minimum de billets';

# inc/class.newsletter.admin.php:592
$GLOBALS['__l10n']['Maximum posts']='Nombre maximal de billets';

# inc/class.newsletter.admin.php:597
$GLOBALS['__l10n']['View contents posts']='Affiche le contenu des billets';

# inc/class.newsletter.admin.php:599
$GLOBALS['__l10n']['Size contents posts']='Taille maximale du contenu des billets';

# inc/class.newsletter.admin.php:607
$GLOBALS['__l10n']['Use suspend option']='Utiliser l\'option Suspendre';

# inc/class.newsletter.admin.php:615
$GLOBALS['__l10n']['Defaults']='Défauts';

# inc/class.newsletter.admin.php:625
# inc/class.newsletter.admin.php:757
# inc/class.newsletter.admin.php:912
# inc/class.newsletter.admin.php:1037
# inc/class.newsletter.admin.php:1153
$GLOBALS['__l10n']['Activate the plugin in the Maintenance tab to view all options']='Activer le plugin dans l\'onglet maintenance pour afficher toutes les options';

# inc/class.newsletter.admin.php:665
# inc/class.newsletter.admin.php:747
$GLOBALS['__l10n']['Planning newsletter']='Planification de la newsletter';

# inc/class.newsletter.admin.php:668
$GLOBALS['__l10n']['Interval time in seconds between 2 runs']='Intervalle de temps en secondes entre 2 exécutions';

# inc/class.newsletter.admin.php:672
$GLOBALS['__l10n']['samples']='exemples';

# inc/class.newsletter.admin.php:672
$GLOBALS['__l10n']['day']='jour';

# inc/class.newsletter.admin.php:672
$GLOBALS['__l10n']['week']='semaine';

# inc/class.newsletter.admin.php:675
$GLOBALS['__l10n']['Date for the first run']='Date de la première exécution';

# inc/class.newsletter.admin.php:681
$GLOBALS['__l10n']['Unschedule']='Déplanifier';

# inc/class.newsletter.admin.php:681
$GLOBALS['__l10n']['Schedule']='Planifier';

# inc/class.newsletter.admin.php:697
$GLOBALS['__l10n']['Scheduled task']='Tâche planifiée';

# inc/class.newsletter.admin.php:707
$GLOBALS['__l10n']['State']='Etat';

# inc/class.newsletter.admin.php:711
$GLOBALS['__l10n']['Interval']='Intervalle';

# inc/class.newsletter.admin.php:715
$GLOBALS['__l10n']['Last run']='Dernière exécution';

# inc/class.newsletter.admin.php:719
$GLOBALS['__l10n']['Next run']='Prochaine exécution';

# inc/class.newsletter.admin.php:723
$GLOBALS['__l10n']['Remaining Time']='Temps restant';

# inc/class.newsletter.admin.php:733
# inc/class.newsletter.admin.php:994
$GLOBALS['__l10n']['Disable']='Désactiver';

# inc/class.newsletter.admin.php:733
# inc/class.newsletter.admin.php:995
$GLOBALS['__l10n']['Enable']='Activer';

# inc/class.newsletter.admin.php:748
$GLOBALS['__l10n']['Install the plugin dcCron for using planning']='Installez l\'extension dcCron pour utiliser la planification';

# inc/class.newsletter.admin.php:810
$GLOBALS['__l10n']['Plugin state']='Etat de l\'extension';

# inc/class.newsletter.admin.php:813
$GLOBALS['__l10n']['Activate plugin']='Activer l\'extension';

# inc/class.newsletter.admin.php:831
$GLOBALS['__l10n']['Import/Export subscribers list']='Import/Export de la liste des abonnés';

# inc/class.newsletter.admin.php:834
$GLOBALS['__l10n']['This blog only']='Ce blog seulement';

# inc/class.newsletter.admin.php:838
$GLOBALS['__l10n']['All datas']='Toutes les données';

# inc/class.newsletter.admin.php:855
$GLOBALS['__l10n']['Adapt the template for the theme']='Adapter le template pour le thème';

# inc/class.newsletter.admin.php:856
$GLOBALS['__l10n']['Theme name']='Nom du thème';

# inc/class.newsletter.admin.php:860
$GLOBALS['__l10n']['Adapt']='Adapter';

# inc/class.newsletter.admin.php:866
$GLOBALS['__l10n']['Clic here to test the template.']='Cliquez ici pour tester le template.';

# inc/class.newsletter.admin.php:878
$GLOBALS['__l10n']['Check for plugin update']='Vérifier les mises à jour';

# inc/class.newsletter.admin.php:885
$GLOBALS['__l10n']['Check']='Vérifier';

# inc/class.newsletter.admin.php:895
$GLOBALS['__l10n']['Erasing all informations about newsletter in database']='Suppression de toutes les informations concernant newsletter dans votre base de données';

# inc/class.newsletter.admin.php:896
$GLOBALS['__l10n']['Be careful, please backup your database before erasing']='Attention, vous êtes priés de sauvegarder votre base de données avant de lancer la suppression';

# inc/class.newsletter.admin.php:899
$GLOBALS['__l10n']['Erasing']='Suppression';

# inc/class.newsletter.admin.php:937
$GLOBALS['__l10n']['No subscriber for this blog.']='Pas d\'abonnés pour ce blog.';

# inc/class.newsletter.admin.php:952
$GLOBALS['__l10n']['Subscriber']='Abonné';

# inc/class.newsletter.admin.php:953
$GLOBALS['__l10n']['Subscribed']='Inscription';

# inc/class.newsletter.admin.php:955
# inc/class.newsletter.admin.php:996
$GLOBALS['__l10n']['Last sent']='Dernier envoi';

# inc/class.newsletter.admin.php:956
# inc/class.newsletter.admin.php:1102
$GLOBALS['__l10n']['Mode send']='Mode d\'envoi';

# inc/class.newsletter.admin.php:957
# index.php:953
$GLOBALS['__l10n']['Edit']='Modifier';

# inc/class.newsletter.admin.php:965
# inc/class.newsletter.admin.php:965
$GLOBALS['__l10n']['Edit subscriber']='Modifier l\'abonné';

# inc/class.newsletter.admin.php:970
# inc/class.newsletter.admin.php:975
# inc/class.newsletter.admin.php:1090
# inc/class.newsletter.admin.php:1095
# inc/class.newsletter.cron.php:142
$GLOBALS['__l10n']['Never']='Jamais';

# inc/class.newsletter.admin.php:1000
$GLOBALS['__l10n']['Confirmation']='Confirmation';

# inc/class.newsletter.admin.php:1002
$GLOBALS['__l10n']['Suspension']='Suspension';

# inc/class.newsletter.admin.php:1004
$GLOBALS['__l10n']['Deactivation']='Désactivation';

# inc/class.newsletter.admin.php:1005
$GLOBALS['__l10n']['Activation']='Activation';

# inc/class.newsletter.admin.php:1006
$GLOBALS['__l10n']['Changing format']='Changer de format';

# inc/class.newsletter.admin.php:1017
$GLOBALS['__l10n']['refresh']='actualiser';

# inc/class.newsletter.admin.php:1018
$GLOBALS['__l10n']['check all']='sélectionner tout';

# inc/class.newsletter.admin.php:1019
$GLOBALS['__l10n']['uncheck all']='désélectionner tout';

# inc/class.newsletter.admin.php:1020
$GLOBALS['__l10n']['toggle check all']='inverser la sélection';

# inc/class.newsletter.admin.php:1024
$GLOBALS['__l10n']['Set state']='Modifier l\'état';

# inc/class.newsletter.admin.php:1025
$GLOBALS['__l10n']['Set']='Modifier';

# inc/class.newsletter.admin.php:1026
$GLOBALS['__l10n']['Mail to send']='Courrier à envoyer';

# inc/class.newsletter.admin.php:1029
$GLOBALS['__l10n']['Set format']='Modifier le format';

# inc/class.newsletter.admin.php:1030
$GLOBALS['__l10n']['Change']='Changer';

# inc/class.newsletter.admin.php:1082
$GLOBALS['__l10n']['Edit a subscriber']='Modifier un abonné';

# inc/class.newsletter.admin.php:1084
$GLOBALS['__l10n']['Update']='Mettre à jour';

# inc/class.newsletter.admin.php:1098
$GLOBALS['__l10n']['Subscribed:']='Inscrit:';

# inc/class.newsletter.admin.php:1100
$GLOBALS['__l10n']['Last sent:']='Dernier envoi:';

# inc/class.newsletter.admin.php:1104
$GLOBALS['__l10n']['Registration code:']='Code d\'inscription:';

# inc/class.newsletter.admin.php:1108
$GLOBALS['__l10n']['enabled']='actif';

# inc/class.newsletter.admin.php:1109
$GLOBALS['__l10n']['suspended']='suspendu';

# inc/class.newsletter.admin.php:1110
$GLOBALS['__l10n']['disabled']='désactivé';

# inc/class.newsletter.admin.php:1120
$GLOBALS['__l10n']['Add a subscriber']='Ajouter un abonné';

# inc/class.newsletter.admin.php:1128
$GLOBALS['__l10n']['Not allowed.']='Interdit.';

# inc/class.newsletter.core.php:819
$GLOBALS['__l10n']['Thank you for your subscription.']='Merci pour votre inscription !';

# inc/class.newsletter.core.php:822
$GLOBALS['__l10n']['Your sending format has been updated.']='Votre format d\'envoi a été mis à jour.';

# inc/class.newsletter.core.php:823
$GLOBALS['__l10n'][', by']=', par';

# inc/class.newsletter.core.php:930
$GLOBALS['__l10n']['Successful mail sent for']='Courriel envoyé avec succès pour';

# inc/class.newsletter.core.php:933
$GLOBALS['__l10n']['Mail sent error for']='Echec de l\'envoi du courriel pour';

# inc/class.newsletter.core.php:936
$GLOBALS['__l10n']['Nothing to send for']='Rien à envoyer pour';

# inc/class.newsletter.core.php:981
# inc/class.newsletter.core.php:1003
# inc/class.newsletter.core.php:1053
# inc/class.newsletter.core.php:1100
# inc/class.newsletter.core.php:1152
# inc/class.newsletter.core.php:1199
# inc/class.newsletter.core.php:1301
# inc/class.newsletter.core.php:1348
$GLOBALS['__l10n']['Links:']='Liens:';

# inc/class.newsletter.core.php:1225
# inc/class.newsletter.plugin.php:690
$GLOBALS['__l10n']['Newsletter account resume for']='Information sur l\'abonnement à la lettre d\'information pour';

# inc/class.newsletter.core.php:1225
# inc/class.newsletter.core.php:1327
# inc/class.newsletter.plugin.php:866
# inc/class.newsletter.plugin.php:956
$GLOBALS['__l10n']['Have a nice day !']='Passez une bonne journée !';

# inc/class.newsletter.core.php:1281
$GLOBALS['__l10n']['Your account is pending confirmation.']='Votre abonnement est en attente de confirmation.';

# inc/class.newsletter.core.php:1294
$GLOBALS['__l10n']['Your sending mode is']='Votre format est';

# inc/class.newsletter.core.php:1327
# inc/class.newsletter.plugin.php:710
$GLOBALS['__l10n']['Newsletter account change format for']='Changement du format sur l\'abonnement à la lettre d\'information pour';

# inc/class.newsletter.core.php:1430
# inc/class.newsletter.core.php:1455
# inc/class.newsletter.core.php:1481
# inc/class.newsletter.core.php:1506
# inc/class.newsletter.core.php:1531
$GLOBALS['__l10n']['Bad email !']='Mauvais email ou format incorrect !';

# inc/class.newsletter.core.php:1433
$GLOBALS['__l10n']['Email already exist !']='Email déja existant !';

# inc/class.newsletter.core.php:1435
$GLOBALS['__l10n']['Error creating account !']='Erreur lors de la création du compte !';

# inc/class.newsletter.plugin.php:282
$GLOBALS['__l10n']['Thanks you for reading.']='Merci de nous lire.';

# inc/class.newsletter.plugin.php:330
$GLOBALS['__l10n']['This is the newsletter for']='Voici la lettre d\'information pour';

# inc/class.newsletter.plugin.php:354
$GLOBALS['__l10n']['Here are the last post:']='Voici les derniers billets:';

# inc/class.newsletter.plugin.php:372
$GLOBALS['__l10n']['To confirm you subscription']='Pour confirmer votre inscription';

# inc/class.newsletter.plugin.php:390
# inc/class.newsletter.plugin.php:426
# inc/class.newsletter.plugin.php:462
# inc/class.newsletter.plugin.php:498
$GLOBALS['__l10n']['Click here']='Cliquez ici';

# inc/class.newsletter.plugin.php:408
$GLOBALS['__l10n']['To cancel your account']='Pour supprimer votre abonnement';

# inc/class.newsletter.plugin.php:444
$GLOBALS['__l10n']['To enable your account']='Pour activer votre abonnement';

# inc/class.newsletter.plugin.php:480
$GLOBALS['__l10n']['To suspend your account']='Pour suspendre votre abonnement';

# inc/class.newsletter.plugin.php:590
$GLOBALS['__l10n']['Newsletter for']='Lettre d\'information pour';

# inc/class.newsletter.plugin.php:610
# inc/class.newsletter.plugin.php:794
$GLOBALS['__l10n']['Newsletter subscription confirmation for']='Confirmation d\'inscription pour';

# inc/class.newsletter.plugin.php:630
# inc/class.newsletter.plugin.php:830
# inc/class.newsletter.plugin.php:848
$GLOBALS['__l10n']['Newsletter account suspend for']='Suspension d\'abonnement à la lettre d\'information pour';

# inc/class.newsletter.plugin.php:650
# inc/class.newsletter.plugin.php:884
$GLOBALS['__l10n']['Newsletter account activation for']='Activation d\'abonnement à la lettre d\'information pour';

# inc/class.newsletter.plugin.php:670
# inc/class.newsletter.plugin.php:938
$GLOBALS['__l10n']['Newsletter account removal for']='Suppression d\'abonnement à la lettre d\'information pour';

# inc/class.newsletter.plugin.php:812
$GLOBALS['__l10n']['Thanks you for subscribing.']='Merci pour votre inscription.';

# inc/class.newsletter.plugin.php:902
$GLOBALS['__l10n']['Thank you for subscribing.']='Merci pour votre inscription.';

# inc/class.newsletter.plugin.php:920
$GLOBALS['__l10n']['Your account has been validated.']='Votre compte a été validé.';

# inc/class.newsletter.plugin.php:974
$GLOBALS['__l10n']['Your account has been canceled.']='Votre compte a été supprimé.';

# inc/class.newsletter.plugin.php:1679
$GLOBALS['__l10n']['No new version available.']='Pas de nouvelle version.';

# inc/class.newsletter.plugin.php:1681
$GLOBALS['__l10n']['New version available:']='Nouvelle version disponible:';

# inc/class.newsletter.plugin.php:1687
$GLOBALS['__l10n']['Read the post.']='Lire le billet.';

# inc/class.newsletter.plugin.php:1687
$GLOBALS['__l10n']['post']='billet';

# inc/class.newsletter.plugin.php:1689
$GLOBALS['__l10n']['Installer.']='Installeur.';

# inc/class.newsletter.plugin.php:1689
$GLOBALS['__l10n']['pkg.gz']='pkg.gz';

# inc/class.newsletter.plugin.php:1691
$GLOBALS['__l10n']['Archive.']='Archive.';

# inc/class.newsletter.plugin.php:1691
$GLOBALS['__l10n']['tar.gz']='tar.gz';

# index.php:70
# index.php:365
# index.php:378
$GLOBALS['__l10n']['Settings updated.']='Paramètres mis à jour.';

# index.php:85
# index.php:86
$GLOBALS['__l10n']['You must input a valid email !']='Vous devez saisir un email valide !';

# index.php:397
# index.php:436
# index.php:461
# index.php:487
$GLOBALS['__l10n']['Planning updated.']='Planning mis à jour.';

# index.php:405
$GLOBALS['__l10n']['Error during create planning task.']='Erreur pendant la création de la tâche planifiée.';

# index.php:523
# index.php:574
$GLOBALS['__l10n']['Missing informations.']='Informations manquantes.';

# index.php:526
$GLOBALS['__l10n']['Error adding subscriber.']='Erreur lors de l\'ajout d\'un abonné.';

# index.php:528
$GLOBALS['__l10n']['Subscriber added.']='Abonné ajouté.';

# index.php:581
$GLOBALS['__l10n']['Error updating subscriber.']='Erreur lors de la mise à jour d\'un abonné.';

# index.php:583
$GLOBALS['__l10n']['Subscriber updated.']='Abonné mis à jour.';

# index.php:597
$GLOBALS['__l10n']['No account removed.']='Pas de compte supprimé.';

# index.php:605
$GLOBALS['__l10n']['Account(s) successfully removed.']='Compte(s) supprimé(s) avec succès.';

# index.php:619
$GLOBALS['__l10n']['No account suspended.']='Pas de compte suspendu.';

# index.php:627
$GLOBALS['__l10n']['Account(s) successfully suspended.']='Compte(s) suspendu(s) avec succès.';

# index.php:641
$GLOBALS['__l10n']['No account enabled.']='Pas de compte activé.';

# index.php:649
$GLOBALS['__l10n']['Account(s) successfully enabled.']='Compte(s) activé(s) avec succés.';

# index.php:663
$GLOBALS['__l10n']['No account disabled.']='Pas de compte désactivé.';

# index.php:671
$GLOBALS['__l10n']['Account(s) successfully disabled.']='Compte(s) désactivé(s) avec succès.';

# index.php:710
$GLOBALS['__l10n']['No account changed.']='Pas de compte modifié.';

# index.php:716
$GLOBALS['__l10n']['Account(s) successfully changed.']='Compte(s) modifié(s) avec succès.';

# index.php:737
$GLOBALS['__l10n']['Datas exported.']='Données exportées.';

# index.php:757
$GLOBALS['__l10n']['Datas imported.']='Données importées.';

# index.php:842
# index.php:864
$GLOBALS['__l10n']['No account(s) updated.']='Pas de compte(s) mis à jour.';

# index.php:850
$GLOBALS['__l10n']['Format sending for account(s) successfully updated to html.']='Format d\'envoi pour le(s) abonné(s) mis à jour au format html.';

# index.php:872
$GLOBALS['__l10n']['Format sending for account(s) successfully updated to text.']='Format d\'envoi pour le(s) abonné(s) mis à jour au format text.';

# index.php:886
$GLOBALS['__l10n']['No template adapted.']='Pas de template adapté.';

# index.php:889
$GLOBALS['__l10n']['Template successfully adapted.']='Template adapté avec succès.';

# index.php:903
$GLOBALS['__l10n']['Erasing complete.']='Nettoyage terminé.';

# index.php:939
$GLOBALS['__l10n']['Are you sure you want to delete all informations about newsletter in database ?']='Etes-vous sûr de vouloir supprimer toutes les informations de newsletter dans la base de données ?';

# index.php:950
$GLOBALS['__l10n']['Subscribers']='Abonnés';

# index.php:959
$GLOBALS['__l10n']['Planning']='Planification';

$GLOBALS['__l10n']['Your account has been suspended.']='Votre compte a été suspendu.';

$GLOBALS['__l10n']['Newsletter is disabled.']='Newsletter est désactivé.';

$GLOBALS['__l10n']['Presentation message']='Message de présentation';

$GLOBALS['__l10n']['Use planning']='Utiliser la planification';

$GLOBALS['__l10n']['Mode']='Mode';

$GLOBALS['__l10n']['Period sending']='Période d\'envoi';

$GLOBALS['__l10n']['Activate plugin before using it']='Activer l\'extension avant de l\'utiliser';

$GLOBALS['__l10n']['Your sending mode is ']='Votre mode d\'envoi est';

$GLOBALS['__l10n']['Newsletter template successfully adapted.']='Template correctement adapté pour Newsletter.';

$GLOBALS['__l10n']['About Newsletter...']='A propos de Newsletter...';

$GLOBALS['__l10n']['Template(s) successfully adapted.']='Template(s) adapté(s) avec succès.';

$GLOBALS['__l10n']['Set state:']='Modifier l\'état:';

$GLOBALS['__l10n']['Mail to send:']='Mail à envoyer:';

$GLOBALS['__l10n']['Confirm']='Confirmation';

$GLOBALS['__l10n']['You account as been suspended.']='Votre abonnement a été suspendu.';

$GLOBALS['__l10n']['Your account as been canceled.']='Votre abonnement a été annulé.';

$GLOBALS['__l10n']['Your account as been validated.']='Votre inscription a été validée.';

$GLOBALS['__l10n']['To confirm you subscription, please click the link.']='Pour confirmer votre inscription, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['To enable your account, please click the link.']='Pour activer votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['Options']='Options';

$GLOBALS['__l10n']['To cancel your account, please click the link.']='Pour annuler votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['To suspend your account, please click the link.']='Pour suspendre votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['Newsletter for ']='Lettre d\'information pour';

$GLOBALS['__l10n']['Successful mail sent for ']='Courriel envoyé avec succès pour';

$GLOBALS['__l10n']['Mail sent error for ']='Echec de l\'envoi du courriel pour';

$GLOBALS['__l10n']['Nothing to send for ']='Rien à envoyer pour';

$GLOBALS['__l10n']['Newsletter subscription confirmation for ']='Confirmation d\'inscription pour';

$GLOBALS['__l10n']['Newsletter account suspend for ']='Suspension d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account activation for ']='Activation d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account removal for ']='Suppression d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account resume for ']='Information sur l\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Theme template adaptation']='Adaptation du template de thème';

$GLOBALS['__l10n']['Gestion']='Gestion';

$GLOBALS['__l10n']['Change settings:']='Modifier les paramètres:';

$GLOBALS['__l10n']['Clic here to edit your settings.']='Cliquez ici pour modifier vos paramètres.';

$GLOBALS['__l10n']['Widget']='Widget';

$GLOBALS['__l10n']['Widget manager:']='Gestionnaire de widget:';

$GLOBALS['__l10n']['Clic here to edit your widgets.']='Cliquez ici pour modifier vos widgets.';

$GLOBALS['__l10n']['Theme']='Theme';

$GLOBALS['__l10n']['Theme integration:']='Intégration au thème:';

$GLOBALS['__l10n']['You can add this code into your theme to display the Newsletter subscription form:']='Vous pouvez ajouter ce code à votre thème pour afficher le formulaire d\'abonnement à la newsletter:';

$GLOBALS['__l10n']['Email don\'t exist !']='L\'email n\'existe pas !';

$GLOBALS['__l10n']['Error deleting account !']='Erreur lors de la suppression du compte !';

$GLOBALS['__l10n']['Usage']='Mode d\'emploi';

$GLOBALS['__l10n']['General options']='Options générales';

$GLOBALS['__l10n']['Customizing the newsletter options']='Personnalisation de la newsletter';

?>