<?php
// Français translation of Newsletter, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:57
# _admin.php:59
# _public.php:69
# class.admin.php:744
# class.modele.php:1858
# index.php:32
$GLOBALS['__l10n']['Newsletter']='Lettre d\'informations';

# _admin.php:60
$GLOBALS['__l10n']['Show title']='Afficher le titre';

# _admin.php:62
$GLOBALS['__l10n']['In widget']='Dans un widget';

# _admin.php:63
$GLOBALS['__l10n']['In sublink']='Dans un lien';

# _admin.php:64
$GLOBALS['__l10n']['Title subscription link:']='Titre du lien de souscription:';

# _admin.php:64
# _public.php:72
$GLOBALS['__l10n']['Subscription link']='S\'abonner';

# _install.php:49
$GLOBALS['__l10n']['Unable to install Newsletter.']='Impossible d\'installer Newsletter';

# _public.php:84
$GLOBALS['__l10n']['Email']='Courriel';

# _public.php:87
$GLOBALS['__l10n']['Format']='Format';

# _public.php:89
# class.admin.php:350
# class.admin.php:753
# class.admin.php:798
$GLOBALS['__l10n']['html']='html';

# _public.php:90
# class.admin.php:349
# class.admin.php:754
# class.admin.php:797
# class.modele.php:1918
$GLOBALS['__l10n']['text']='texte';

# _public.php:92
# _public.php:102
$GLOBALS['__l10n']['Actions']='Actions';

# _public.php:95
# class.modele.php:1925
$GLOBALS['__l10n']['Change format']='Changer le format';

# _public.php:96
# class.admin.php:738
# class.modele.php:1892
$GLOBALS['__l10n']['Suspend']='Suspendre';

# _public.php:97
# class.modele.php:1896
$GLOBALS['__l10n']['Resume']='Résumé';

# _public.php:99
# _public.php:104
$GLOBALS['__l10n']['Unsubscribe']='Se désabonner';

# _public.php:118
# _public.php:119
# class.admin.php:504
# class.modele.php:1950
$GLOBALS['__l10n']['Captcha']='Code visuel';

# class.admin.php:212
$GLOBALS['__l10n']['No template to adapt.']='Pas de template à adapter.';

# class.admin.php:234
$GLOBALS['__l10n']['is not in your theme folder.']='n\'est pas dans votre répertoire de thème.';

# class.admin.php:238
$GLOBALS['__l10n']['is not in the plugin folder.']='n\'est pas dans le répertoire de plugin.';

# class.admin.php:242
$GLOBALS['__l10n']['is not readable.']='n\'est pas lisible';

# class.admin.php:310
# class.admin.php:317
$GLOBALS['__l10n']['Template created.']='Template créé.';

# class.admin.php:312
$GLOBALS['__l10n']['Unable to write file.']='Impossible d\'écrire le fichier.';

# class.admin.php:394
$GLOBALS['__l10n']['Plugin state']='Etat de l\'extension';

# class.admin.php:397
$GLOBALS['__l10n']['Activate plugin']='Activer l\'extension';

# class.admin.php:416
# index.php:592
$GLOBALS['__l10n']['Settings']='Paramètres';

# class.admin.php:428
$GLOBALS['__l10n']['Editor name']='Nom de l\'éditeur';

# class.admin.php:432
$GLOBALS['__l10n']['Editor email']='Email de l\'éditeur';

# class.admin.php:436
$GLOBALS['__l10n']['Presentation message']='Message de présentation';

# class.admin.php:440
$GLOBALS['__l10n']['Presentation message for posts']='Message de présentation pour les billets';

# class.admin.php:445
$GLOBALS['__l10n']['Introductory confirm message']='Introduction au lien de confirmation';

# class.admin.php:449
$GLOBALS['__l10n']['Title confirmation link']='Titre du lien de confirmation';

# class.admin.php:453
$GLOBALS['__l10n']['Introductory disable message']='Introduction au lien de désactivation';

# class.admin.php:457
$GLOBALS['__l10n']['Title disable link']='Titre du lien de désactivation';

# class.admin.php:461
$GLOBALS['__l10n']['Introductory enable message']='Introduction au lien d\'activation';

# class.admin.php:465
$GLOBALS['__l10n']['Title enable link']='Titre du lien d\'activation';

# class.admin.php:469
$GLOBALS['__l10n']['Introductory suspend message']='Introduction au lien de suspension';

# class.admin.php:473
$GLOBALS['__l10n']['Title suspend link']='Titre du lien de suspension';

# class.admin.php:480
$GLOBALS['__l10n']['Introductory message']='Message d\'introduction';

# class.admin.php:483
$GLOBALS['__l10n']['Concluding message']='Message de conclusion';

# class.admin.php:487
$GLOBALS['__l10n']['Message presentation form']='Message de présentation du formulaire';

# class.admin.php:494
$GLOBALS['__l10n']['Period sending']='Période d\'envoi';

# class.admin.php:501
$GLOBALS['__l10n']['Advanced Settings']='Paramètres avancés';

# class.admin.php:505
$GLOBALS['__l10n']['Mode']='Mode';

# class.admin.php:510
$GLOBALS['__l10n']['Automatic send']='Envoi automatique';

# class.admin.php:512
$GLOBALS['__l10n']['Maximum posts']='Nombre maximal de billets';

# class.admin.php:517
$GLOBALS['__l10n']['View contents posts']='Affiche le contenu des billets';

# class.admin.php:519
$GLOBALS['__l10n']['Size contents posts']='Taille maximale du contenu des billets';

# class.admin.php:528
$GLOBALS['__l10n']['Defaults']='Défauts';

# class.admin.php:579
$GLOBALS['__l10n']['Import/Export subscribers list']='Import/Export de la liste des abonnés';

# class.admin.php:582
$GLOBALS['__l10n']['This blog only']='Ce blog seulement';

# class.admin.php:586
$GLOBALS['__l10n']['All datas']='Toutes les données';

# class.admin.php:603
$GLOBALS['__l10n']['Adapt the template for the theme']='Adapter le template pour le thème';

# class.admin.php:604
$GLOBALS['__l10n']['Theme name']='Nom du thème';

# class.admin.php:608
$GLOBALS['__l10n']['Adapt']='Adapter';

# class.admin.php:614
$GLOBALS['__l10n']['Clic here to test the template.']='Cliquez ici pour tester le template.';

# class.admin.php:626
$GLOBALS['__l10n']['Check for plugin update']='Vérifier les mises à jour';

# class.admin.php:633
$GLOBALS['__l10n']['Check']='Vérifier';

# class.admin.php:643
$GLOBALS['__l10n']['Erasing all informations about newsletter in database']='Suppression de toutes les informations concernant newsletter dans votre base de données';

# class.admin.php:644
$GLOBALS['__l10n']['Be careful, please backup your database before erasing']='Attention, vous êtes priés de sauvegarder votre base de données avant de lancer la suppression';

# class.admin.php:647
$GLOBALS['__l10n']['Erasing']='Suppression';

# class.admin.php:660
$GLOBALS['__l10n']['Activate plugin before using it']='Activer l\'extension avant de l\'utiliser';

# class.admin.php:682
$GLOBALS['__l10n']['No subscriber for this blog.']='Pas d\'abonnés pour ce blog.';

# class.admin.php:699
$GLOBALS['__l10n']['Subscriber']='Abonné';

# class.admin.php:700
$GLOBALS['__l10n']['Subscribed']='Inscription';

# class.admin.php:702
# class.admin.php:741
$GLOBALS['__l10n']['Last sent']='Dernier envoi';

# class.admin.php:703
# class.admin.php:834
$GLOBALS['__l10n']['Mode send']='Mode d\'envoi';

# class.admin.php:704
# index.php:589
$GLOBALS['__l10n']['Edit']='Modifier';

# class.admin.php:712
# class.admin.php:712
$GLOBALS['__l10n']['Edit subscriber']='Modifier l\'abonné';

# class.admin.php:717
# class.admin.php:722
# class.admin.php:822
# class.admin.php:827
$GLOBALS['__l10n']['Never']='Jamais';

# class.admin.php:739
$GLOBALS['__l10n']['Disable']='Désactiver';

# class.admin.php:740
$GLOBALS['__l10n']['Enable']='Activer';

# class.admin.php:745
$GLOBALS['__l10n']['Confirmation']='Confirmation';

# class.admin.php:746
$GLOBALS['__l10n']['Suspension']='Suspension';

# class.admin.php:747
$GLOBALS['__l10n']['Deactivation']='Désactivation';

# class.admin.php:748
$GLOBALS['__l10n']['Activation']='Activation';

# class.admin.php:749
$GLOBALS['__l10n']['Changing format']='Changer de format';

# class.admin.php:760
$GLOBALS['__l10n']['refresh']='actualiser';

# class.admin.php:761
$GLOBALS['__l10n']['check all']='sélectionner tout';

# class.admin.php:762
$GLOBALS['__l10n']['uncheck all']='désélectionner tout';

# class.admin.php:763
$GLOBALS['__l10n']['toggle check all']='inverser la sélection';

# class.admin.php:767
$GLOBALS['__l10n']['Set state']='Modifier l\'état';

# class.admin.php:768
$GLOBALS['__l10n']['Set']='Modifier';

# class.admin.php:769
$GLOBALS['__l10n']['Mail to send']='Courrier à envoyer';

# class.admin.php:772
$GLOBALS['__l10n']['Set format']='Modifier le format';

# class.admin.php:773
$GLOBALS['__l10n']['Change']='Changer';

# class.admin.php:814
$GLOBALS['__l10n']['Edit a subscriber']='Modifier un abonné';

# class.admin.php:816
$GLOBALS['__l10n']['Update']='Mettre à jour';

# class.admin.php:830
$GLOBALS['__l10n']['Subscribed:']='Inscrit:';

# class.admin.php:832
$GLOBALS['__l10n']['Last sent:']='Dernier envoi:';

# class.admin.php:836
$GLOBALS['__l10n']['Registration code:']='Code d\'inscription:';

# class.admin.php:840
$GLOBALS['__l10n']['enabled']='actif';

# class.admin.php:841
$GLOBALS['__l10n']['suspended']='suspendu';

# class.admin.php:842
$GLOBALS['__l10n']['disabled']='désactivé';

# class.admin.php:852
$GLOBALS['__l10n']['Add a subscriber']='Ajouter un abonné';

# class.admin.php:860
$GLOBALS['__l10n']['Not allowed.']='Interdit.';

# class.modele.php:828
$GLOBALS['__l10n']['Thank you for your subscription.']='Merci pour votre inscription !';

# class.modele.php:829
$GLOBALS['__l10n']['Your account has been suspended.']='Votre compte a été suspendu.';

# class.modele.php:830
$GLOBALS['__l10n']['Your account has been canceled.']='Votre compte a été supprimé.';

# class.modele.php:831
$GLOBALS['__l10n']['Your account has been validated.']='Votre compte a été validé.';

# class.modele.php:832
$GLOBALS['__l10n']['Your sending format has been updated.']='Votre format d\'envoi a été mis à jour.';

# class.modele.php:880
$GLOBALS['__l10n']['Newsletter for']='Lettre d\'information pour';

# class.modele.php:896
$GLOBALS['__l10n']['Links:']='Liens:';

# class.modele.php:955
# class.modele.php:1073
# class.modele.php:1155
# class.modele.php:1237
# class.modele.php:1316
# class.modele.php:1450
# class.modele.php:1531
$GLOBALS['__l10n']['Successful mail sent for']='Courriel envoyé avec succès pour';

# class.modele.php:957
# class.modele.php:1075
# class.modele.php:1157
# class.modele.php:1239
# class.modele.php:1318
# class.modele.php:1452
# class.modele.php:1533
$GLOBALS['__l10n']['Mail sent error for']='Echec de l\'envoi du courriel pour';

# class.modele.php:959
$GLOBALS['__l10n']['Nothing to send for']='Rien à envoyer pour';

# class.modele.php:1031
# class.modele.php:1038
$GLOBALS['__l10n']['Newsletter subscription confirmation for']='Confirmation d\'inscription pour';

# class.modele.php:1031
$GLOBALS['__l10n']['Thanks you for subscribing.']='Merci pour votre inscription.';

# class.modele.php:1114
# class.modele.php:1121
$GLOBALS['__l10n']['Newsletter account suspend for']='Suspension d\'abonnement à la lettre d\'information pour';

# class.modele.php:1114
# class.modele.php:1276
# class.modele.php:1356
# class.modele.php:1496
$GLOBALS['__l10n']['Have a nice day !']='Passez une bonne journée !';

# class.modele.php:1194
# class.modele.php:1201
$GLOBALS['__l10n']['Newsletter account activation for']='Activation d\'abonnement à la lettre d\'information pour';

# class.modele.php:1194
$GLOBALS['__l10n']['Thank you for subscribing.']='Merci pour votre inscription.';

# class.modele.php:1276
# class.modele.php:1283
$GLOBALS['__l10n']['Newsletter account removal for']='Suppression d\'abonnement à la lettre d\'information pour';

# class.modele.php:1356
# class.modele.php:1363
$GLOBALS['__l10n']['Newsletter account resume for']='Information sur l\'abonnement à la lettre d\'information pour';

# class.modele.php:1394
# class.modele.php:1784
$GLOBALS['__l10n']['Your account is suspended.']='Votre abonnement est suspendu.';

# class.modele.php:1401
# class.modele.php:1768
$GLOBALS['__l10n']['Your account is disabled.']='Votre abonnement est désactivé.';

# class.modele.php:1408
# class.modele.php:1752
$GLOBALS['__l10n']['Your account is enabled.']='Votre abonnement est activé.';

# class.modele.php:1415
$GLOBALS['__l10n']['Your account is pending confirmation.']='Votre abonnement est en attente de confirmation.';

# class.modele.php:1431
$GLOBALS['__l10n']['Your sending mode is']='Votre format est';

# class.modele.php:1496
# class.modele.php:1503
$GLOBALS['__l10n']['Newsletter account change format for']='Changement du format sur l\'abonnement à la lettre d\'information pour';

# class.modele.php:1552
# class.modele.php:1579
# class.modele.php:1608
# class.modele.php:1635
# class.modele.php:1662
$GLOBALS['__l10n']['Newsletter is disabled.']='Newsletter est désactivé.';

# class.modele.php:1554
# class.modele.php:1582
# class.modele.php:1610
# class.modele.php:1637
# class.modele.php:1664
$GLOBALS['__l10n']['Bad email !']='Mauvais email ou format incorrect !';

# class.modele.php:1559
$GLOBALS['__l10n']['Email already exist !']='Email déja existant !';

# class.modele.php:1561
$GLOBALS['__l10n']['Error creating account !']='Erreur lors de la création du compte !';

# class.modele.php:1714
$GLOBALS['__l10n']['Test display template.']='Test d\'affichage du template.';

# class.modele.php:1718
$GLOBALS['__l10n']['About Newsletter ...']='A propos de Newsletter ...';

# class.modele.php:1719
$GLOBALS['__l10n']['About']='A propos';

# class.modele.php:1721
$GLOBALS['__l10n']['Authors']='Auteurs';

# class.modele.php:1727
# class.modele.php:1743
# class.modele.php:1759
# class.modele.php:1775
# class.modele.php:1791
$GLOBALS['__l10n']['Missing informations. ']='Informations manquantes.';

# class.modele.php:1731
$GLOBALS['__l10n']['Your subscription code is invalid.']='Votre code d\'inscription est invalide.';

# class.modele.php:1733
$GLOBALS['__l10n']['Account already confirmed.']='Abonnement déja confirmé.';

# class.modele.php:1736
$GLOBALS['__l10n']['Your subscription is confirmed.']='Votre inscription est confirmée.';

# class.modele.php:1736
# class.modele.php:1752
# class.modele.php:1768
# class.modele.php:1784
# class.modele.php:1798
$GLOBALS['__l10n']['You will soon receive an email.']='Vous allez bientôt recevoir un email.';

# class.modele.php:1747
# class.modele.php:1763
# class.modele.php:1779
# class.modele.php:1795
$GLOBALS['__l10n']['Unable to find you account informations.']='Impossible de trouver les informations de votre compte.';

# class.modele.php:1749
$GLOBALS['__l10n']['Account already enabled.']='Abonnement déja activé.';

# class.modele.php:1765
$GLOBALS['__l10n']['Account already disabled.']='Abonnement déja désactivé.';

# class.modele.php:1781
$GLOBALS['__l10n']['Account already suspended.']='Abonnement déja suspendu.';

# class.modele.php:1798
$GLOBALS['__l10n']['Your sending format is']='Votre format d\'envoi est';

# class.modele.php:1817
$GLOBALS['__l10n']['Bad captcha code.']='Mauvais code de vérification.';

# class.modele.php:1840
$GLOBALS['__l10n']['Error in formular.']='Erreur dans le formulaire.';

# class.plugin.php:274
$GLOBALS['__l10n']['Thanks you for reading.']='Merci de nous lire.';

# class.plugin.php:298
$GLOBALS['__l10n']['This is the newsletter for']='Voici la lettre d\'information pour';

# class.plugin.php:322
$GLOBALS['__l10n']['Here are the last post:']='Voici les derniers billets:';

# class.plugin.php:340
$GLOBALS['__l10n']['To confirm you subscription']='Pour confirmer votre inscription';

# class.plugin.php:358
# class.plugin.php:394
# class.plugin.php:430
# class.plugin.php:466
$GLOBALS['__l10n']['Click here']='Cliquez ici';

# class.plugin.php:376
$GLOBALS['__l10n']['To cancel your account']='Pour supprimer votre abonnement';

# class.plugin.php:412
$GLOBALS['__l10n']['To enable your account']='Pour activer votre abonnement';

# class.plugin.php:448
$GLOBALS['__l10n']['To suspend your account']='Pour suspendre votre abonnement';

# class.plugin.php:1136
$GLOBALS['__l10n']['No new version available.']='Pas de nouvelle version.';

# class.plugin.php:1138
$GLOBALS['__l10n']['New version available:']='Nouvelle version disponible:';

# class.plugin.php:1144
$GLOBALS['__l10n']['Read the post.']='Lire le billet.';

# class.plugin.php:1144
$GLOBALS['__l10n']['post']='billet';

# class.plugin.php:1146
$GLOBALS['__l10n']['Installer.']='Installeur.';

# class.plugin.php:1146
$GLOBALS['__l10n']['pkg.gz']='pkg.gz';

# class.plugin.php:1148
$GLOBALS['__l10n']['Archive.']='Archive.';

# class.plugin.php:1148
$GLOBALS['__l10n']['tar.gz']='tar.gz';

# index.php:65
# index.php:159
$GLOBALS['__l10n']['Settings updated.']='Paramètres mis à jour.';

# index.php:79
# index.php:80
$GLOBALS['__l10n']['You must input a valid email !']='Vous devez saisir un email valide !';

# index.php:194
# index.php:245
$GLOBALS['__l10n']['Missing informations.']='Informations manquantes.';

# index.php:197
$GLOBALS['__l10n']['Error adding subscriber.']='Erreur lors de l\'ajout d\'un abonné.';

# index.php:199
$GLOBALS['__l10n']['Subscriber added.']='Abonné ajouté.';

# index.php:252
$GLOBALS['__l10n']['Error updating subscriber.']='Erreur lors de la mise à jour d\'un abonné.';

# index.php:254
$GLOBALS['__l10n']['Subscriber updated.']='Abonné mis à jour.';

# index.php:268
$GLOBALS['__l10n']['No account removed.']='Pas de compte supprimé.';

# index.php:276
$GLOBALS['__l10n']['Account(s) successfully removed.']='Compte(s) supprimé(s) avec succès.';

# index.php:290
$GLOBALS['__l10n']['No account suspended.']='Pas de compte suspendu.';

# index.php:298
$GLOBALS['__l10n']['Account(s) successfully suspended.']='Compte(s) suspendu(s) avec succès.';

# index.php:312
$GLOBALS['__l10n']['No account enabled.']='Pas de compte activé.';

# index.php:320
$GLOBALS['__l10n']['Account(s) successfully enabled.']='Compte(s) activé(s) avec succés.';

# index.php:334
$GLOBALS['__l10n']['No account disabled.']='Pas de compte désactivé.';

# index.php:342
$GLOBALS['__l10n']['Account(s) successfully disabled.']='Compte(s) désactivé(s) avec succès.';

# index.php:375
$GLOBALS['__l10n']['No account changed.']='Pas de compte modifié.';

# index.php:380
$GLOBALS['__l10n']['Account(s) successfully changed.']='Compte(s) modifié(s) avec succès.';

# index.php:399
$GLOBALS['__l10n']['Datas exported.']='Données exportées.';

# index.php:419
$GLOBALS['__l10n']['Datas imported.']='Données importées.';

# index.php:492
# index.php:514
$GLOBALS['__l10n']['No account(s) updated.']='Pas de compte(s) mis à jour.';

# index.php:500
$GLOBALS['__l10n']['Format sending for account(s) successfully updated to html.']='Format d\'envoi pour le(s) abonné(s) mis à jour au format html.';

# index.php:522
$GLOBALS['__l10n']['Format sending for account(s) successfully updated to text.']='Format d\'envoi pour le(s) abonné(s) mis à jour au format text.';

# index.php:536
$GLOBALS['__l10n']['No template adapted.']='Pas de template adapté.';

# index.php:538
$GLOBALS['__l10n']['Template successfully adapted.']='Template adapté avec succès.';

# index.php:553
$GLOBALS['__l10n']['Erasing complete.']='Nettoyage terminé.';

# index.php:586
$GLOBALS['__l10n']['Subscribers']='Abonnés';

$GLOBALS['__l10n']['Your sending mode is ']='Votre mode d\'envoi est';

$GLOBALS['__l10n']['Newsletter template successfully adapted.']='Template correctement adapté pour Newsletter.';

$GLOBALS['__l10n']['About Newsletter...']='A propos de Newsletter...';

$GLOBALS['__l10n']['Template(s) successfully adapted.']='Template(s) adapté(s) avec succès.';

$GLOBALS['__l10n']['Set state:']='Modifier l\'état:';

$GLOBALS['__l10n']['Mail to send:']='Mail à envoyer:';

$GLOBALS['__l10n']['Confirm']='Confirmation';

$GLOBALS['__l10n']['You account as been suspended.']='Votre abonnement a été suspendu.';

$GLOBALS['__l10n']['Your account as been canceled.']='Votre abonnement a été annulé.';

$GLOBALS['__l10n']['Your account as been validated.']='Votre inscription a été validée.';

$GLOBALS['__l10n']['To confirm you subscription, please click the link.']='Pour confirmer votre inscription, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['To enable your account, please click the link.']='Pour activer votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['Options']='Options';

$GLOBALS['__l10n']['To cancel your account, please click the link.']='Pour annuler votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['To suspend your account, please click the link.']='Pour suspendre votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['Newsletter for ']='Lettre d\'information pour';

$GLOBALS['__l10n']['Successful mail sent for ']='Courriel envoyé avec succès pour';

$GLOBALS['__l10n']['Mail sent error for ']='Echec de l\'envoi du courriel pour';

$GLOBALS['__l10n']['Nothing to send for ']='Rien à envoyer pour';

$GLOBALS['__l10n']['Newsletter subscription confirmation for ']='Confirmation d\'inscription pour';

$GLOBALS['__l10n']['Newsletter account suspend for ']='Suspension d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account activation for ']='Activation d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account removal for ']='Suppression d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account resume for ']='Information sur l\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Theme template adaptation']='Adaptation du template de thème';

$GLOBALS['__l10n']['Gestion']='Gestion';

$GLOBALS['__l10n']['Change settings:']='Modifier les paramètres:';

$GLOBALS['__l10n']['Clic here to edit your settings.']='Cliquez ici pour modifier vos paramètres.';

$GLOBALS['__l10n']['Widget']='Widget';

$GLOBALS['__l10n']['Widget manager:']='Gestionnaire de widget:';

$GLOBALS['__l10n']['Clic here to edit your widgets.']='Cliquez ici pour modifier vos widgets.';

$GLOBALS['__l10n']['Theme']='Theme';

$GLOBALS['__l10n']['Theme integration:']='Intégration au thème:';

$GLOBALS['__l10n']['You can add this code into your theme to display the Newsletter subscription form:']='Vous pouvez ajouter ce code à votre thème pour afficher le formulaire d\'abonnement à la newsletter:';

$GLOBALS['__l10n']['Email don\'t exist !']='L\'email n\'existe pas !';

$GLOBALS['__l10n']['Error deleting account !']='Erreur lors de la suppression du compte !';

$GLOBALS['__l10n']['Usage']='Mode d\'emploi';

$GLOBALS['__l10n']['General options']='Options générales';

$GLOBALS['__l10n']['Customizing the newsletter options']='Personnalisation de la newsletter';

?>