<?php
// Français translation of Newsletter, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:57
# _admin.php:59
# _public.php:68
# class.admin.php:664
# class.modele.php:1583
# index.php:32
$GLOBALS['__l10n']['Newsletter']='Lettre d\'informations';

# _admin.php:60
$GLOBALS['__l10n']['Show title']='Afficher le titre';

# _admin.php:62
$GLOBALS['__l10n']['In widget']='Dans un widget';

# _admin.php:63
$GLOBALS['__l10n']['In sublink']='Dans un lien';

# _admin.php:64
$GLOBALS['__l10n']['Title subscription link:']='Titre du lien de souscription:';

# _admin.php:64
# _public.php:71
$GLOBALS['__l10n']['Subscription link']='S\'abonner';

# _install.php:49
$GLOBALS['__l10n']['Unable to install Newsletter.']='Impossible d\'installer Newsletter';

# _public.php:89
$GLOBALS['__l10n']['Unsubscribe']='Se désabonner';

# _public.php:102
# _public.php:103
# class.admin.php:447
# class.modele.php:1657
$GLOBALS['__l10n']['Captcha']='Code visuel';

# class.admin.php:205
$GLOBALS['__l10n']['No template to adapt.']='Pas de template à adapter.';

# class.admin.php:226
$GLOBALS['__l10n']['is not in your theme folder.']='n\'est pas dans votre répertoire de thème.';

# class.admin.php:229
$GLOBALS['__l10n']['is not in the plugin folder.']='n\'est pas dans le répertoire de plugin.';

# class.admin.php:232
$GLOBALS['__l10n']['is not readable.']='n\'est pas lisible';

# class.admin.php:266
$GLOBALS['__l10n']['Template created.']='Template créé';

# class.admin.php:268
$GLOBALS['__l10n']['Unable to write file.']='Impossible d\'écrire le fichier.';

# class.admin.php:298
$GLOBALS['__l10n']['text']='texte';

# class.admin.php:299
$GLOBALS['__l10n']['html']='html';

# class.admin.php:341
$GLOBALS['__l10n']['Plugin state']='Etat de l\'extension';

# class.admin.php:344
$GLOBALS['__l10n']['Activate plugin']='Activer l\'extension';

# class.admin.php:363
# index.php:520
$GLOBALS['__l10n']['Settings']='Paramètres';

# class.admin.php:375
$GLOBALS['__l10n']['Editor name']='Nom de l\'éditeur';

# class.admin.php:379
$GLOBALS['__l10n']['Editor email']='Email de l\'éditeur';

# class.admin.php:383
$GLOBALS['__l10n']['Presentation message']='Message de présentation';

# class.admin.php:387
$GLOBALS['__l10n']['Presentation message for posts']='Message de présentation pour les billets';

# class.admin.php:392
$GLOBALS['__l10n']['Introductory confirm message']='Introduction au lien de confirmation';

# class.admin.php:396
$GLOBALS['__l10n']['Title confirmation link']='Titre du lien de confirmation';

# class.admin.php:400
$GLOBALS['__l10n']['Introductory disable message']='Introduction au lien de désactivation';

# class.admin.php:404
$GLOBALS['__l10n']['Title disable link']='Titre du lien de désactivation';

# class.admin.php:408
$GLOBALS['__l10n']['Introductory enable message']='Introduction au lien d\'activation';

# class.admin.php:412
$GLOBALS['__l10n']['Title enable link']='Titre du lien d\'activation';

# class.admin.php:416
$GLOBALS['__l10n']['Introductory suspend message']='Introduction au lien de suspension';

# class.admin.php:420
$GLOBALS['__l10n']['Title suspend link']='Titre du lien de suspension';

# class.admin.php:426
$GLOBALS['__l10n']['Introductory message']='Message d\'introduction';

# class.admin.php:429
$GLOBALS['__l10n']['Concluding message']='Message de conclusion';

# class.admin.php:444
$GLOBALS['__l10n']['Advanced Settings']='Paramètres avancés';

# class.admin.php:448
$GLOBALS['__l10n']['Mode']='Mode';

# class.admin.php:453
$GLOBALS['__l10n']['Automatic send']='Envoi automatique';

# class.admin.php:455
$GLOBALS['__l10n']['Maximum posts']='Nombre maximal de billets';

# class.admin.php:460
$GLOBALS['__l10n']['View contents posts']='Affiche le contenu des billets';

# class.admin.php:462
$GLOBALS['__l10n']['Size contents posts']='Taille maximale du contenu des billets';

# class.admin.php:471
$GLOBALS['__l10n']['Defaults']='Défauts';

# class.admin.php:520
$GLOBALS['__l10n']['Import/Export subscribers list']='Import/Export de la liste des abonnés';

# class.admin.php:523
$GLOBALS['__l10n']['This blog only']='Ce blog seulement';

# class.admin.php:527
$GLOBALS['__l10n']['All datas']='Toutes les données';

# class.admin.php:544
$GLOBALS['__l10n']['Adapt the template for the theme']='Adapter le template pour le thème';

# class.admin.php:545
$GLOBALS['__l10n']['Theme name']='Nom du thème';

# class.admin.php:549
$GLOBALS['__l10n']['Adapt']='Adapter';

# class.admin.php:552
$GLOBALS['__l10n']['Clic here to test the template.']='Cliquez ici pour tester le template.';

# class.admin.php:564
$GLOBALS['__l10n']['Check for plugin update']='Vérifier les mises à jour';

# class.admin.php:571
$GLOBALS['__l10n']['Check']='Vérifier';

# class.admin.php:582
$GLOBALS['__l10n']['Activate plugin before using it']='Activer l\'extension avant de l\'utiliser';

# class.admin.php:604
$GLOBALS['__l10n']['No subscriber for this blog.']='Pas d\'abonnés pour ce blog.';

# class.admin.php:621
$GLOBALS['__l10n']['Subscriber']='Abonné';

# class.admin.php:622
$GLOBALS['__l10n']['Subscribed']='Inscription';

# class.admin.php:624
# class.admin.php:661
$GLOBALS['__l10n']['Last sent']='Dernier envoi';

# class.admin.php:625
# index.php:517
$GLOBALS['__l10n']['Edit']='Modifier';

# class.admin.php:633
# class.admin.php:633
$GLOBALS['__l10n']['Edit subscriber']='Modifier l\'abonné';

# class.admin.php:638
# class.admin.php:643
# class.admin.php:729
# class.admin.php:734
$GLOBALS['__l10n']['Never']='Jamais';

# class.admin.php:658
# class.admin.php:666
$GLOBALS['__l10n']['Suspend']='Suspension';

# class.admin.php:659
# class.admin.php:667
$GLOBALS['__l10n']['Disable']='Désactivation';

# class.admin.php:660
# class.admin.php:668
$GLOBALS['__l10n']['Enable']='Activation';

# class.admin.php:665
$GLOBALS['__l10n']['Confirm']='Confirmation';

# class.admin.php:674
$GLOBALS['__l10n']['refresh']='actualiser';

# class.admin.php:675
$GLOBALS['__l10n']['check all']='sélectionner tout';

# class.admin.php:676
$GLOBALS['__l10n']['uncheck all']='désélectionner tout';

# class.admin.php:677
$GLOBALS['__l10n']['toggle check all']='inverser la sélection';

# class.admin.php:681
$GLOBALS['__l10n']['Set state:']='Modifier l\'état:';

# class.admin.php:682
$GLOBALS['__l10n']['Set']='Modifier';

# class.admin.php:683
$GLOBALS['__l10n']['Mail to send:']='Mail à envoyer:';

# class.admin.php:721
$GLOBALS['__l10n']['Edit a subscriber']='Modifier un abonné';

# class.admin.php:723
$GLOBALS['__l10n']['Update']='Mettre à jour';

# class.admin.php:737
$GLOBALS['__l10n']['Subscribed:']='Inscrit:';

# class.admin.php:739
$GLOBALS['__l10n']['Last sent:']='Dernier envoi:';

# class.admin.php:741
$GLOBALS['__l10n']['Registration code:']='Code d\'inscription:';

# class.admin.php:745
$GLOBALS['__l10n']['enabled']='actif';

# class.admin.php:746
$GLOBALS['__l10n']['suspended']='suspendu';

# class.admin.php:747
$GLOBALS['__l10n']['disabled']='désactivé';

# class.admin.php:756
$GLOBALS['__l10n']['Add a subscriber']='Ajouter un abonné';

# class.admin.php:764
$GLOBALS['__l10n']['Not allowed.']='Interdit.';

# class.modele.php:746
# class.plugin.php:340
$GLOBALS['__l10n']['To confirm you subscription']='Pour confirmer votre inscription';

# class.modele.php:747
# class.modele.php:749
# class.modele.php:751
# class.modele.php:753
# class.plugin.php:358
# class.plugin.php:394
# class.plugin.php:430
# class.plugin.php:466
$GLOBALS['__l10n']['Click here']='Cliquez ici';

# class.modele.php:748
# class.plugin.php:376
$GLOBALS['__l10n']['To cancel your account']='Pour supprimer votre abonnement';

# class.modele.php:750
# class.plugin.php:412
$GLOBALS['__l10n']['To enable your account']='Pour activer votre abonnement';

# class.modele.php:752
# class.plugin.php:448
$GLOBALS['__l10n']['To suspend your account']='Pour suspendre votre abonnement';

# class.modele.php:763
$GLOBALS['__l10n']['Thank you for your subscription.']='Merci pour votre inscription !';

# class.modele.php:764
$GLOBALS['__l10n']['You account as been suspended.']='Votre abonnement a été suspendu.';

# class.modele.php:765
$GLOBALS['__l10n']['Your account as been canceled.']='Votre abonnement a été annulé.';

# class.modele.php:766
$GLOBALS['__l10n']['Your account as been validated.']='Votre inscription a été validée.';

# class.modele.php:816
$GLOBALS['__l10n']['Newsletter for']='Lettre d\'information pour';

# class.modele.php:832
$GLOBALS['__l10n']['Links:']='Liens:';

# class.modele.php:886
# class.modele.php:997
# class.modele.php:1074
# class.modele.php:1151
# class.modele.php:1226
# class.modele.php:1308
$GLOBALS['__l10n']['Successful mail sent for']='Courriel envoyé avec succès pour';

# class.modele.php:888
# class.modele.php:999
# class.modele.php:1076
# class.modele.php:1153
# class.modele.php:1228
# class.modele.php:1310
$GLOBALS['__l10n']['Mail sent error for']='Echec de l\'envoi du courriel pour';

# class.modele.php:890
$GLOBALS['__l10n']['Nothing to send for']='Rien à envoyer pour';

# class.modele.php:959
# class.modele.php:966
$GLOBALS['__l10n']['Newsletter subscription confirmation for']='Confirmation d\'inscription pour';

# class.modele.php:959
$GLOBALS['__l10n']['Thanks you for subscribing.']='Merci pour votre inscription.';

# class.modele.php:1038
# class.modele.php:1045
$GLOBALS['__l10n']['Newsletter account suspend for']='Suspension d\'abonnement à la lettre d\'information pour';

# class.modele.php:1038
# class.modele.php:1190
# class.modele.php:1266
$GLOBALS['__l10n']['Have a nice day !']='Passez une bonne journée !';

# class.modele.php:1113
# class.modele.php:1120
$GLOBALS['__l10n']['Newsletter account activation for']='Activation d\'abonnement à la lettre d\'information pour';

# class.modele.php:1113
$GLOBALS['__l10n']['Thank you for subscribing.']='Merci pour votre inscription.';

# class.modele.php:1190
# class.modele.php:1197
$GLOBALS['__l10n']['Newsletter account removal for']='Suppression d\'abonnement à la lettre d\'information pour';

# class.modele.php:1266
# class.modele.php:1273
$GLOBALS['__l10n']['Newsletter account resume for']='Information sur l\'abonnement à la lettre d\'information pour';

# class.modele.php:1330
# class.modele.php:1359
# class.modele.php:1388
# class.modele.php:1415
$GLOBALS['__l10n']['Newsletter is disabled.']='Newsletter est désactivé.';

# class.modele.php:1333
# class.modele.php:1362
# class.modele.php:1390
# class.modele.php:1417
$GLOBALS['__l10n']['Bad email !']='Mauvais email ou format incorrect !';

# class.modele.php:1339
$GLOBALS['__l10n']['Email already exist !']='Email déja existant !';

# class.modele.php:1341
$GLOBALS['__l10n']['Error creating account !']='Erreur lors de la création du compte !';

# class.modele.php:1462
$GLOBALS['__l10n']['Newsletter template successfully adapted.']='Template correctement adapté pour Newsletter.';

# class.modele.php:1466
$GLOBALS['__l10n']['About Newsletter...']='A propos de Newsletter...';

# class.modele.php:1471
# class.modele.php:1487
# class.modele.php:1503
# class.modele.php:1519
$GLOBALS['__l10n']['Missing informations. ']='Informations manquantes.';

# class.modele.php:1475
$GLOBALS['__l10n']['Your subscription code is invalid.']='Votre code d\'inscription est invalide.';

# class.modele.php:1477
$GLOBALS['__l10n']['Account already confirmed.']='Abonnement déja confirmé.';

# class.modele.php:1480
$GLOBALS['__l10n']['Your subscription is confirmed.']='Votre inscription est confirmée.';

# class.modele.php:1480
# class.modele.php:1496
# class.modele.php:1512
# class.modele.php:1528
$GLOBALS['__l10n']['You will soon receive an email.']='Vous allez bientôt recevoir un email.';

# class.modele.php:1491
# class.modele.php:1507
# class.modele.php:1523
$GLOBALS['__l10n']['Unable to find you account informations.']='Impossible de trouver les informations de votre compte.';

# class.modele.php:1493
$GLOBALS['__l10n']['Account already enabled.']='Abonnement déja activé.';

# class.modele.php:1496
$GLOBALS['__l10n']['Your account is enabled.']='Votre abonnement est activé.';

# class.modele.php:1509
$GLOBALS['__l10n']['Account already disabled.']='Abonnement déja désactivé.';

# class.modele.php:1512
$GLOBALS['__l10n']['Your account is disabled.']='Votre abonnement est désactivé.';

# class.modele.php:1525
$GLOBALS['__l10n']['Account already suspended.']='Abonnement déja suspendu.';

# class.modele.php:1528
$GLOBALS['__l10n']['Your account is suspended.']='Votre abonnement est suspendu.';

# class.modele.php:1546
$GLOBALS['__l10n']['Bad captcha code.']='Mauvais code de vérification.';

# class.modele.php:1565
$GLOBALS['__l10n']['Error in formular.']='Erreur dans le formulaire.';

# class.plugin.php:274
$GLOBALS['__l10n']['Thanks you for reading.']='Merci de nous lire.';

# class.plugin.php:298
$GLOBALS['__l10n']['This is the newsletter for']='Voici la lettre d\'information pour';

# class.plugin.php:322
$GLOBALS['__l10n']['Here are the last post:']='Voici les derniers billets:';

# class.plugin.php:1087
$GLOBALS['__l10n']['No new version available.']='Pas de nouvelle version.';

# class.plugin.php:1089
$GLOBALS['__l10n']['New version available:']='Nouvelle version disponible:';

# class.plugin.php:1095
$GLOBALS['__l10n']['Read the post.']='Lire le billet.';

# class.plugin.php:1095
$GLOBALS['__l10n']['post']='billet';

# class.plugin.php:1097
$GLOBALS['__l10n']['Installer.']='Installeur.';

# class.plugin.php:1097
$GLOBALS['__l10n']['pkg.gz']='pkg.gz';

# class.plugin.php:1099
$GLOBALS['__l10n']['Archive.']='Archive.';

# class.plugin.php:1099
$GLOBALS['__l10n']['tar.gz']='tar.gz';

# index.php:61
# index.php:149
$GLOBALS['__l10n']['Settings updated.']='Paramètres mis à jour.';

# index.php:75
# index.php:76
$GLOBALS['__l10n']['You must input a valid email !']='Vous devez saisir un email valide !';

# index.php:184
# index.php:230
$GLOBALS['__l10n']['Missing informations.']='Informations manquantes.';

# index.php:187
$GLOBALS['__l10n']['Error adding subscriber.']='Erreur lors de l\'ajout d\'un abonné.';

# index.php:189
$GLOBALS['__l10n']['Subscriber added.']='Abonné ajouté.';

# index.php:237
$GLOBALS['__l10n']['Error updating subscriber.']='Erreur lors de la mise à jour d\'un abonné.';

# index.php:239
$GLOBALS['__l10n']['Subscriber updated.']='Abonné mis à jour.';

# index.php:253
$GLOBALS['__l10n']['No account removed.']='Pas de compte supprimé.';

# index.php:261
$GLOBALS['__l10n']['Account(s) successfully removed.']='Compte(s) supprimé(s) avec succès.';

# index.php:275
$GLOBALS['__l10n']['No account suspended.']='Pas de compte suspendu.';

# index.php:283
$GLOBALS['__l10n']['Account(s) successfully suspended.']='Compte(s) suspendu(s) avec succès.';

# index.php:297
$GLOBALS['__l10n']['No account enabled.']='Pas de compte activé.';

# index.php:305
$GLOBALS['__l10n']['Account(s) successfully enabled.']='Compte(s) activé(s) avec succés.';

# index.php:319
$GLOBALS['__l10n']['No account disabled.']='Pas de compte désactivé.';

# index.php:327
$GLOBALS['__l10n']['Account(s) successfully disabled.']='Compte(s) désactivé(s) avec succès.';

# index.php:360
$GLOBALS['__l10n']['No account changed.']='Pas de compte modifié.';

# index.php:365
$GLOBALS['__l10n']['Account(s) successfully changed.']='Compte(s) modifié(s) avec succès.';

# index.php:384
$GLOBALS['__l10n']['Datas exported.']='Données exportées.';

# index.php:404
$GLOBALS['__l10n']['Datas imported.']='Données importées.';

# index.php:478
$GLOBALS['__l10n']['No template adapted.']='Pas de template adapté.';

# index.php:481
$GLOBALS['__l10n']['Template(s) successfully adapted.']='Template(s) adapté(s) avec succès.';

# index.php:514
$GLOBALS['__l10n']['Subscribers']='Abonnés';

$GLOBALS['__l10n']['To confirm you subscription, please click the link.']='Pour confirmer votre inscription, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['To enable your account, please click the link.']='Pour activer votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['Options']='Options';

$GLOBALS['__l10n']['To cancel your account, please click the link.']='Pour annuler votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['To suspend your account, please click the link.']='Pour suspendre votre abonnement, merci de cliquer sur le lien.';

$GLOBALS['__l10n']['Newsletter for ']='Lettre d\'information pour';

$GLOBALS['__l10n']['Successful mail sent for ']='Courriel envoyé avec succès pour';

$GLOBALS['__l10n']['Mail sent error for ']='Echec de l\'envoi du courriel pour';

$GLOBALS['__l10n']['Nothing to send for ']='Rien à envoyer pour';

$GLOBALS['__l10n']['Newsletter subscription confirmation for ']='Confirmation d\'inscription pour';

$GLOBALS['__l10n']['Newsletter account suspend for ']='Suspension d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account activation for ']='Activation d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account removal for ']='Suppression d\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Newsletter account resume for ']='Information sur l\'abonnement à la lettre d\'information pour';

$GLOBALS['__l10n']['Theme template adaptation']='Adaptation du template de thème';

$GLOBALS['__l10n']['Gestion']='Gestion';

$GLOBALS['__l10n']['Change settings:']='Modifier les paramètres:';

$GLOBALS['__l10n']['Clic here to edit your settings.']='Cliquez ici pour modifier vos paramètres.';

$GLOBALS['__l10n']['Widget']='Widget';

$GLOBALS['__l10n']['Widget manager:']='Gestionnaire de widget:';

$GLOBALS['__l10n']['Clic here to edit your widgets.']='Cliquez ici pour modifier vos widgets.';

$GLOBALS['__l10n']['Theme']='Theme';

$GLOBALS['__l10n']['Theme integration:']='Intégration au thème:';

$GLOBALS['__l10n']['You can add this code into your theme to display the Newsletter subscription form:']='Vous pouvez ajouter ce code à votre thème pour afficher le formulaire d\'abonnement à la newsletter:';

$GLOBALS['__l10n']['Email don\'t exist !']='L\'email n\'existe pas !';

$GLOBALS['__l10n']['Error deleting account !']='Erreur lors de la suppression du compte !';

$GLOBALS['__l10n']['Usage']='Mode d\'emploi';

$GLOBALS['__l10n']['About']='A propos';

$GLOBALS['__l10n']['General options']='Options générales';

$GLOBALS['__l10n']['Customizing the newsletter options']='Personnalisation de la newsletter';

?>