<?php
// French translation of Simple Website, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:113
$GLOBALS['__l10n']['Simple Website']='Site web simple';

# _admin.php:116
$GLOBALS['__l10n']['Parent Menu Item:']='Elément parent dans le menu';

# _admin.php:117
$GLOBALS['__l10n']['Menu Tag:']='Tag du menu';

# _admin.php:118
$GLOBALS['__l10n']['Template file name:']='Nom de fichier template';

# _admin.php:119
$GLOBALS['__l10n']['Leave blank for default template']='Laisser vide pour le template par défaut';

# _admin.php:121
$GLOBALS['__l10n']['Leave blank for default feed URL']='Laisser vide pour l\'URL par défaut';

# _admin.php:191
$GLOBALS['__l10n']['Simple Website Menu']='Menu pour site web simple';

# _admin.php:192
$GLOBALS['__l10n']['Menu']='Menu';

# _admin.php:193
$GLOBALS['__l10n']['Display Sitemap']='Afficher le plan du site';

# _admin.php:194
$GLOBALS['__l10n']['Sitemap Text:']='Texte pour le plan du site :';

# _admin.php:194
# tools.php:27
$GLOBALS['__l10n']['Sitemap']='Plan du site';

?>