<?php


/*

DON'T EDIT THIS FILE!

This file was automatically generated by the Lime parser generator.
The real source code you should be looking at is in one or more
grammar files in the Lime format.

THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
file that your error happened, because there are enough comments to
help you debug your grammar.

If you ignore this warning, you're shooting yourself in the brain,
not the foot.

*/

class expatEngine extends lime_parser {
var $qi = 0;
var $i = array (
  0 => 
  array (
    'exp' => 's 1',
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
    'start' => 's 50',
    '\'start\'' => 'a \'start\'',
  ),
  1 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '#' => 'r 0',
  ),
  2 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 8',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  3 => 
  array (
    '\'%\'' => 'r 1',
    '\'/\'' => 'r 1',
    '\'*\'' => 'r 1',
    '\'-\'' => 'r 1',
    '\'+\'' => 'r 1',
    'GE' => 'r 1',
    'LE' => 'r 1',
    'GT' => 'r 1',
    'LT' => 'r 1',
    'NE' => 'r 1',
    'EQ' => 'r 1',
    'AND' => 'r 1',
    'OR' => 'r 1',
    'XOR' => 'r 1',
    '\')\'' => 'r 1',
    '\',\'' => 'r 1',
    '#' => 'r 1',
  ),
  4 => 
  array (
    '\'%\'' => 'r 2',
    '\'/\'' => 'r 2',
    '\'*\'' => 'r 2',
    '\'-\'' => 'r 2',
    '\'+\'' => 'r 2',
    'GE' => 'r 2',
    'LE' => 'r 2',
    'GT' => 'r 2',
    'LT' => 'r 2',
    'NE' => 'r 2',
    'EQ' => 'r 2',
    'AND' => 'r 2',
    'OR' => 'r 2',
    'XOR' => 'r 2',
    '\')\'' => 'r 2',
    '\',\'' => 'r 2',
    '#' => 'r 2',
  ),
  5 => 
  array (
    '\'%\'' => 'r 3',
    '\'/\'' => 'r 3',
    '\'*\'' => 'r 3',
    '\'-\'' => 'r 3',
    '\'+\'' => 'r 3',
    'GE' => 'r 3',
    'LE' => 'r 3',
    'GT' => 'r 3',
    'LT' => 'r 3',
    'NE' => 'r 3',
    'EQ' => 'r 3',
    'AND' => 'r 3',
    'OR' => 'r 3',
    'XOR' => 'r 3',
    '\')\'' => 'r 3',
    '\',\'' => 'r 3',
    '#' => 'r 3',
  ),
  6 => 
  array (
    'GE' => 'r 4',
    '\'%\'' => 'r 4',
    '\'/\'' => 'r 4',
    '\'*\'' => 'r 4',
    '\'-\'' => 'r 4',
    '\'+\'' => 'r 4',
    'LE' => 'r 4',
    'GT' => 'r 4',
    'LT' => 'r 4',
    'NE' => 'r 4',
    'EQ' => 'r 4',
    'AND' => 'r 4',
    'OR' => 'r 4',
    'XOR' => 'r 4',
    '\')\'' => 'r 4',
    '\',\'' => 'r 4',
    '#' => 'r 4',
  ),
  7 => 
  array (
    'AND' => 'r 5',
    'OR' => 'r 5',
    'XOR' => 'r 5',
    'GE' => 'r 5',
    '\'%\'' => 'r 5',
    '\'/\'' => 'r 5',
    '\'*\'' => 'r 5',
    '\'-\'' => 'r 5',
    '\'+\'' => 'r 5',
    'LE' => 'r 5',
    'GT' => 'r 5',
    'LT' => 'r 5',
    'NE' => 'r 5',
    'EQ' => 'r 5',
    '\')\'' => 'r 5',
    '\',\'' => 'r 5',
    '#' => 'r 5',
  ),
  8 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 6',
    '\',\'' => 'r 6',
    '#' => 'r 6',
  ),
  9 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 10',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  10 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 16',
    '\',\'' => 'r 16',
    '#' => 'r 16',
  ),
  11 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 12',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  12 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 'r 17',
    '\'-\'' => 'r 17',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 17',
    '\',\'' => 'r 17',
    '#' => 'r 17',
  ),
  13 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 14',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  14 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 'r 18',
    '\'-\'' => 'r 18',
    '\'*\'' => 'r 18',
    '\'/\'' => 'r 18',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 18',
    '\',\'' => 'r 18',
    '#' => 'r 18',
  ),
  15 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 16',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  16 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 'r 19',
    '\'-\'' => 'r 19',
    '\'*\'' => 'r 19',
    '\'/\'' => 'r 19',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 19',
    '\',\'' => 'r 19',
    '#' => 'r 19',
  ),
  17 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 18',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  18 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 20',
    '\',\'' => 'r 20',
    '#' => 'r 20',
  ),
  19 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 20',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  20 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 21',
    '\',\'' => 'r 21',
    '#' => 'r 21',
  ),
  21 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 22',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  22 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 22',
    '\',\'' => 'r 22',
    '#' => 'r 22',
  ),
  23 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 24',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  24 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 23',
    '\',\'' => 'r 23',
    '#' => 'r 23',
  ),
  25 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 26',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  26 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 24',
    '\',\'' => 'r 24',
    '#' => 'r 24',
  ),
  27 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 28',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  28 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 25',
    '\',\'' => 'r 25',
    '#' => 'r 25',
  ),
  29 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 30',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  30 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 26',
    '\',\'' => 'r 26',
    '#' => 'r 26',
  ),
  31 => 
  array (
    'number' => 'r 27',
    'string' => 'r 27',
    '\'(\'' => 'r 27',
    '\'!\'' => 'r 27',
    'varname' => 'r 27',
  ),
  32 => 
  array (
    'number' => 'r 28',
    'string' => 'r 28',
    '\'(\'' => 'r 28',
    '\'!\'' => 'r 28',
    'varname' => 'r 28',
  ),
  33 => 
  array (
    'number' => 'r 29',
    'string' => 'r 29',
    '\'(\'' => 'r 29',
    '\'!\'' => 'r 29',
    'varname' => 'r 29',
  ),
  34 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 35',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  35 => 
  array (
    'logical' => 's 2',
    '\')\'' => 's 36',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
  ),
  36 => 
  array (
    'AND' => 'r 7',
    'OR' => 'r 7',
    'XOR' => 'r 7',
    'GE' => 'r 7',
    '\'%\'' => 'r 7',
    '\'/\'' => 'r 7',
    '\'*\'' => 'r 7',
    '\'-\'' => 'r 7',
    '\'+\'' => 'r 7',
    'LE' => 'r 7',
    'GT' => 'r 7',
    'LT' => 'r 7',
    'NE' => 'r 7',
    'EQ' => 'r 7',
    '\')\'' => 'r 7',
    '\',\'' => 'r 7',
    '#' => 'r 7',
  ),
  37 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 38',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  38 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 'r 8',
    '\'-\'' => 'r 8',
    '\'*\'' => 'r 8',
    '\'/\'' => 'r 8',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 8',
    '\',\'' => 'r 8',
    '#' => 'r 8',
  ),
  39 => 
  array (
    'AND' => 'r 9',
    'OR' => 'r 9',
    'XOR' => 'r 9',
    'GE' => 'r 9',
    '\'%\'' => 'r 9',
    '\'/\'' => 'r 9',
    '\'*\'' => 'r 9',
    '\'-\'' => 'r 9',
    '\'+\'' => 'r 9',
    'LE' => 'r 9',
    'GT' => 'r 9',
    'LT' => 'r 9',
    'NE' => 'r 9',
    'EQ' => 'r 9',
    '\')\'' => 'r 9',
    '\',\'' => 'r 9',
    '#' => 'r 9',
  ),
  40 => 
  array (
    '\'.\'' => 's 41',
    '\'(\'' => 's 43',
    '\'%\'' => 'r 10',
    '\'/\'' => 'r 10',
    '\'*\'' => 'r 10',
    '\'-\'' => 'r 10',
    '\'+\'' => 'r 10',
    'GE' => 'r 10',
    'LE' => 'r 10',
    'GT' => 'r 10',
    'LT' => 'r 10',
    'NE' => 'r 10',
    'EQ' => 'r 10',
    'AND' => 'r 10',
    'OR' => 'r 10',
    'XOR' => 'r 10',
    '\')\'' => 'r 10',
    '\',\'' => 'r 10',
    '#' => 'r 10',
  ),
  41 => 
  array (
    'varname' => 's 42',
  ),
  42 => 
  array (
    '\'%\'' => 'r 11',
    '\'/\'' => 'r 11',
    '\'*\'' => 'r 11',
    '\'-\'' => 'r 11',
    '\'+\'' => 'r 11',
    'GE' => 'r 11',
    'LE' => 'r 11',
    'GT' => 'r 11',
    'LT' => 'r 11',
    'NE' => 'r 11',
    'EQ' => 'r 11',
    'AND' => 'r 11',
    'OR' => 'r 11',
    'XOR' => 'r 11',
    '\')\'' => 'r 11',
    '\',\'' => 'r 11',
    '#' => 'r 11',
  ),
  43 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 44',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
    '\')\'' => 's 45',
    'args' => 's 46',
  ),
  44 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\',\'' => 'r 14',
    '\')\'' => 'r 14',
  ),
  45 => 
  array (
    'AND' => 'r 12',
    'OR' => 'r 12',
    'XOR' => 'r 12',
    'GE' => 'r 12',
    '\'%\'' => 'r 12',
    '\'/\'' => 'r 12',
    '\'*\'' => 'r 12',
    '\'-\'' => 'r 12',
    '\'+\'' => 'r 12',
    'LE' => 'r 12',
    'GT' => 'r 12',
    'LT' => 'r 12',
    'NE' => 'r 12',
    'EQ' => 'r 12',
    '\')\'' => 'r 12',
    '\',\'' => 'r 12',
    '#' => 'r 12',
  ),
  46 => 
  array (
    '\')\'' => 's 47',
    '\',\'' => 's 48',
  ),
  47 => 
  array (
    'AND' => 'r 13',
    'OR' => 'r 13',
    'XOR' => 'r 13',
    'GE' => 'r 13',
    '\'%\'' => 'r 13',
    '\'/\'' => 'r 13',
    '\'*\'' => 'r 13',
    '\'-\'' => 'r 13',
    '\'+\'' => 'r 13',
    'LE' => 'r 13',
    'GT' => 'r 13',
    'LT' => 'r 13',
    'NE' => 'r 13',
    'EQ' => 'r 13',
    '\')\'' => 'r 13',
    '\',\'' => 'r 13',
    '#' => 'r 13',
  ),
  48 => 
  array (
    'variable' => 's 3',
    'number' => 's 4',
    'string' => 's 5',
    'arithmetic' => 's 6',
    'comparison' => 's 7',
    'exp' => 's 49',
    '\'(\'' => 's 34',
    '\'!\'' => 's 37',
    'function' => 's 39',
    'varname' => 's 40',
  ),
  49 => 
  array (
    'logical' => 's 2',
    '\'+\'' => 's 9',
    '\'-\'' => 's 11',
    '\'*\'' => 's 13',
    '\'/\'' => 's 15',
    '\'%\'' => 's 17',
    'EQ' => 's 19',
    'NE' => 's 21',
    'LT' => 's 23',
    'GT' => 's 25',
    'LE' => 's 27',
    'GE' => 's 29',
    'AND' => 's 31',
    'OR' => 's 32',
    'XOR' => 's 33',
    '\')\'' => 'r 15',
    '\',\'' => 'r 15',
  ),
  50 => 
  array (
    '#' => 'r 30',
  ),
);
function reduce_0_start_1($tokens, &$result) {
#
# (0) start :=  exp
#
$result = reset($tokens);
 $result=$tokens[0];
}

function reduce_1_exp_1($tokens, &$result) {
#
# (1) exp :=  variable
#
$result = reset($tokens);

}

function reduce_2_exp_2($tokens, &$result) {
#
# (2) exp :=  number
#
$result = reset($tokens);
$result= new eaValue($tokens[0]);
}

function reduce_3_exp_3($tokens, &$result) {
#
# (3) exp :=  string
#
$result = reset($tokens);
 $result = new eaValue($tokens[0]);
}

function reduce_4_exp_4($tokens, &$result) {
#
# (4) exp :=  arithmetic
#
$result = reset($tokens);

}

function reduce_5_exp_5($tokens, &$result) {
#
# (5) exp :=  comparison
#
$result = reset($tokens);

}

function reduce_6_exp_6($tokens, &$result) {
#
# (6) exp :=  exp  logical  exp
#
$result = reset($tokens);
$result = new eaLogicalExpression($tokens[0],$tokens[2],$tokens[1]);
}

function reduce_7_exp_7($tokens, &$result) {
#
# (7) exp :=  '('  exp  ')'
#
$result = $tokens[1];
$result = new eaGroupExpression($tokens[1]);
}

function reduce_8_exp_8($tokens, &$result) {
#
# (8) exp :=  '!'  exp
#
$result = reset($tokens);
$result = new eaNotExpression($tokens[1]);
}

function reduce_9_exp_9($tokens, &$result) {
#
# (9) exp :=  function
#
$result = reset($tokens);

}

function reduce_10_variable_1($tokens, &$result) {
#
# (10) variable :=  varname
#
$result = reset($tokens);
 $result = new eaVariable(null,$tokens[0]);
}

function reduce_11_variable_2($tokens, &$result) {
#
# (11) variable :=  varname  '.'  varname
#
$result = reset($tokens);
 $result= new eaVariable($tokens[0],$tokens[2]);
}

function reduce_12_function_1($tokens, &$result) {
#
# (12) function :=  varname  '('  ')'
#
$result = reset($tokens);
 $result = new eaFunction($tokens[0],array()); 
}

function reduce_13_function_2($tokens, &$result) {
#
# (13) function :=  varname  '('  args  ')'
#
$result = reset($tokens);
 $result = new eaFunction($tokens[0],$tokens[2]); 
}

function reduce_14_args_1($tokens, &$result) {
#
# (14) args :=  exp
#
$result = reset($tokens);
 $result = array($tokens[0]);
}

function reduce_15_args_2($tokens, &$result) {
#
# (15) args :=  args  ','  exp
#
$result = reset($tokens);
 $tokens[0][]=$tokens[2]; $result = $tokens[0];
}

function reduce_16_arithmetic_1($tokens, &$result) {
#
# (16) arithmetic :=  exp  '+'  exp
#
$result = reset($tokens);
$result = new eaArithmeticExpression($tokens[0],$tokens[2],'+');
}

function reduce_17_arithmetic_2($tokens, &$result) {
#
# (17) arithmetic :=  exp  '-'  exp
#
$result = reset($tokens);
$result = new eaArithmeticExpression($tokens[0],$tokens[2],'-');
}

function reduce_18_arithmetic_3($tokens, &$result) {
#
# (18) arithmetic :=  exp  '*'  exp
#
$result = reset($tokens);
$result = new eaArithmeticExpression($tokens[0],$tokens[2],'*');
}

function reduce_19_arithmetic_4($tokens, &$result) {
#
# (19) arithmetic :=  exp  '/'  exp
#
$result = reset($tokens);
$result = new eaArithmeticExpression($tokens[0],$tokens[2],'/');
}

function reduce_20_arithmetic_5($tokens, &$result) {
#
# (20) arithmetic :=  exp  '%'  exp
#
$result = reset($tokens);
$result = new eaArithmeticExpression($tokens[0],$tokens[2],'%');
}

function reduce_21_comparison_1($tokens, &$result) {
#
# (21) comparison :=  exp  EQ  exp
#
$result = reset($tokens);
$result = new eaComparisonExpression($tokens[0],$tokens[2],"==");
}

function reduce_22_comparison_2($tokens, &$result) {
#
# (22) comparison :=  exp  NE  exp
#
$result = reset($tokens);
$result = new eaComparisonExpression($tokens[0],$tokens[2],"!=");
}

function reduce_23_comparison_3($tokens, &$result) {
#
# (23) comparison :=  exp  LT  exp
#
$result = reset($tokens);
$result = new eaComparisonExpression($tokens[0],$tokens[2],"<");
}

function reduce_24_comparison_4($tokens, &$result) {
#
# (24) comparison :=  exp  GT  exp
#
$result = reset($tokens);
$result = new eaComparisonExpression($tokens[0],$tokens[2],">");
}

function reduce_25_comparison_5($tokens, &$result) {
#
# (25) comparison :=  exp  LE  exp
#
$result = reset($tokens);
$result = new eaComparisonExpression($tokens[0],$tokens[2],"<=");
}

function reduce_26_comparison_6($tokens, &$result) {
#
# (26) comparison :=  exp  GE  exp
#
$result = reset($tokens);
$result = new eaComparisonExpression($tokens[0],$tokens[2],">=");
}

function reduce_27_logical_1($tokens, &$result) {
#
# (27) logical :=  AND
#
$result = reset($tokens);

}

function reduce_28_logical_2($tokens, &$result) {
#
# (28) logical :=  OR
#
$result = reset($tokens);

}

function reduce_29_logical_3($tokens, &$result) {
#
# (29) logical :=  XOR
#
$result = reset($tokens);

}

function reduce_30_start_2($tokens, &$result) {
#
# (30) 'start' :=  start
#
$result = reset($tokens);

}

var $method = array (
  0 => 'reduce_0_start_1',
  1 => 'reduce_1_exp_1',
  2 => 'reduce_2_exp_2',
  3 => 'reduce_3_exp_3',
  4 => 'reduce_4_exp_4',
  5 => 'reduce_5_exp_5',
  6 => 'reduce_6_exp_6',
  7 => 'reduce_7_exp_7',
  8 => 'reduce_8_exp_8',
  9 => 'reduce_9_exp_9',
  10 => 'reduce_10_variable_1',
  11 => 'reduce_11_variable_2',
  12 => 'reduce_12_function_1',
  13 => 'reduce_13_function_2',
  14 => 'reduce_14_args_1',
  15 => 'reduce_15_args_2',
  16 => 'reduce_16_arithmetic_1',
  17 => 'reduce_17_arithmetic_2',
  18 => 'reduce_18_arithmetic_3',
  19 => 'reduce_19_arithmetic_4',
  20 => 'reduce_20_arithmetic_5',
  21 => 'reduce_21_comparison_1',
  22 => 'reduce_22_comparison_2',
  23 => 'reduce_23_comparison_3',
  24 => 'reduce_24_comparison_4',
  25 => 'reduce_25_comparison_5',
  26 => 'reduce_26_comparison_6',
  27 => 'reduce_27_logical_1',
  28 => 'reduce_28_logical_2',
  29 => 'reduce_29_logical_3',
  30 => 'reduce_30_start_2',
);
var $a = array (
  0 => 
  array (
    'symbol' => 'start',
    'len' => 1,
    'replace' => true,
  ),
  1 => 
  array (
    'symbol' => 'exp',
    'len' => 1,
    'replace' => true,
  ),
  2 => 
  array (
    'symbol' => 'exp',
    'len' => 1,
    'replace' => true,
  ),
  3 => 
  array (
    'symbol' => 'exp',
    'len' => 1,
    'replace' => true,
  ),
  4 => 
  array (
    'symbol' => 'exp',
    'len' => 1,
    'replace' => true,
  ),
  5 => 
  array (
    'symbol' => 'exp',
    'len' => 1,
    'replace' => true,
  ),
  6 => 
  array (
    'symbol' => 'exp',
    'len' => 3,
    'replace' => true,
  ),
  7 => 
  array (
    'symbol' => 'exp',
    'len' => 3,
    'replace' => true,
  ),
  8 => 
  array (
    'symbol' => 'exp',
    'len' => 2,
    'replace' => true,
  ),
  9 => 
  array (
    'symbol' => 'exp',
    'len' => 1,
    'replace' => true,
  ),
  10 => 
  array (
    'symbol' => 'variable',
    'len' => 1,
    'replace' => true,
  ),
  11 => 
  array (
    'symbol' => 'variable',
    'len' => 3,
    'replace' => true,
  ),
  12 => 
  array (
    'symbol' => 'function',
    'len' => 3,
    'replace' => true,
  ),
  13 => 
  array (
    'symbol' => 'function',
    'len' => 4,
    'replace' => true,
  ),
  14 => 
  array (
    'symbol' => 'args',
    'len' => 1,
    'replace' => true,
  ),
  15 => 
  array (
    'symbol' => 'args',
    'len' => 3,
    'replace' => true,
  ),
  16 => 
  array (
    'symbol' => 'arithmetic',
    'len' => 3,
    'replace' => true,
  ),
  17 => 
  array (
    'symbol' => 'arithmetic',
    'len' => 3,
    'replace' => true,
  ),
  18 => 
  array (
    'symbol' => 'arithmetic',
    'len' => 3,
    'replace' => true,
  ),
  19 => 
  array (
    'symbol' => 'arithmetic',
    'len' => 3,
    'replace' => true,
  ),
  20 => 
  array (
    'symbol' => 'arithmetic',
    'len' => 3,
    'replace' => true,
  ),
  21 => 
  array (
    'symbol' => 'comparison',
    'len' => 3,
    'replace' => true,
  ),
  22 => 
  array (
    'symbol' => 'comparison',
    'len' => 3,
    'replace' => true,
  ),
  23 => 
  array (
    'symbol' => 'comparison',
    'len' => 3,
    'replace' => true,
  ),
  24 => 
  array (
    'symbol' => 'comparison',
    'len' => 3,
    'replace' => true,
  ),
  25 => 
  array (
    'symbol' => 'comparison',
    'len' => 3,
    'replace' => true,
  ),
  26 => 
  array (
    'symbol' => 'comparison',
    'len' => 3,
    'replace' => true,
  ),
  27 => 
  array (
    'symbol' => 'logical',
    'len' => 1,
    'replace' => true,
  ),
  28 => 
  array (
    'symbol' => 'logical',
    'len' => 1,
    'replace' => true,
  ),
  29 => 
  array (
    'symbol' => 'logical',
    'len' => 1,
    'replace' => true,
  ),
  30 => 
  array (
    'symbol' => '\'start\'',
    'len' => 1,
    'replace' => true,
  ),
);
}
