<?php
// French translation of Blog this!, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# index.php:62
$GLOBALS['__l10n']['send']='envoyer';

# index.php:68
$GLOBALS['__l10n']['You can add it to your bookmarks and when you will click "Blog this!" it will open up a popup window with the text you selected and a link to the site you\'re currently browsing so you can make a quick post about it.']='Vous pouvez ajouter le lien suivant à vos favoris. Quand vous cliquerez sur "Blog this!", une fenêtre s\'ouvrira avec le texte que vous avez sélectionné et un lien vers le site que vous visitez afin de commencer à écrire un billet à son propos.';

?>