<?php
// Français translation of Plugin Bootstrap, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:18
# index.php:75
# index.php:78
$GLOBALS['__l10n']['Plugin Bootstrap']='Amorçage d\'extension';

# class.dc.plugin.bootstrap.php:167
$GLOBALS['__l10n']['It seems that a %s plugin allready exists']='Il semblerait qu\'une extension %s existe déjà';

# class.dc.plugin.bootstrap.php:350
$GLOBALS['__l10n']['%s template file doesn\'t exists in %s directory']='Le fichier template %s n\'existe pas dans le répertoire %s';

# index.php:15
$GLOBALS['__l10n']['My new plugin']='Mon nouveau plugin';

# index.php:16
$GLOBALS['__l10n']['A plugin that does nothing yet.']='Un plugin qui ne fait rien pour le moment.';

# index.php:40
$GLOBALS['__l10n']['You must give a name for the plugin.']='Vous devez indiquer un nom pour l\'extension.';

# index.php:44
$GLOBALS['__l10n']['You must give a number version for the plugin.']='Vous devez indiquer un numéro de version pour l\'extension.';

# index.php:70
$GLOBALS['__l10n']['Other']='Autre';

# index.php:82
$GLOBALS['__l10n']['Plugin successfully bootstraped.']='Extension amorçée avec succès.';

# index.php:104
$GLOBALS['__l10n']['Options']='Options';

# index.php:110
$GLOBALS['__l10n']['With admin page']='Avec une page d\'administration';

# index.php:113
$GLOBALS['__l10n']['With public page']='Avec une page publique';

$GLOBALS['__l10n']['%s template file doesn\'t exists in %s directory']='Le fichier template %s n\'existe pas dans le répertoire %s';

?>