<?php
// French translation of Bloc-Notes, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:31
# index.php:50
# index.php:58
# lib.blocNotes.php:28
$GLOBALS['__l10n']['Bloc-notes']='Bloc-notes';

# index.php:44
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:64
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:67
$GLOBALS['__l10n']['Text']='Texte';

# index.php:72
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# lib.blocNotes.php:37
$GLOBALS['__l10n']['Bloc-notes :']='Bloc-notes :';

?>