<?php
// French translation of Bloc-Notes, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:28
# _admin.php:38
# index.php:47
# index.php:55
# lib.blocNotes.php:28
$GLOBALS['__l10n']['Notebook']='Bloc-notes';

# index.php:41
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:61
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:67
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# lib.blocNotes.php:38
$GLOBALS['__l10n']['Personal notebook (other users can&#39;t edit it) :']='Bloc-notes personnel (les autres utilisateurs ne peuvent pas le modifier) :';

# lib.blocNotes.php:45
$GLOBALS['__l10n']['Blog-specific notebook (all the users of the blog can edit it) :']='Bloc-notes spécifique à ce blog (tous les utilisateurs du blog peuvent le modifier) :';

# lib.blocNotes.php:51
$GLOBALS['__l10n']['These notes may be read by anyone, don&#39;t write some sensitive information (password, personal information, etc.)']='Ces notes pourraientt être lues par n\'importe qui, n\'écrivez pas d\'information sensible (mot de passe, information personnelle, etc.)';

?>