<?php
// French translation of Wiki Text Widget, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:8
$GLOBALS['__l10n']['Wiki Text']='Texte Wiki';

# _admin.php:10
$GLOBALS['__l10n']['optional']='facultatif';

# _admin.php:14
$GLOBALS['__l10n']['wiki syntax']='syntaxe wiki';

?>