<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~D</string>
	<key>name</key>
	<string>HTML (Dotclear)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.dotclear.value</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dotclear.tpl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.dotclear.any.value</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{\{(tpl):(.*)\}\})</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.dotclear.block.start</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dotclear.tpl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.dotclear.any.block</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(\&lt;(tpl):(.*)\&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.dotclear.block.end</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dotclear.tpl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.dotclear.any.block</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(\&lt;\/(tpl):(.*)\&gt;)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dotclear</string>
	<key>uuid</key>
	<string>791B177E-F8C6-491A-97D8-1A2DB9129D5C</string>
</dict>
</plist>
