<?php
// French translation of Subscribe to comments, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:26
# index.php:87
# index.php:229
# index.php:356
# index.php:365
# index.php:382
# index.php:519
# index.php:584
# lib.subscribeToComments.php:140
$GLOBALS['__l10n']['Subscribe to comments']='Abonnement aux commentaires';

# _public.php:86
# class.subscriber.php:147
$GLOBALS['__l10n']['Invalid post ID.']='Identifiant du billet invalide.';

# _public.php:267
$GLOBALS['__l10n']['Account informations sent']='Informations sur le compte envoyées';

# _public.php:268
$GLOBALS['__l10n']['Subscriptions removed']='Abonnements effacés';

# _public.php:269
$GLOBALS['__l10n']['Logged out']='Déconnecté';

# _public.php:270
$GLOBALS['__l10n']['Logged in']='Connecté';

# _public.php:271
$GLOBALS['__l10n']['Emails blocked']='Emails bloqués';

# _public.php:272
$GLOBALS['__l10n']['Emails allowed']='Emails autorisés';

# _public.php:273
$GLOBALS['__l10n']['An email has been sent to the new email address']='Un email a été envoyé à la nouvelle adresse email';

# _public.php:274
$GLOBALS['__l10n']['Email address changed']='Adresse email changée';

# _public.php:275
$GLOBALS['__l10n']['Account deleted']='Compte supprimé';

# _public.php:276
$GLOBALS['__l10n']['Subscribed to the entry']='Abonné au billet';

# class.subscriber.php:62
# class.subscriber.php:307
$GLOBALS['__l10n']['Invalid email address or key.']='Adresse email ou clé invalide.';

# class.subscriber.php:151
$GLOBALS['__l10n']['Invalid post.']='Billet invalide.';

# class.subscriber.php:195
# class.subscriber.php:466
$GLOBALS['__l10n']['This email address already exists.']='Cette adresse email existe déjà.';

# class.subscriber.php:461
# lib.subscribeToComments.php:54
$GLOBALS['__l10n']['Invalid key.']='Clé invalide.';

# class.subscriber.php:470
$GLOBALS['__l10n']['Link expired, request another email.']='Lien périmé, demandez un autre email.';

# index.php:83
$GLOBALS['__l10n']['Blog name']='Nom du blog';

# index.php:84
$GLOBALS['__l10n']['Blog URL']='URL du blog';

# index.php:85
# index.php:505
$GLOBALS['__l10n']['Email address']='Adresse email';

# index.php:87
$GLOBALS['__l10n']['%s&#39;s page URL']='URL de la page %s';

# index.php:91
# index.php:95
$GLOBALS['__l10n']['Post title']='Titre du billet';

# index.php:92
# index.php:96
$GLOBALS['__l10n']['Post URL']='URL du billet';

# index.php:97
$GLOBALS['__l10n']['URL to new comment']='URL vers le nouveau commentaire';

# index.php:98
$GLOBALS['__l10n']['Comment author']='Auteur du commentaire';

# index.php:99
$GLOBALS['__l10n']['Comment content']='Contenu du commentaire';

# index.php:103
$GLOBALS['__l10n']['New email address']='Nouvelle adresse email';

# index.php:105
$GLOBALS['__l10n']['URL to confirm the change of email address']='URL pour confirmer le changement d\'adresse email';

# index.php:228
$GLOBALS['__l10n']['Test email from your blog - %s']='Email test depuis votre blog - %s';

# index.php:229
$GLOBALS['__l10n']['% works.']='%s fonctionne.';

# index.php:241
# index.php:251
$GLOBALS['__l10n']['Destination file already exists.']='Le fichier de destination existe déjà.';

# index.php:257
$GLOBALS['__l10n']['No file to copy.']='Pas de fichier à copier.';

# index.php:274
$GLOBALS['__l10n']['No file to save.']='Pas de fichier à sauvegarder.';

# index.php:333
$GLOBALS['__l10n']['Test email sent.']='Email test envoyé.';

# index.php:337
$GLOBALS['__l10n']['File copied to theme directory.']='Fichier copié dans le répertoire du thème.';

# index.php:341
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:345
$GLOBALS['__l10n']['File succesfully saved.']='Fichier sauvegardé avec succés.';

# index.php:371
$GLOBALS['__l10n']['Error:']='Erreur:';

# index.php:372
$GLOBALS['__l10n']['Unable to find metadata plugin']='Impossible de trouver l\'extension metadata';

# index.php:376
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:382
$GLOBALS['__l10n']['Activate %s']='Activer %s';

# index.php:385
$GLOBALS['__l10n']['You can format the emails using the following tags.']='Vous pouvez formater les emails en utilisant les balises suivantes.';

# index.php:386
$GLOBALS['__l10n']['Each tag will be replaced by the associated value.']='Chaque balise sera remplacée par la valeur associée.';

# index.php:387
$GLOBALS['__l10n']['Tags available in all the contexts']='Balises disponibles dans tous les contextes';

# index.php:391
# index.php:425
# index.php:450
# index.php:475
$GLOBALS['__l10n']['Tag']='Balise';

# index.php:391
# index.php:425
# index.php:450
# index.php:475
$GLOBALS['__l10n']['Value']='Valeur';

# index.php:399
$GLOBALS['__l10n']['Email sent when an account is created or if a subscriber request it']='Email envoyé quand un compte est créé ou si un abonné le demande';

# index.php:401
# index.php:432
# index.php:457
# index.php:482
$GLOBALS['__l10n']['Subject']='Sujet';

# index.php:407
# index.php:438
# index.php:463
# index.php:488
$GLOBALS['__l10n']['Content']='Contenu';

# index.php:415
$GLOBALS['__l10n']['Email sent when a subscriber subscribe to the comments of a post']='Email envoyé quand un abonné s\'abonne aux commentaires d\'un billet';

# index.php:420
$GLOBALS['__l10n']['Send an email for each subscription to the comments of a post']='Envoyer un email pour chaque abonnement aux commentaires d\'un billet';

# index.php:422
# index.php:447
# index.php:472
$GLOBALS['__l10n']['Available tags']='Balises disponibles';

# index.php:446
$GLOBALS['__l10n']['Email sent when a new comment is published']='Email envoyé quand un nouveau commentaire est publié';

# index.php:471
$GLOBALS['__l10n']['Email sent when a subscriber want to change his email address']='Email envoyé quand un abonné veut changer d\'adresse email';

# index.php:496
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:503
$GLOBALS['__l10n']['Test']='Test';

# index.php:510
$GLOBALS['__l10n']['This will send a email, if you don&#39;t receive it, try to <a href="%s">change the way Dotclear send emails</a>.']='Ceci enverra un email, si vous ne le recevez pas, essayer de <a href="%s">changer la façon dont Dotclear envoie les emails</a>';

# index.php:513
$GLOBALS['__l10n']['Try to send an email']='Essayer d\'envoyer un email';

# index.php:516
$GLOBALS['__l10n']['Installation']='Installation';

# index.php:517
$GLOBALS['__l10n']['If this weblog is hosted by free.fr, create a <code>/sessions/</code> directory in the root directory of the website.']='Si ce blog est hébergé chez free.fr, créez un répertoire <code>/sessions/</code> dans le répertoire racine de ce site.';

# index.php:518
$GLOBALS['__l10n']['To add the checkbox <q>%1$s</q> to the form comment, edit the file <strong>post.html</strong> by clicking on the tab <strong>post.html</strong>.']='Pour ajouter la case à cocher <q>%1$s</q> au formulaire de commentaire, éditer le fichier <strong>post.html</strong> en cliquant sur l\'onglet <strong>post.html</strong>.';

# index.php:518
$GLOBALS['__l10n']['Receive following comments by email']='Recevoir les commentaires suivants par email';

# index.php:519
$GLOBALS['__l10n']['%s send notification emails to the subscribers of a post when :']='%s envoie des emails de notification aux abonnés d\'un billet quand :';

# index.php:521
$GLOBALS['__l10n']['a comment is posted on a post and published immediatly']='un commentaire est posté sur un billet et publié immédiatement';

# index.php:522
$GLOBALS['__l10n']['a comment is updated from the backend']='un commentaire est mis à jour depuis l\'interface d\'administration';

# index.php:523
$GLOBALS['__l10n']['a pending comment is published']='un commentaire en attente est publié à partir de l\'interface d\'administation';

# index.php:525
$GLOBALS['__l10n']['To send notification emails when you&#39;re publishing a comment from the backend, %1$s it twice, a message in the comment form show the status of the notification.']='Pour envoyer des emails de notification lors de la publication d\'un commentaire depuis l\'interface d\'administation, sauvegardez-le deux fois, un message dans le formulaire de commentaire montre le statut de la notification.';

# index.php:527
$GLOBALS['__l10n']['Inspired by <a href="%1$s">%1$s</a>']='Inspiré par <a href="%1$s">%1$s</a>';

# index.php:542
# index.php:569
$GLOBALS['__l10n']['Copy the file %s into the theme directory']='Copier le fichier %s dans le répertoire du thème';

# index.php:546
# index.php:591
$GLOBALS['__l10n']['Edit %s']='Éditer %s';

# index.php:552
# index.php:596
$GLOBALS['__l10n']['Save file']='Sauvegarder le fichier';

# index.php:573
$GLOBALS['__l10n']['Checkbox to subscribe to comments when posting a comment']='Case à cocher pour s\'abonner aux commentaires quand on poste un commentaire';

# index.php:574
$GLOBALS['__l10n']['Insert this in the comment form (suggestion : in the <code>&lt;fieldset&gt;</code> before the <code>&lt;/form&gt;</code> tag) :']='Insérer ceci dans le formulaire de commentaire (suggestion : dans le <code>&lt;fieldset&gt;</code> avant la balise <code>&lt;/form&gt;</code>) :';

# index.php:579
$GLOBALS['__l10n']['If the blog use the default theme, add this at the end of the CSS file of the theme (usually style.css) :']='Si le blog utilise le thème par défaut, ajoutez ceci à la fin du fichiers CSS du thème (généralement style.css) :';

# index.php:584
$GLOBALS['__l10n']['Link to the %s page']='Lien vers la page %s';

# index.php:585
$GLOBALS['__l10n']['Insert this anywhere on the page (suggestion : just after the <code>&lt;/form&gt;</code> tag) :']='Insérer ceci n\'importe où dans la page (suggestion : juste après la balise <code>&lt;/form&gt;</code>) :';

# lib.subscribeToComments.php:41
$GLOBALS['__l10n']['Invalid email address.']='Adresse email invalide.';

# lib.subscribeToComments.php:134
$GLOBALS['__l10n']['<img src="images/check-off.png" alt="%1$s" title="%1$s" /> Notification email not sent, click on <strong>%2$s</strong>.']='<img src="images/check-off.png" alt="%1$s" title="%1$s" /> Email de notification non envoyé, cliquez sur <strong>%2$s</strong>.';

# lib.subscribeToComments.php:134
$GLOBALS['__l10n']['not sent']='pas envoyé';

# lib.subscribeToComments.php:138
$GLOBALS['__l10n']['<img src="images/check-on.png" alt="%1$s" title="%1$s" /> Notification email sent.']='<img src="images/check-on.png" alt="%1$s" title="%1$s" /> Email de notification envoyé.';

# lib.subscribeToComments.php:138
$GLOBALS['__l10n']['sent']='envoyé';

?>