<?php
// Français translation of Subscribe to comments, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:26
# _public.php:485
# index.php:78
# index.php:239
# index.php:330
# index.php:361
# index.php:378
# index.php:505
# index.php:543
# index.php:563
# lib.subscribeToComments.php:163
$GLOBALS['__l10n']['Subscribe to comments']='Abonnement aux commentaires';

# _public.php:86
# class.subscriber.php:147
$GLOBALS['__l10n']['Invalid post ID.']='Identifiant du billet invalide.';

# _public.php:274
$GLOBALS['__l10n']['Account informations sent']='Informations sur le compte envoyées';

# _public.php:275
$GLOBALS['__l10n']['Subscriptions removed']='Abonnements effacés';

# _public.php:276
$GLOBALS['__l10n']['Logged out']='Déconnecté';

# _public.php:277
# _public.php:449
$GLOBALS['__l10n']['Logged in']='Connecté';

# _public.php:278
$GLOBALS['__l10n']['Emails blocked']='Emails bloqués';

# _public.php:279
$GLOBALS['__l10n']['Emails allowed']='Emails autorisés';

# _public.php:280
$GLOBALS['__l10n']['An email has been sent to the new email address']='Un email a été envoyé à la nouvelle adresse email';

# _public.php:281
$GLOBALS['__l10n']['Email address changed']='Adresse email changée';

# _public.php:282
$GLOBALS['__l10n']['Account deleted']='Compte supprimé';

# _public.php:283
$GLOBALS['__l10n']['Subscribed to the entry']='Abonné au billet';

# _public.php:456
# index.php:511
# index.php:527
$GLOBALS['__l10n']['Receive following comments by email']='Recevoir les commentaires suivants par email';

# class.subscriber.php:62
# class.subscriber.php:307
$GLOBALS['__l10n']['Invalid email address or key.']='Adresse email ou clé invalide.';

# class.subscriber.php:151
$GLOBALS['__l10n']['Invalid post.']='Billet invalide.';

# class.subscriber.php:195
# class.subscriber.php:466
$GLOBALS['__l10n']['This email address already exists.']='Cette adresse email existe déjà.';

# class.subscriber.php:461
# lib.subscribeToComments.php:54
$GLOBALS['__l10n']['Invalid key.']='Clé invalide.';

# class.subscriber.php:470
$GLOBALS['__l10n']['Link expired, request another email.']='Lien périmé, demandez un autre email.';

# index.php:75
$GLOBALS['__l10n']['Blog URL']='URL du blog';

# index.php:76
# index.php:574
$GLOBALS['__l10n']['Email address']='Adresse email';

# index.php:78
$GLOBALS['__l10n']['%s&#39;s page URL']='URL de la page %s';

# index.php:82
# index.php:86
$GLOBALS['__l10n']['Post title']='Titre du billet';

# index.php:83
# index.php:87
$GLOBALS['__l10n']['Post URL']='URL du billet';

# index.php:88
$GLOBALS['__l10n']['URL to new comment']='URL vers le nouveau commentaire';

# index.php:89
$GLOBALS['__l10n']['Comment author']='Auteur du commentaire';

# index.php:90
$GLOBALS['__l10n']['Comment content']='Contenu du commentaire';

# index.php:94
$GLOBALS['__l10n']['New email address']='Nouvelle adresse email';

# index.php:96
$GLOBALS['__l10n']['URL to confirm the change of email address']='URL pour confirmer le changement d\'adresse email';

# index.php:238
$GLOBALS['__l10n']['Test email from your blog - %s']='Email test depuis votre blog - %s';

# index.php:239
$GLOBALS['__l10n']['The plugin % works.']='Le plugin %s fonctionne.';

# index.php:315
$GLOBALS['__l10n']['Test email sent.']='Email test envoyé.';

# index.php:319
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:367
$GLOBALS['__l10n']['Error:']='Erreur:';

# index.php:368
$GLOBALS['__l10n']['Unable to find metadata plugin']='Impossible de trouver l\'extension metadata';

# index.php:378
$GLOBALS['__l10n']['Activate %s']='Activer %s';

# index.php:382
$GLOBALS['__l10n']['You can format the emails using the following tags.']='Vous pouvez formater les emails en utilisant les balises suivantes.';

# index.php:383
$GLOBALS['__l10n']['Each tag will be replaced by the associated value.']='Chaque balise sera remplacée par la valeur associée.';

# index.php:384
$GLOBALS['__l10n']['Tags available in all the contexts']='Balises disponibles dans tous les contextes';

# index.php:388
# index.php:422
# index.php:447
# index.php:472
$GLOBALS['__l10n']['Tag']='Balise';

# index.php:388
# index.php:422
# index.php:447
# index.php:472
$GLOBALS['__l10n']['Value']='Valeur';

# index.php:396
$GLOBALS['__l10n']['Email sent when an account is created or if a subscriber request it']='Email envoyé quand un compte est créé ou si un abonné le demande';

# index.php:398
# index.php:429
# index.php:454
# index.php:479
$GLOBALS['__l10n']['Subject']='Sujet';

# index.php:404
# index.php:435
# index.php:460
# index.php:485
$GLOBALS['__l10n']['Content']='Contenu';

# index.php:412
$GLOBALS['__l10n']['Email sent when a subscriber subscribe to the comments of a post']='Email envoyé quand un abonné s\'abonne aux commentaires d\'un billet';

# index.php:417
$GLOBALS['__l10n']['Send an email for each subscription to the comments of a post']='Envoyer un email pour chaque abonnement aux commentaires d\'un billet';

# index.php:419
# index.php:444
# index.php:469
$GLOBALS['__l10n']['Available tags']='Balises disponibles';

# index.php:443
$GLOBALS['__l10n']['Email sent when a new comment is published']='Email envoyé quand un nouveau commentaire est publié';

# index.php:468
$GLOBALS['__l10n']['Email sent when a subscriber want to change his email address']='Email envoyé quand un abonné veut changer d\'adresse email';

# index.php:493
# index.php:556
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:497
# index.php:498
$GLOBALS['__l10n']['Display']='Affichage';

# index.php:499
$GLOBALS['__l10n']['If you want to customize the display on the post page, uncheck the following checbboxes and follow the instructions under each checkbox :']='Si vous voulez modifier l\'affichage sur la page du billet, décochez les cases suivantes et suivez les instructions sous chaque case à cocher :';

# index.php:500
$GLOBALS['__l10n']['You can use the plugin <strong>%s</strong> to edit the file <strong>post.html</strong>.']='Vous pousez utiliser le plugin <strong>%s</strong> pour éditer le fichier <strong>post.html</strong>.';

# index.php:504
$GLOBALS['__l10n']['Install %s on the post page.']='Installer %s sur la page du billet.';

# index.php:510
$GLOBALS['__l10n']['To add the %s checkbox in the comment form, check this']='Pour ajouter la case à cocher %s dans le formulaire de commentaire, cochez ceci';

# index.php:515
# index.php:531
# index.php:547
$GLOBALS['__l10n']['or']='ou';

# index.php:516
$GLOBALS['__l10n']['insert this in the comment form (suggestion : in the <code>&lt;fieldset&gt;</code> before the <code>&lt;/form&gt;</code> tag) :']='insérez ceci dans le formulaire de commentaire (suggestion : dans le <code>&lt;fieldset&gt;</code> avant la balise <code>&lt;/form&gt;</code>) :';

# index.php:526
$GLOBALS['__l10n']['If the %1$s checkbox is not displayed correctly and the blog use Blowup or Blue Silence theme, check this']='Si le blog utilise le thème par défaut, ajoutez ceci à la fin du fichiers CSS du thème (généralement style.css) :';

# index.php:532
$GLOBALS['__l10n']['add this CSS rule at the end of the file <strong>style.css</strong>']='ajoutez cette règle CSS à la fin du fichier <strong>style.css</strong>';

# index.php:542
$GLOBALS['__l10n']['To add a link to the %1$s page between the comments and the trackbacks, check this']='Pour ajouter un lien vers la page %1$s entre les commentaires et les rétroliens, cochez ceci';

# index.php:548
$GLOBALS['__l10n']['insert this anywhere on the page (suggestion : just after the <code>&lt;/form&gt;</code> tag) :']='insérez ceci n\'importe où dans la page (suggestion : juste après la balise <code>&lt;/form&gt;</code>) :';

# index.php:563
$GLOBALS['__l10n']['%s send notification emails to the subscribers of a post when :']='%s envoie des emails de notification aux abonnés d\'un billet quand :';

# index.php:565
$GLOBALS['__l10n']['a comment is posted and published immediatly']='un commentaire est posté et publié immédiatement';

# index.php:566
$GLOBALS['__l10n']['a pending comment is published']='un commentaire en attente est publié à partir de l\'interface d\'administation';

# index.php:568
$GLOBALS['__l10n']['If this weblog is hosted by free.fr, create a <code>/sessions/</code> directory in the root directory of the website.']='Si ce blog est hébergé chez free.fr, créez un répertoire <code>/sessions/</code> dans le répertoire racine de ce site.';

# index.php:569
$GLOBALS['__l10n']['To use this plugin, you have to test if the server can send emails :']='Pour utiliser ce plugin, vous devez tester si le serveur peut envoyer des emails :';

# index.php:572
$GLOBALS['__l10n']['Test']='Test';

# index.php:579
$GLOBALS['__l10n']['This will send a email, if you don&#39;t receive it, try to <a href="%s">change the way Dotclear send emails</a>.']='Ceci enverra un email, si vous ne le recevez pas, essayer de <a href="%s">changer la façon dont Dotclear envoie les emails</a>';

# index.php:582
$GLOBALS['__l10n']['Try to send an email']='Essayer d\'envoyer un email';

# index.php:586
$GLOBALS['__l10n']['Inspired by <a href="%1$s">%2$s</a>']='Inspiré par <a href="%1$s">%2$s</a>';

# lib.subscribeToComments.php:41
$GLOBALS['__l10n']['Invalid email address.']='Adresse email invalide.';

# lib.subscribeToComments.php:157
$GLOBALS['__l10n']['<img src="images/check-off.png" alt="%1$s" title="%1$s" /> Notification email not sent, click on <strong>%2$s</strong>.']='<img src="images/check-off.png" alt="%1$s" title="%1$s" /> Email de notification non envoyé, cliquez sur <strong>%2$s</strong>.';

# lib.subscribeToComments.php:157
$GLOBALS['__l10n']['not sent']='pas envoyé';

# lib.subscribeToComments.php:161
$GLOBALS['__l10n']['<img src="images/check-on.png" alt="%1$s" title="%1$s" /> Notification email sent.']='<img src="images/check-on.png" alt="%1$s" title="%1$s" /> Email de notification envoyé.';

# lib.subscribeToComments.php:161
$GLOBALS['__l10n']['sent']='envoyé';

?>