<?php
// French translation of Subscribe to comments, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:26
# index.php:76
# index.php:243
# index.php:369
# index.php:378
# index.php:395
# index.php:531
# index.php:589
$GLOBALS['__l10n']['Subscribe to comments']='Abonnement aux commentaires';

# _public.php:86
# class.subscriber.php:146
$GLOBALS['__l10n']['Invalid post ID.']='Idenfifiant du billet invalide.';

# _public.php:267
$GLOBALS['__l10n']['Account informations sent']='Informations sur le compte envoyées';

# _public.php:268
$GLOBALS['__l10n']['Subscriptions removed']='Abonnements effacés';

# _public.php:269
$GLOBALS['__l10n']['Logged out']='Déconnecté';

# _public.php:270
$GLOBALS['__l10n']['Logged in']='Connecté';

# _public.php:271
$GLOBALS['__l10n']['Emails blocked']='Emails bloqués';

# _public.php:272
$GLOBALS['__l10n']['Emails allowed']='Emails autorisés';

# _public.php:273
$GLOBALS['__l10n']['An email has been sent to the new email address']='Un email a été envoyé à la nouvelle adresse email';

# _public.php:274
$GLOBALS['__l10n']['Email address changed']='Adresse email changée';

# _public.php:275
$GLOBALS['__l10n']['Account deleted']='Compte supprimé';

# _public.php:276
$GLOBALS['__l10n']['Subscribed to the entry']='Abonné au billet';

# class.subscriber.php:62
# class.subscriber.php:306
$GLOBALS['__l10n']['Invalid email address or key.']='Adresse email ou clé invalide.';

# class.subscriber.php:150
$GLOBALS['__l10n']['Invalid post.']='Billet invalide.';

# class.subscriber.php:194
# class.subscriber.php:465
$GLOBALS['__l10n']['This email address already exists.']='Cette adresse email existe déjà.';

# class.subscriber.php:460
# lib.subscribeToComments.php:54
$GLOBALS['__l10n']['Invalid key.']='Clé invalide.';

# class.subscriber.php:469
$GLOBALS['__l10n']['Link expired, request another email.']='Lien périmé, demandez un autre email.';

# index.php:72
$GLOBALS['__l10n']['Blog name']='Nom du blog';

# index.php:73
$GLOBALS['__l10n']['Blog URL']='URL du blog';

# index.php:74
# index.php:518
$GLOBALS['__l10n']['Email address']='Adresse email';

# index.php:76
$GLOBALS['__l10n']['%s&#39;s page URL']='URL de la page %s';

# index.php:80
# index.php:84
$GLOBALS['__l10n']['Post title']='Titre du billet';

# index.php:81
# index.php:85
$GLOBALS['__l10n']['Post URL']='URL du billet';

# index.php:86
$GLOBALS['__l10n']['URL to new comment']='URL vers le nouveau commentaire';

# index.php:87
$GLOBALS['__l10n']['Comment author']='Auteur du commentaire';

# index.php:88
$GLOBALS['__l10n']['Comment content']='Contenu du commentaire';

# index.php:92
$GLOBALS['__l10n']['New email address']='Nouvelle adresse email';

# index.php:94
$GLOBALS['__l10n']['URL to confirm the change of email address']='URL pour confirmer le changement d\'adresse email';

# index.php:242
$GLOBALS['__l10n']['Test email from your blog - %s']='Email test depuis votre blog - %s';

# index.php:243
$GLOBALS['__l10n']['% works \o/']='%s fonctionne \o/';

# index.php:254
# index.php:264
$GLOBALS['__l10n']['Destination file already exists.']='Le fichier de destination existe déjà.';

# index.php:270
$GLOBALS['__l10n']['No file to copy.']='Pas de fichier à copier.';

# index.php:287
$GLOBALS['__l10n']['No file to save.']='Pas de fichier à sauvegarder.';

# index.php:346
$GLOBALS['__l10n']['Test email sent.']='Email test envoyé.';

# index.php:350
$GLOBALS['__l10n']['File copied to theme directory.']='Fichier copié dans le répertoire du thème.';

# index.php:354
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:358
$GLOBALS['__l10n']['File succesfully saved.']='Fichier sauvegardé avec succés.';

# index.php:384
$GLOBALS['__l10n']['Error:']='Erreur:';

# index.php:385
$GLOBALS['__l10n']['Unable to find metadata plugin']='Impossible de trouver l\'extension metadata';

# index.php:389
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:395
$GLOBALS['__l10n']['Activate %s']='Activer %s';

# index.php:398
$GLOBALS['__l10n']['You can format the emails using the following tags.']='Vous pouvez formater les emails en utilisant les balises suivantes.';

# index.php:399
$GLOBALS['__l10n']['Each tag will be replaced by the associated value.']='Chaque balise sera remplacée par la valeur associée.';

# index.php:400
$GLOBALS['__l10n']['Tags available in all the contexts']='Balises disponibles dans tous les contextes';

# index.php:404
# index.php:438
# index.php:463
# index.php:488
$GLOBALS['__l10n']['Tag']='Balise';

# index.php:404
# index.php:438
# index.php:463
# index.php:488
$GLOBALS['__l10n']['Value']='Valeur';

# index.php:412
$GLOBALS['__l10n']['Email sent when an account is created or if a subscriber request it']='Email envoyé quand un compte est créé ou si un abonné le demande';

# index.php:414
# index.php:445
# index.php:470
# index.php:495
$GLOBALS['__l10n']['Subject']='Sujet';

# index.php:420
# index.php:451
# index.php:476
# index.php:501
$GLOBALS['__l10n']['Content']='Contenu';

# index.php:428
$GLOBALS['__l10n']['Email sent when a subscriber subscribe to the comments of a post']='Email envoyé quand un abonné s\'abonne aux commentaires d\'un billet';

# index.php:433
$GLOBALS['__l10n']['Send an email for each subscription']='Envoyer un email pour chaque abonnement';

# index.php:435
# index.php:460
# index.php:485
$GLOBALS['__l10n']['Available tags']='Balises disponibles';

# index.php:459
$GLOBALS['__l10n']['Email sent when a new comment is published']='Email envoyé quand un nouveau commentaire est publié';

# index.php:484
$GLOBALS['__l10n']['Email sent when a subscriber want to change his email address']='Email envoyé quand un abonné veut changer d\'adresse email';

# index.php:509
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:516
$GLOBALS['__l10n']['Test']='Test';

# index.php:523
$GLOBALS['__l10n']['This will send a email, if you don&#39;t receive it, try to <a href="%s">change the way Dotclear send emails</a>.']='Ceci enverra un email, si vous ne le recevez pas, essayer de <a href="%s">changer la façon dont Dotclear envoie les emails</a>';

# index.php:526
$GLOBALS['__l10n']['Try to send an email']='Essayer d\'envoyer un email';

# index.php:529
$GLOBALS['__l10n']['Installation']='Installation';

# index.php:530
$GLOBALS['__l10n']['To use this plugin, edit the file <strong>post.html</strong> by clicking on the tab <strong>post.html</strong>.']='Pour utiliser cette extension, éditer le fichier <strong>post.html</strong> en cliquant sur l\'onglet <strong>post.html</strong>.';

# index.php:531
$GLOBALS['__l10n']['%s send emails to the subscribers of a post when :']='%s envoie des emails aux abonnés d\'un billet quand :';

# index.php:533
$GLOBALS['__l10n']['a comment is posted on a post and published immediatly']='un commentaire est posté sur un billet et publié immédiatement';

# index.php:534
$GLOBALS['__l10n']['publishing a pending comment from the administration backend']='un commentaire en attente est publié à partir de l\'interface d\'administation';

# index.php:537
$GLOBALS['__l10n']['Inspired by <a href="%1$s">%1$s</a>']='Inspiré par <a href="%1$s">%1$s</a>';

# index.php:552
# index.php:579
$GLOBALS['__l10n']['Copy the file %s into the theme directory']='Copier le fichier %s dans le répertoire du thème';

# index.php:556
# index.php:596
$GLOBALS['__l10n']['Edit %s']='Éditer %s';

# index.php:562
# index.php:601
$GLOBALS['__l10n']['Save file']='Sauvegarder le fichier';

# index.php:583
$GLOBALS['__l10n']['Checkbox to subscribe to comments when posting a comment']='Case à cocher pour s\'abonner aux commentaires quand on poste un commentaire';

# index.php:584
$GLOBALS['__l10n']['Insert this in the comment form (suggestion : in the <code>&lt;fieldset&gt;</code> before the <code>&lt;/form&gt;</code> tag) :']='Insérer ceci dans le formulaire de commentaire (suggestion : dans le <code>&lt;fieldset&gt;</code> avant la balise <code>&lt;/form&gt;</code>) :';

# index.php:589
$GLOBALS['__l10n']['Link to the %s page']='Lien vers la page %s';

# index.php:590
$GLOBALS['__l10n']['Insert this anywhere on the page (suggestion : just after the <code>&lt;/form&gt;</code> tag) :']='Insérer ceci n\'importe où dans la page (suggestion : juste après la balise <code>&lt;/form&gt;</code>) :';

# lib.subscribeToComments.php:41
$GLOBALS['__l10n']['Invalid email address.']='Adresse email invalide.';

?>