<?php
// French translation of Gallery, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:27
# _public.php:394
# _widgets.php:31
# gal.php:440
# gals.php:55
# gals.php:62
# gals.php:64
# gals_actions.php:146
# item.php:331
# item.php:352
# items.php:287
# newitems.php:71
$GLOBALS['__l10n']['Galleries']='Galeries';

# _admin.php:33
$GLOBALS['__l10n']['%d galleries']='%d galeries';

# _admin.php:33
$GLOBALS['__l10n']['%d gallery']='%d galerie';

# _public.php:123
# _public.php:431
$GLOBALS['__l10n']['No category']='Sans catégorie';

# _public.php:469
$GLOBALS['__l10n']['Random Image']='Image aléatoire';

# _public.php:492
# _widgets.php:46
$GLOBALS['__l10n']['Last images']='Dernières images';

# _widgets.php:34
$GLOBALS['__l10n']['Display mode']='Affichage';

# _widgets.php:35
$GLOBALS['__l10n']['Galleries only']='Galeries seulement';

# _widgets.php:35
$GLOBALS['__l10n']['Categories only']='Catégories seulement';

# _widgets.php:35
$GLOBALS['__l10n']['Both']='Galeries et catégories';

# _widgets.php:36
$GLOBALS['__l10n']['Order by']='Trier par';

# _widgets.php:37
$GLOBALS['__l10n']['Gallery name']='Nom de galerie';

# _widgets.php:37
$GLOBALS['__l10n']['Gallery date']='Date de galerie';

# _widgets.php:42
$GLOBALS['__l10n']['Random image']='Image aléatoire';

# class.dc.gallery.php:39
$GLOBALS['__l10n']['Filename']='Nom du fichier';

# class.dc.gallerylists.php:44
# gal.php:441
# gal.php:474
# gals.php:106
# item.php:332
# items.php:288
# newitems.php:72
$GLOBALS['__l10n']['Images']='Images';

# class.dc.gallerylists.php:147
$GLOBALS['__l10n']['Thumb']='Miniature';

# gal.php:48
# gals.php:66
$GLOBALS['__l10n']['New gallery']='Nouvelle galerie';

# gal.php:179
$GLOBALS['__l10n']['Edit gallery']='Modifier la galerie';

# gal.php:188
$GLOBALS['__l10n']['next gallery']='galerie suivante';

# gal.php:196
$GLOBALS['__l10n']['previous gallery']='galerie précédente';

# gal.php:430
# gal.php:432
$GLOBALS['__l10n']['view gallery']='voir la galerie';

# gal.php:442
# items.php:374
$GLOBALS['__l10n']['Gallery']='Galerie';

# gal.php:448
$GLOBALS['__l10n']['Presentation thumbnail']='Miniature de présentation';

# gal.php:459
$GLOBALS['__l10n']['Change']='Changer';

# gal.php:461
# gal.php:462
$GLOBALS['__l10n']['Remove']='Enlever';

# gal.php:468
$GLOBALS['__l10n']['This gallery has no presentation thumbnail']='Cette galerie n\'a pas de miniature de présentation';

# gal.php:469
$GLOBALS['__l10n']['Define one']='En définir une';

# gal.php:471
$GLOBALS['__l10n']['This gallery has %d images']='Cette galerie possède %d images';

# gal.php:471
$GLOBALS['__l10n']['This gallery has %d image']='Cette galerie possède %d image';

# gal.php:494
# item.php:379
$GLOBALS['__l10n']['Gallery status:']='Etat de la galerie';

# gal.php:539
$GLOBALS['__l10n']['Settings']='Paramètres';

# gal.php:543
$GLOBALS['__l10n']['Select below the image filters you wish to set for this gallery (at least 1 must be selected)']='Sélectionnez ci-dessous les filtres que vous voulez mettre pour cette galerie (il faut en sélectionner au moins un)';

# gal.php:545
$GLOBALS['__l10n']['Media dir']='Répertoire de media';

# gal.php:551
$GLOBALS['__l10n']['User']='Utilisateur';

# gal.php:556
$GLOBALS['__l10n']['Sort']='Tri';

# gal.php:605
# gals.php:107
# item.php:458
# items.php:409
# newitems.php:73
$GLOBALS['__l10n']['Manage new items']='Gestion des nouvelles images';

# gals.php:62
$GLOBALS['__l10n']['Main menu']='Menu principal';

# galthumbnail.php:42
$GLOBALS['__l10n']['This gallery does not exits']='Cette galerie n\'existe pas';

# galthumbnail.php:97
$GLOBALS['__l10n']['Choose a media to attach to gallery %s by clicking on %s.']='Choisissez un media à attacher à la galerie %s, en cliquant sur %s.';

# item.php:128
$GLOBALS['__l10n']['Edit image']='Editer l\'image';

# item.php:138
$GLOBALS['__l10n']['next item']='image suivante';

# item.php:146
$GLOBALS['__l10n']['previous item']='image précédente';

# item.php:307
# item.php:309
$GLOBALS['__l10n']['view item']='voir l\'image';

# item.php:333
$GLOBALS['__l10n']['Image']='Image';

# item.php:340
$GLOBALS['__l10n']['Sizes']='Tailles';

# item.php:341
$GLOBALS['__l10n']['This image is available with sizes :']='Cette image est disponibles dans les tailles :';

# item.php:348
$GLOBALS['__l10n']['This image belongs to %d galleries']='Cette image appartient à %d galeries';

# item.php:348
$GLOBALS['__l10n']['This image belongs to %d gallery']='Cette image appartient à %d galerie';

# items.php:171
$GLOBALS['__l10n']['Remove image-post']='Supprimer le billet associé';

# items.php:269
# newitems.php:45
$GLOBALS['__l10n']['Gallery Items']='Images';

# items.php:278
$GLOBALS['__l10n']['Show / Hide thumbnails']='Montrer / Cacher les miniatures';

# items.php:302
$GLOBALS['__l10n']['Gallery:']='Galerie';

# items.php:305
# newitems.php:77
$GLOBALS['__l10n']['Media dir:']='Répertoire contenant les media';

# items.php:311
$GLOBALS['__l10n']['Tag:']='Tag:';

# items.php:369
$GLOBALS['__l10n']['Gallery content']='Contenu de la galerie';

# items.php:371
$GLOBALS['__l10n']['filtered']='filtrée';

# newitems.php:52
$GLOBALS['__l10n']['Waiting...']='En attente...';

# newitems.php:53
$GLOBALS['__l10n']['%s entries found']='%s entrées trouvées';

# newitems.php:54
$GLOBALS['__l10n']['Create media']='Création du media';

# newitems.php:55
$GLOBALS['__l10n']['Create post for media']='Création du billet pour le media';

# newitems.php:56
$GLOBALS['__l10n']['Refresh gallery']='Rafraîchissement de la galerie';

# newitems.php:57
# newitems.php:80
$GLOBALS['__l10n']['Delete orphan media']='Supprimer les media orphelins';

# newitems.php:58
$GLOBALS['__l10n']['Delete orphan items']='Suppression des images orphelines';

# newitems.php:59
$GLOBALS['__l10n']['Fetch new media']='Recherche des nouveaux media';

# newitems.php:60
$GLOBALS['__l10n']['Fetch media without post']='Recherche des media sans billet associé';

# newitems.php:61
$GLOBALS['__l10n']['Retrieve galleries']='Récupération des galeries';

# newitems.php:62
$GLOBALS['__l10n']['Whole blog']='Tout le blog';

# newitems.php:76
$GLOBALS['__l10n']['New Items']='Nouvelles images';

# newitems.php:82
$GLOBALS['__l10n']['Delete orphan image-posts']='Supprimer les billets-images orphelins';

# newitems.php:84
$GLOBALS['__l10n']['Scan dir for new media']='Rechercher les nouveaux media dans le répertoire';

# newitems.php:86
$GLOBALS['__l10n']['Create image-posts for media in dir']='Créer les billets-images pour les media dans le dossier';

# newitems.php:87
$GLOBALS['__l10n']['proceed']='Soumettre';

# newitems.php:90
$GLOBALS['__l10n']['Gallery mass update']='Mise à jour en masse des galeries';

# newitems.php:91
$GLOBALS['__l10n']['Update all galeries']='Mettre à jour toutes les galeries';

# newitems.php:94
$GLOBALS['__l10n']['Processing result']='Résultat du traitement';

# newitems.php:96
$GLOBALS['__l10n']['Requests']='Requêtes';

# newitems.php:98
$GLOBALS['__l10n']['Actions']='Actions';

$GLOBALS['__l10n']['Thumbnail']='Miniature';

$GLOBALS['__l10n']['Maintenance']='Maintenance';

$GLOBALS['__l10n']['next images']='images suivantes';

$GLOBALS['__l10n']['previous images']='images précédentes';

?>