<?php
// French translation of Gallery, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:25
# _public.php:283
# _widgets.php:31
# gals.php:53
# gals.php:60
# gals.php:62
# gals_actions.php:145
# item.php:354
# items.php:293
# newitems.php:56
$GLOBALS['__l10n']['Galleries']='Galeries';

# _widgets.php:34
$GLOBALS['__l10n']['Display mode']='Affichage';

# _widgets.php:35
$GLOBALS['__l10n']['Galleries only']='Galeries seulement';

# _widgets.php:35
$GLOBALS['__l10n']['Categories only']='Catégories seulement';

# _widgets.php:35
$GLOBALS['__l10n']['Both']='Galeries et catégories';

# _widgets.php:36
$GLOBALS['__l10n']['Order by']='Trier par';

# _widgets.php:37
$GLOBALS['__l10n']['Gallery name']='Nom de galerie';

# _widgets.php:37
$GLOBALS['__l10n']['Gallery date']='Date de galerie';

# class.dc.gallery.php:38
$GLOBALS['__l10n']['Filename']='Nom du fichier';

# class.dc.gallerylists.php:44
# gals.php:102
# items.php:294
# newitems.php:57
$GLOBALS['__l10n']['Images']='Images';

# class.dc.gallerylists.php:147
$GLOBALS['__l10n']['Thumb']='Miniature';

# gal.php:49
# gals.php:64
$GLOBALS['__l10n']['New gallery']='Nouvelle galerie';

# gal.php:143
$GLOBALS['__l10n']['Edit gallery']='Modifier la galerie';

# gal.php:152
# item.php:137
$GLOBALS['__l10n']['next gallery']='galerie suivante';

# gal.php:160
# item.php:145
$GLOBALS['__l10n']['previous gallery']='galerie précédente';

# gal.php:378
# gal.php:380
$GLOBALS['__l10n']['view gallery']='voir la galerie';

# gal.php:394
# items.php:379
$GLOBALS['__l10n']['Gallery']='Galerie';

# gal.php:398
$GLOBALS['__l10n']['Thumbnail']='Miniature';

# gal.php:421
$GLOBALS['__l10n']['Change thumbnail']='Changer la miniature';

# gal.php:423
$GLOBALS['__l10n']['Set a thumbnail for this gallery']='Sélectionner une miniature pour cette galerie';

# gal.php:431
# item.php:385
$GLOBALS['__l10n']['Gallery status:']='Etat de la galerie';

# gal.php:477
$GLOBALS['__l10n']['Media Directory:']='Répertoire contenant les media';

# gals.php:60
$GLOBALS['__l10n']['Main menu']='Menu principal';

# gals.php:103
# items.php:414
# newitems.php:58
$GLOBALS['__l10n']['Manage new items']='Gestion des nouvelles images';

# item.php:128
$GLOBALS['__l10n']['Edit image']='Editer l\'image';

# item.php:349
$GLOBALS['__l10n']['Image']='Image';

# item.php:360
$GLOBALS['__l10n']['Detach from this gallery']='Détacher de la galerie en cours';

# item.php:367
$GLOBALS['__l10n']['Sizes available']='Tailles disponibles';

# items.php:175
$GLOBALS['__l10n']['Add to gallery ...']='Ajouter à la galerie ...';

# items.php:177
$GLOBALS['__l10n']['remove from current gallery']='Enlever de la galerie courante';

# items.php:178
$GLOBALS['__l10n']['Remove image-post']='Supprimer le billet associé';

# items.php:275
# newitems.php:46
$GLOBALS['__l10n']['Gallery Items']='Images';

# items.php:284
$GLOBALS['__l10n']['Show / Hide thumbnails']='Montrer / Cacher les miniatures';

# items.php:308
# items_actions.php:291
$GLOBALS['__l10n']['Gallery:']='Galerie';

# items.php:311
# newitems.php:67
$GLOBALS['__l10n']['Media dir:']='Répertoire contenant les media';

# items.php:320
$GLOBALS['__l10n']['Tag:']='Tag:';

# items.php:374
$GLOBALS['__l10n']['Gallery content']='Contenu de la galerie';

# items.php:376
$GLOBALS['__l10n']['filtered']='filtrée';

# items_actions.php:287
$GLOBALS['__l10n']['Add gallery for entries']='Ajouter la galerie pour les images';

# newitems.php:66
$GLOBALS['__l10n']['New Items']='Nouvelles images';

# newitems.php:70
$GLOBALS['__l10n']['Scan dir for new media']='Rechercher les nouveaux media dans le répertoire';

# newitems.php:72
$GLOBALS['__l10n']['Create image-posts for media in dir']='Créer les billets-images pour les media dans le dossier';

# newitems.php:73
$GLOBALS['__l10n']['Update galeries configured for this dir']='Mettre à jour les galeries configurées pour ce répertoire';

# newitems.php:75
$GLOBALS['__l10n']['proceed']='Soumettre';

# newitems.php:78
$GLOBALS['__l10n']['Processing result']='Résultat du traitement';

$GLOBALS['__l10n']['Items']='Eléments';

$GLOBALS['__l10n']['Maintenance']='Maintenance';

$GLOBALS['__l10n']['Operations performed :']='Opérations effectuées :';

$GLOBALS['__l10n']['Operation performed']='Opération effectuée :';

$GLOBALS['__l10n']['Add image linked to media, add image to gallery']='Ajout d\'un billet attaché à l\'image, ajout de l\'image à la galerie';

$GLOBALS['__l10n']['Add image to gallery']='Ajout de l\'image à la galerie';

$GLOBALS['__l10n']['Create thumb']='Création de la miniature';

?>