<?php
// French translation of Gallery, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:23
# _public.php:238
# _widgets.php:30
# gals.php:50
# gals.php:56
# gals_actions.php:144
# gals_actions.php:149
$GLOBALS['__l10n']['Galleries']='Galeries';

# gal.php:48
# gals.php:199
$GLOBALS['__l10n']['New gallery']='Nouvelle galerie';

# gal.php:129
# galitemlist.php:32
# galupdate.php:32
$GLOBALS['__l10n']['Edit gallery']='Modifier la galerie';

# gal.php:138
$GLOBALS['__l10n']['next gallery']='galerie suivante';

# gal.php:146
$GLOBALS['__l10n']['previous gallery']='galerie précédente';

# gal.php:316
# gal.php:318
$GLOBALS['__l10n']['view gallery']='voir la galerie';

# gal.php:375
$GLOBALS['__l10n']['Gallery status:']='Etat de la galerie';

# gal.php:421
$GLOBALS['__l10n']['Media Directory:']='Répertoire contenant les media';

# gal.php:473
# galupdate.php:106
$GLOBALS['__l10n']['Items']='Eléments';

# gals.php:56
$GLOBALS['__l10n']['Main menu']='Menu principal';

# gals.php:78
$GLOBALS['__l10n']['Images']='Images';

# galupdate.php:113
$GLOBALS['__l10n']['Operations performed :']='Opérations effectuées :';

# galupdate.php:118
$GLOBALS['__l10n']['Operation performed']='Opération effectuée :';

# galupdate.php:125
$GLOBALS['__l10n']['Add image linked to media, add image to gallery']='Ajout d\'un billet attaché à l\'image, ajout de l\'image à la galerie';

# galupdate.php:135
$GLOBALS['__l10n']['Add image to gallery']='Ajout de l\'image à la galerie';

# galupdate.php:158
$GLOBALS['__l10n']['Create thumb']='Création de la miniature';

?>