<?php
// Français translation of RepriseCom, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# class.dc.repriseCom.php:157
$GLOBALS['__l10n']['Table galcomment not found']='Table galcomment non trouvée';

# class.dc.repriseCom.php:210
$GLOBALS['__l10n']['Number of comments in your database']='Nombre de commentaires dans votre base';

# class.dc.repriseCom.php:211
$GLOBALS['__l10n']['Number of comments in your old table for gallery']='Nombre de commentaires dans l\'ancienne table pour gallery';

# class.dc.repriseCom.php:212
$GLOBALS['__l10n']['Number of comments to resume']='Nombre de commentaires à reprendre';

# class.dc.repriseCom.php:213
$GLOBALS['__l10n']['Number of comments included']='Nombre de commentaires repris';

# index.php:99
$GLOBALS['__l10n']['No old prefix table define.']='L\'ancien prefix pour la table n\'est pas défini.';

# index.php:105
$GLOBALS['__l10n']['Limit for insert not defined.']='Aucune limite définie pour l\'insertion.';

# index.php:138
$GLOBALS['__l10n']['Waiting...']='Veuillez patienter...';

# index.php:156
$GLOBALS['__l10n']['Prerequisites']='Pré-requis';

# index.php:158
$GLOBALS['__l10n']['Notice ligne 1']='- Il est nécessaire d\'avoir déjà intégrer les galeries d\'images avec le nouveau plugin gallery';

# index.php:159
$GLOBALS['__l10n']['Notice ligne 2']='- Il ne doit pas y avoir 2 images avec le même nom de fichier sinon insertion en double';

# index.php:160
$GLOBALS['__l10n']['The backup of database is recommended']='La sauvegarde de votre base de données est vivement conseillée.';

# index.php:173
$GLOBALS['__l10n']['Message']='Message';

# index.php:177
$GLOBALS['__l10n']['Create temporaries tables successful']='Creation des tables temporaires ok';

# index.php:180
$GLOBALS['__l10n']['Update temporaries tables successful']='Mise à jour des tables temporaires ok';

# index.php:183
$GLOBALS['__l10n']['Comments correctly inserted']='Les commentaires ont été correctement insérés';

# index.php:186
$GLOBALS['__l10n']['Cleaner correctly terminated']='Nettoyage correctement terminé';

# index.php:189
$GLOBALS['__l10n']['Save configuration successful']='Sauvegarde de la configuration effectuée';

# index.php:198
$GLOBALS['__l10n']['List of treatments']='Liste des traitements';

# index.php:203
# index.php:205
# index.php:205
$GLOBALS['__l10n']['Creating temporaries tables']='Création des tables temporaires';

# index.php:212
# index.php:214
# index.php:214
$GLOBALS['__l10n']['Updating temporaries tables']='Mise à jour des tables temporaires';

# index.php:221
# index.php:223
$GLOBALS['__l10n']['Insert old comments']='Reprise des anciens commentaires';

# index.php:223
$GLOBALS['__l10n']['Start insert command']='Lancer l\'insertion';

# index.php:230
# index.php:232
$GLOBALS['__l10n']['Cleaning temporary elements']='Nettoyage des éléments temporaires';

# index.php:232
$GLOBALS['__l10n']['Cleaner starts']='Lancement du nettoyeur';

# index.php:249
$GLOBALS['__l10n']['Result']='Résultat';

# index.php:266
$GLOBALS['__l10n']['old prefix table']='Prefix des tables à reprendre';

# index.php:270
$GLOBALS['__l10n']['number comments limit for insert']='Limite du nombre de commentaires à insérer par page';

$GLOBALS['__l10n']['Temporary table']='Table temporaire';

$GLOBALS['__l10n']['Table not found']='Table non trouvée';

?>