<?php
// French translation of CompreSS, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:2
# index.php:102
# index.php:108
$GLOBALS['__l10n']['CompreSS']='CompreSS';

# class.compress.php:12
# class.compress.php:99
# class.compress.php:116
# class.compress.php:157
# class.compress.php:162
$GLOBALS['__l10n']['is not writable']='n\'est pas accessible en écriture';

# class.compress.php:117
# class.compress.php:156
$GLOBALS['__l10n']['is not readable']='n\'est pas accessible en lecture';

# class.compress.php:165
# class.compress.php:171
$GLOBALS['__l10n']['is not deletable']='ne peut pas être supprimé';

# class.compress.php:175
$GLOBALS['__l10n']['is not a backup file']='n\'est pas un fichier de sauvegarde';

# class.compress.php:264
$GLOBALS['__l10n']['Theme&nbsp;:']='Thème&nbsp;:';

# class.compress.php:265
$GLOBALS['__l10n']['default theme']='thème par défaut';

# class.compress.php:266
$GLOBALS['__l10n']['blog theme']='thème du blog';

# class.compress.php:270
$GLOBALS['__l10n']['file']='fichier';

# class.compress.php:270
$GLOBALS['__l10n']['size']='taille';

# class.compress.php:270
$GLOBALS['__l10n']['actions']='actions';

# class.compress.php:286
# index.php:65
$GLOBALS['__l10n']['of the original size']='de la taille originale';

# class.compress.php:292
$GLOBALS['__l10n']['uncompressed file']='fichier non compressé';

# class.compress.php:293
$GLOBALS['__l10n']['compress']='compresser';

# class.compress.php:299
$GLOBALS['__l10n']['compressed file']='fichier compressé';

# class.compress.php:306
$GLOBALS['__l10n']['original file']='fichier original';

# class.compress.php:307
# index.php:156
$GLOBALS['__l10n']['compress to']='compresser vers';

# class.compress.php:315
$GLOBALS['__l10n']['backup file']='fichier de sauvegarde';

# index.php:46
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:55
$GLOBALS['__l10n']['is not executable']='n\'est pas exécutable';

# index.php:66
$GLOBALS['__l10n']['The file&nbsp;:']='Le fichier&nbsp;:';

# index.php:66
$GLOBALS['__l10n']['has been compressed']='a été compressé';

# index.php:76
$GLOBALS['__l10n']['The backup file&nbsp;:']='Le fichier de sauvegarde&nbsp;:';

# index.php:76
$GLOBALS['__l10n']['has been deleted']='a été supprimé';

# index.php:83
$GLOBALS['__l10n']['All CSS files have been compressed']='Tous les fichiers CSS ont été compressés';

# index.php:89
$GLOBALS['__l10n']['All CSS backup files have been deleted']='Tous les fichiers de sauvegarde CSS ont été supprimés';

# index.php:95
$GLOBALS['__l10n']['All CSS compressed files have been replaced']='Tous les fichiers CSS compressés ont été remplacés';

# index.php:122
$GLOBALS['__l10n']['Compress CSSs']='Compresser les CSSs';

# index.php:125
$GLOBALS['__l10n']['All files']='Tous les fichiers';

# index.php:127
$GLOBALS['__l10n']['Compress CSS files']='Compresser les fichiers CSS';

# index.php:128
$GLOBALS['__l10n']['Delete backups files']='Supprimer les fichiers de sauvegarde';

# index.php:129
$GLOBALS['__l10n']['Replace compressed files with original files']='Remplacer les fichiers compressés par les fichiers originaux';

# index.php:138
# index.php:141
$GLOBALS['__l10n']['Options']='Options';

# index.php:142
$GLOBALS['__l10n']['Keep comments when compressing']='Garder les commentaires lors de la compression';

# index.php:144
$GLOBALS['__l10n']['Create an unique backup of CSS file every time a CSS backup file is compressed']='Créer une sauvegarde unique du fichier CSS à chaque fois qu\'un fichier de sauvegarde CSS est compressé';

# index.php:146
$GLOBALS['__l10n']['Text to include at the beginning of the compressed file:']='Texte à inclure au début du fichier compressé:';

# index.php:150
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:154
$GLOBALS['__l10n']['Help']='Aide';

# index.php:155
$GLOBALS['__l10n']['A copy of the original file (.css.bak) is created when a CSS file is compressed for the first time.']='Une copie du fichier original (.css.bak) est créée quand un fichier CSS est compressé pour la première fois.';

# index.php:156
$GLOBALS['__l10n']['To modify a CSS file, edit the original file (.css.bak), save it and then compress this file by clicking on']='Pour modifier un fichier CSS, éditez le fichier original (.css.bak), sauvez-le puis compressez-le en cliquant sur';

# index.php:157
$GLOBALS['__l10n']['delete the file and replace the compressed file by the original file if the file is original.']='supprime le fichier et remplace le fichier compressé par le fichier original si le fichier est original.';

?>