<?php
// French translation of CompreSS, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:24
# index.php:134
# index.php:140
$GLOBALS['__l10n']['CompreSS']='CompreSS';

# index.php:76
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:89
$GLOBALS['__l10n']['%s is not executable']='%s n\'est pas éxécutable';

# index.php:99
# lib.compress.php:354
$GLOBALS['__l10n']['(%s%% of the original size)']='(%s%% de la taille originale)';

# index.php:100
$GLOBALS['__l10n']['The file&nbsp;: %1$s has been compressed<br />%2$s']='Le fichier&nbsp;: %1$s a été compressé<br />%2$s';

# index.php:106
$GLOBALS['__l10n']['The backup file&nbsp;: %s has been deleted']='Le fichier de sauvegarde&nbsp;: %s a été supprimé';

# index.php:111
$GLOBALS['__l10n']['All CSS files have been compressed']='Tous les fichiers CSS ont été compressés';

# index.php:117
$GLOBALS['__l10n']['All CSS backup files have been deleted']='Tous les fichiers de sauvegarde CSS ont été supprimés';

# index.php:123
$GLOBALS['__l10n']['All CSS compressed files have been replaced']='Tous les fichiers CSS compressés ont été remplacés';

# index.php:144
$GLOBALS['__l10n']['Compress CSSs']='Compresser les CSSs';

# index.php:147
$GLOBALS['__l10n']['All files']='Tous les fichiers';

# index.php:150
$GLOBALS['__l10n']['Compress CSS files']='Compresser les fichiers CSS';

# index.php:152
$GLOBALS['__l10n']['Delete backups files']='Supprimer les fichiers de sauvegarde';

# index.php:154
$GLOBALS['__l10n']['Replace compressed files with original files']='Remplacer les fichiers compressés par les fichiers originaux';

# index.php:164
# index.php:167
$GLOBALS['__l10n']['settings']='paramètres';

# index.php:169
$GLOBALS['__l10n']['Keep comments when compressing']='Garder les commentaires lors de la compression';

# index.php:173
$GLOBALS['__l10n']['Create an unique backup of CSS file every time a CSS backup file is compressed']='Créer une sauvegarde unique du fichier CSS à chaque fois qu\'un fichier de sauvegarde CSS est compressé';

# index.php:176
$GLOBALS['__l10n']['Text to include at the beginning of the compressed file:']='Texte à inclure au début du fichier compressé:';

# index.php:176
$GLOBALS['__l10n']['optional']='facultatif';

# index.php:181
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:186
$GLOBALS['__l10n']['Help']='Aide';

# index.php:187
$GLOBALS['__l10n']['A copy of the original file (.bak.css) is created when a CSS file is compressed for the first time.']='Une copie du fichier original (.bak.css) est créée quand un fichier CSS est compressé pour la première fois.';

# index.php:189
$GLOBALS['__l10n']['To modify a CSS file, edit the original file (.bak.css), save it and then compress this file by clicking on']='Pour modifier un fichier CSS, éditez le fichier original (.bak.css), sauvez-le puis compressez-le en cliquant sur';

# index.php:190
# lib.compress.php:379
$GLOBALS['__l10n']['compress to']='compresser vers';

# index.php:193
$GLOBALS['__l10n']['delete the file and replace the compressed file by the original file if the file is original.']='supprime le fichier et remplace le fichier compressé par le fichier original si le fichier est original.';

# lib.compress.php:47
# lib.compress.php:141
# lib.compress.php:161
# lib.compress.php:216
# lib.compress.php:222
$GLOBALS['__l10n']['%s is not writable']='%s n\'est pas accessible en écriture';

# lib.compress.php:165
# lib.compress.php:212
$GLOBALS['__l10n']['%s is not readable']='%s n\'est pas accessible en lecture';

# lib.compress.php:228
# lib.compress.php:237
$GLOBALS['__l10n']['%s is not deletable']='%s ne peut pas être supprimé';

# lib.compress.php:244
$GLOBALS['__l10n']['%s is not a backup file']='%s n\'est pas un fichier de sauvegarde';

# lib.compress.php:326
$GLOBALS['__l10n']['default theme']='thème par défaut';

# lib.compress.php:329
$GLOBALS['__l10n']['blog theme']='thème du blog';

# lib.compress.php:331
$GLOBALS['__l10n']['Theme&nbsp;:']='Thème&nbsp;:';

# lib.compress.php:333
$GLOBALS['__l10n']['file']='fichier';

# lib.compress.php:333
$GLOBALS['__l10n']['size']='taille';

# lib.compress.php:333
$GLOBALS['__l10n']['actions']='actions';

# lib.compress.php:362
$GLOBALS['__l10n']['uncompressed file']='fichier non compressé';

# lib.compress.php:364
$GLOBALS['__l10n']['compress']='compresser';

# lib.compress.php:370
$GLOBALS['__l10n']['compressed file']='fichier compressé';

# lib.compress.php:377
$GLOBALS['__l10n']['original file']='fichier original';

# lib.compress.php:388
$GLOBALS['__l10n']['backup file']='fichier de sauvegarde';

?>