<?php
// French translation of CompreSS, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:24
# index.php:126
# index.php:132
$GLOBALS['__l10n']['CompreSS']='CompreSS';

# class.compress.php:35
# class.compress.php:125
# class.compress.php:142
# class.compress.php:186
# class.compress.php:191
$GLOBALS['__l10n']['is not writable']='n\'est pas accessible en écriture';

# class.compress.php:143
# class.compress.php:185
$GLOBALS['__l10n']['is not readable']='n\'est pas accessible en lecture';

# class.compress.php:194
# class.compress.php:200
$GLOBALS['__l10n']['is not deletable']='ne peut pas être supprimé';

# class.compress.php:204
$GLOBALS['__l10n']['is not a backup file']='n\'est pas un fichier de sauvegarde';

# class.compress.php:290
$GLOBALS['__l10n']['default theme']='thème par défaut';

# class.compress.php:291
$GLOBALS['__l10n']['blog theme']='thème du blog';

# class.compress.php:292
$GLOBALS['__l10n']['Theme&nbsp;:']='Thème&nbsp;:';

# class.compress.php:294
$GLOBALS['__l10n']['file']='fichier';

# class.compress.php:294
$GLOBALS['__l10n']['size']='taille';

# class.compress.php:294
$GLOBALS['__l10n']['actions']='actions';

# class.compress.php:311
# index.php:89
$GLOBALS['__l10n']['of the original size']='de la taille originale';

# class.compress.php:317
$GLOBALS['__l10n']['uncompressed file']='fichier non compressé';

# class.compress.php:318
$GLOBALS['__l10n']['compress']='compresser';

# class.compress.php:324
$GLOBALS['__l10n']['compressed file']='fichier compressé';

# class.compress.php:331
$GLOBALS['__l10n']['original file']='fichier original';

# class.compress.php:333
# index.php:187
$GLOBALS['__l10n']['compress to']='compresser vers';

# class.compress.php:341
$GLOBALS['__l10n']['backup file']='fichier de sauvegarde';

# index.php:70
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès.';

# index.php:79
$GLOBALS['__l10n']['is not executable']='n\'est pas exécutable';

# index.php:90
$GLOBALS['__l10n']['The file&nbsp;:']='Le fichier&nbsp;:';

# index.php:90
$GLOBALS['__l10n']['has been compressed']='a été compressé';

# index.php:100
$GLOBALS['__l10n']['The backup file&nbsp;:']='Le fichier de sauvegarde&nbsp;:';

# index.php:100
$GLOBALS['__l10n']['has been deleted']='a été supprimé';

# index.php:107
$GLOBALS['__l10n']['All CSS files have been compressed']='Tous les fichiers CSS ont été compressés';

# index.php:113
$GLOBALS['__l10n']['All CSS backup files have been deleted']='Tous les fichiers de sauvegarde CSS ont été supprimés';

# index.php:119
$GLOBALS['__l10n']['All CSS compressed files have been replaced']='Tous les fichiers CSS compressés ont été remplacés';

# index.php:146
$GLOBALS['__l10n']['Compress CSSs']='Compresser les CSSs';

# index.php:149
$GLOBALS['__l10n']['All files']='Tous les fichiers';

# index.php:151
$GLOBALS['__l10n']['Compress CSS files']='Compresser les fichiers CSS';

# index.php:152
$GLOBALS['__l10n']['Delete backups files']='Supprimer les fichiers de sauvegarde';

# index.php:153
$GLOBALS['__l10n']['Replace compressed files with original files']='Remplacer les fichiers compressés par les fichiers originaux';

# index.php:163
# index.php:166
$GLOBALS['__l10n']['Options']='Options';

# index.php:168
$GLOBALS['__l10n']['Keep comments when compressing']='Garder les commentaires lors de la compression';

# index.php:172
$GLOBALS['__l10n']['Create an unique backup of CSS file every time a CSS backup file is compressed']='Créer une sauvegarde unique du fichier CSS à chaque fois qu\'un fichier de sauvegarde CSS est compressé';

# index.php:174
$GLOBALS['__l10n']['Text to include at the beginning of the compressed file:']='Texte à inclure au début du fichier compressé:';

# index.php:174
$GLOBALS['__l10n']['optional']='facultatif';

# index.php:178
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

# index.php:183
$GLOBALS['__l10n']['Help']='Aide';

# index.php:184
$GLOBALS['__l10n']['A copy of the original file (.css.bak) is created when a CSS file is compressed for the first time.']='Une copie du fichier original (.css.bak) est créée quand un fichier CSS est compressé pour la première fois.';

# index.php:186
$GLOBALS['__l10n']['To modify a CSS file, edit the original file (.css.bak), save it and then compress this file by clicking on']='Pour modifier un fichier CSS, éditez le fichier original (.css.bak), sauvez-le puis compressez-le en cliquant sur';

# index.php:190
$GLOBALS['__l10n']['delete the file and replace the compressed file by the original file if the file is original.']='supprime le fichier et remplace le fichier compressé par le fichier original si le fichier est original.';

?>