
dotclear.messageExpander=function(line){var td=line.firstChild;var img=document.createElement('img');img.src=dotclear.img_plus_src;img.alt=dotclear.img_plus_alt;img.className='expand';$(img).css('cursor','pointer');img.line=line;img.onclick=function(){dotclear.viewMessageContent(this,this.line);};td.insertBefore(img,td.firstChild);};dotclear.viewMessageContent=function(img,line){var messageId=line.id.substr(1);var tr=document.getElementById('ce'+messageId);if(!tr){tr=document.createElement('tr');tr.id='ce'+messageId;var td=document.createElement('td');td.colSpan=6;td.className='expand';tr.appendChild(td);img.src=dotclear.img_minus_src;img.alt=dotclear.img_minus_alt;$.get('services.php',{f:'getMessageById',id:messageId},function(data){var rsp=$(data).children('rsp')[0];if(rsp.attributes[0].value=='ok'){var message=$(rsp).find('message_display_content').text();if(message){$(td).append(message);var message_spam_disp=$(rsp).find('message_spam_disp').text();$(td).append('<p>'+message_spam_disp+'</p>');}}else{alert($(rsp).find('message').text());}});$(line).toggleClass('expand');line.parentNode.insertBefore(tr,line.nextSibling);}
else if(tr.style.display=='none')
{$(tr).toggle();$(line).toggleClass('expand');img.src=dotclear.img_minus_src;img.alt=dotclear.img_minus_alt;}
else
{$(tr).toggle();$(line).toggleClass('expand');img.src=dotclear.img_plus_src;img.alt=dotclear.img_plus_alt;}};$(function(){$('#form-messages tr.line').each(function(){dotclear.messageExpander(this);});$('.checkboxes-helpers').each(function(){dotclear.checkboxesHelpers(this);});dotclear.messagesActionsHelper();});

dotclear.messagesActionsHelper=function(){$('#form-messages').submit(function(){var action=$(this).find('select[name="action"]').val();var checked=false;$(this).find('input[name="messages[]"]').each(function(){if(this.checked){checked=true;}});if(!checked){return false;}
if(action=='delete'){return window.confirm(dotclear.msg.confirm_delete_messages);}
return true;});}
$(function(){if(!document.getElementById){return;}
if(document.getElementById('edit-message'))
{var formatField=$('#message_format').get(0);$(formatField).change(function(){contentTb.switchMode(this.value);});var contentTb=new jsToolBar(document.getElementById('message_content'));contentTb.context='post';}
$('#message-preview').modalWeb($(window).width()-40,$(window).height()-40);$('#edit-message').onetabload(function(){dotclear.hideLockable();var post_dtPick=new datePicker($('#message_dt').get(0));post_dtPick.img_top='1.5em';post_dtPick.draw();$('input[name="delete"]').click(function(){return window.confirm(dotclear.msg.confirm_delete_message);});$('#notes-area label').toggleWithLegend($('#notes-area').children().not('label'),{cookie:'dcx_message_notes',hide:$('#message_notes').val()==''});contentTb.switchMode(formatField.value);var h=document.createElement('h4');var a=document.createElement('a');a.href='#';$(a).click(function(){var params={xd_check:dotclear.nonce,f:'validatePostMarkup',content:$('#message_content').text(),format:$('#message_format').get(0).value};$.post('services.php',params,function(data){if($(data).find('rsp').attr('status')!='ok'){alert($(data).find('rsp message').text());return false;}
if($(data).find('valid').text()==1){var p=document.createElement('p');p.id='markup-validator';if($('#markup-validator').length>0){$('#markup-validator').remove();}
$(p).addClass('message');$(p).text(dotclear.msg.xhtml_valid);$(p).insertAfter(h);$(p).backgroundFade({sColor:'#666666',eColor:'#ffcc00',steps:50},function(){$(this).backgroundFade({sColor:'#ffcc00',eColor:'#666666'});});}else{var div=document.createElement('div');div.id='markup-validator';if($('#markup-validator').length>0){$('#markup-validator').remove();}
$(div).addClass('error');$(div).html('<p><strong>'+dotclear.msg.xhtml_not_valid+'</strong></p>'+$(data).find('errors').text());$(div).insertAfter(h);$(div).backgroundFade({sColor:'#ffffff',eColor:'#ff9999',steps:50},function(){$(this).backgroundFade({sColor:'#ff9999',eColor:'#ffffff'});});}
return false;});return false;});a.appendChild(document.createTextNode(dotclear.msg.xhtml_validator));h.appendChild(a);$(h).appendTo('#message-content');});$('#add-message').onetabload(function(){messageTb.draw('xhtml');});});
