<?php
// Français translation of notifications, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:15
# index.php:57
# index.php:61
$GLOBALS['__l10n']['Notifications']='Notifications';

# _services.php:21
$GLOBALS['__l10n']['%s at %s']='%s à %s';

# _services.php:37
$GLOBALS['__l10n']['By %s on %s']='Par %s le %s';

# inc/class.notifications.behaviors.php:22
# inc/class.notifications.behaviors.php:57
# inc/class.notifications.behaviors.php:81
# inc/class.notifications.behaviors.php:105
$GLOBALS['__l10n']['%s created']='%s créé(e)';

# inc/class.notifications.behaviors.php:34
# inc/class.notifications.behaviors.php:69
# inc/class.notifications.behaviors.php:93
$GLOBALS['__l10n']['%s updated']='%s mis(e) à jour';

# inc/class.notifications.behaviors.php:34
$GLOBALS['__l10n']['Entry']='Billet';

# inc/class.notifications.behaviors.php:46
$GLOBALS['__l10n']['Entry deleted']='Billet supprimé';

# inc/class.notifications.behaviors.php:81
$GLOBALS['__l10n']['New comment']='Nouveau commentaire';

# inc/class.notifications.behaviors.php:105
$GLOBALS['__l10n']['New trackback']='Nouveau rétrolien';

# inc/class.notifications.behaviors.php:117
$GLOBALS['__l10n']['New 404 error page displayed about %s']='Nouvelle page d\'erreur 404 affichée à propos de %s';

# inc/class.notifications.behaviors.php:117
$GLOBALS['__l10n']['this URL']='cette URL';

# inc/class.notifications.behaviors.php:159
$GLOBALS['__l10n']['Last visit on administration interface']='Dernière visite sur l\'interface d\'administration';

# index.php:17
$GLOBALS['__l10n']['Impossible to load notification configuration']='Impossible de charger la configuration du plugin notifications';

# index.php:38
$GLOBALS['__l10n']['Configuration successfully updated.']='Configuration mise à jour avec succès';

# index.php:46
$GLOBALS['__l10n']['Top - Left']='Haut - Gauche';

# index.php:47
$GLOBALS['__l10n']['Top - Right']='Haut - Droite';

# index.php:48
$GLOBALS['__l10n']['Bottom - Left']='Bas - Gauche';

# index.php:49
$GLOBALS['__l10n']['Bottom - Right']='Bas - Droite';

# index.php:68
$GLOBALS['__l10n']['Blog notifications']='Notifications du blog';

# index.php:71
$GLOBALS['__l10n']['Enable posts notifications']='Activer les notifications en rapport avec les billets';

# index.php:75
$GLOBALS['__l10n']['Enable categories notifications']='Activer les notifications en rapport avec les catégories';

# index.php:79
$GLOBALS['__l10n']['Enable comments notifications']='Activer les notifications en rapport avec les commentaires';

# index.php:83
$GLOBALS['__l10n']['Enable trackbacks notifications']='Activer les notifications en rapport avec les rétroliens';

# index.php:87
$GLOBALS['__l10n']['Enable 404 errors notifications']='Activer les notifications en rapport avec les page d\'erreur 404';

# index.php:92
$GLOBALS['__l10n']['Notifications options']='Options des notifications';

# index.php:95
$GLOBALS['__l10n']['Sticky new notifications']='Coller les notifications pour les éléments de type : nouveaux';

# index.php:99
$GLOBALS['__l10n']['Sticky update notifications']='Coller les notifications pour les éléments de type : mis à jour';

# index.php:103
$GLOBALS['__l10n']['Sticky delete notifications']='Coller les notifications pour les éléments de type : supprimés';

# index.php:107
$GLOBALS['__l10n']['Sticky message notifications']='Coller les notifications pour les éléments de type : messages';

# index.php:111
$GLOBALS['__l10n']['Sticky error notifications']='Coller les notifications pour les éléments de type : erreurs';

# index.php:115
$GLOBALS['__l10n']['Position of notifications']='Positions des notifications';

# index.php:119
$GLOBALS['__l10n']['Time to display notifications (second)']='Temps d\'affichage des notifications (en secondes)';

# index.php:123
$GLOBALS['__l10n']['Time beetween each request (second)']='Temps entre chaque requête (en secondes)';

# index.php:127
$GLOBALS['__l10n']['Notifications maintenance']='Maintenance des notifications';

# index.php:130
$GLOBALS['__l10n']['Auto-clean notifications']='Nettoyage automatique des notifications';

# index.php:136
$GLOBALS['__l10n']['Save configuration']='Enregistrer la configuration';

?>