<?php
// Français translation of SnapMe, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:36
# _admin.php:37
# index.php:68
$GLOBALS['__l10n']['SnapMe']='SnapMe';

# _admin.php:37
$GLOBALS['__l10n']['Title:']='Titre :';

# _admin.php:38
$GLOBALS['__l10n']['Display :']='Affichage :';

# _admin.php:38
$GLOBALS['__l10n']['Last Snap']='Le dernier snap';

# _admin.php:38
$GLOBALS['__l10n']['Random Snap']='Un snap al&eacute;atoire';

# _admin.php:39
$GLOBALS['__l10n']['Home page only']='Uniquement sur la page d\'accueil';

# _public.php:111
$GLOBALS['__l10n']['Unknown']='Inconnu';

# _public.php:125
$GLOBALS['__l10n']['No snap']='Aucun snap';

# _public.php:129
$GLOBALS['__l10n']['Take a picture']='Prendre une photo';

# _public.php:130
$GLOBALS['__l10n']['Watch the gallery']='Voir la galerie';

# _public.php:145
# _public.php:176
$GLOBALS['__l10n']['SnapMe Gallery']='Galerie SnapMe';

# _public.php:173
$GLOBALS['__l10n']['No snap has been found']='Aucun snap n\'a &eacute;t&eacute; trouv&eacute;';

# _public.php:198
$GLOBALS['__l10n']['Remove']='Supprimer';

# _public.php:215
$GLOBALS['__l10n']['Snap']='Snap';

# _public.php:215
$GLOBALS['__l10n']['Today']='Aujourd\'hui';

# _public.php:215
# _public.php:217
$GLOBALS['__l10n']['from']='de';

# index.php:61
$GLOBALS['__l10n']['Snapshot deleted.']='Snapshot correctement supprim&eacute;';

# index.php:64
$GLOBALS['__l10n']['Snapshot not deleted.']='Suppression du snapshot impossible';

# index.php:74
$GLOBALS['__l10n']['About']='A propos';

# index.php:75
$GLOBALS['__l10n']['Plugin SnapMe by Ludovic Toinel']='Plugin SnapMe par Ludovic Toinel';

?>