<?php
// French translation of Post Maker, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:37
# index.php:32
# index.php:39
$GLOBALS['__l10n']['Define custom entries']='Definition des billets personnalisés';

?>